### PR TITLE
LPS-58141 Add all available network interface IPs on portal startup

### PR DESCRIPTION
**Pull request by SamZiemer**
On Linux machines, the computer name cannot be retrieved, so by default the computer address is set to the loop back address. Instead we should iterate through all available network interfaces and add them to a set which is available in portalImpl.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Sam,

Is the "_computerAddress" that's populated right above included in your "_computerAddresses"? Also, should we modify the calls to "getComputerAddress" to use "_computerAddresses" instead?

**Comment by jonathanmccann** [comment]
Closing per our discussion. Please SDH this fix but continue looking at the LPS in order to merge together _computerAddress and _computerAddresses and create a new method to check if a hostname is contained in the list of computer addresses.

**Pull request closed without merging**
