### PR TITLE
Pr 20

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @wanderlast
From Lianne:

> LPP: https://issues.liferay.com/browse/LPP-28517
> LPS: https://issues.liferay.com/browse/LPS-77428
> 
> Certain portlet types share portlet preferences across sites due to using the 'shared' portlet id and 'shared' owner id of 0 and 0. While this is understandable for certain portlets (e.g. those that are designated as "company wide"), this makes less sense for those that are explicitly designated as "unique per layout" and "unique per group". This causes these portlets (Forms being one of the primary offenders) to not be displayed in the staging menu under the "since last publish" option if any other staging site has been published after the form was made.
> 
> The fix has these portlets each have their own preferences based on groupid/ownerid, ensuring that these preferences stay unique per group.
> 
> If you have any other questions or concerns, please let me know. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
tests didn't finish, so I'll let it run on your repo over the weekend.

**Comment by ChrisKian** [comment]
ci:test

**Comment by ChrisKian** [comment]
Hey @wanderlast, 
Can you take a look at these test failures?  They seem like they could be related.  Thanks!

**Comment by jonathanmccann** [comment]
While you're doing that, I'll re-run the tests to make sure.

**Comment by jonathanmccann** [comment]
ci:test

**Comment by wanderlast** [comment]
Hi @ChrisKian @jonathanmccann 
It'll take a while for me to look through all of these tests, but I know that some of them are definitely from the fix. At least a handful of tests explicitly conflict with the fix, e.g.:

testUdatePortletPreferencesPlid1NotNullNull()
```
		PortletPreferencesImpl portletPreferencesImpl = setLastPublishDate(
			group, lastPublishDate, layout);

		Assert.assertEquals(
			PortletKeys.PREFS_OWNER_ID_DEFAULT,
			portletPreferencesImpl.getOwnerId());
)
```

specifically checks to see that the ownerID for these preferences are 0. Since the default setting is for a portlet's preferences to be both unique per layout and unique per group (per [this at least](https://web.liferay.com/web/pmesotten/blog/-/blogs/user-specific-versus-shared-portlet-preferences-part-1) ), my fix will always fail this test as far as I can tell since I explicitly set these to have an ownerID equal to their groupID versus the "0" that it used to be. I can definitely take another look at this issue if you guys want it to conform to these tests as well though. Thanks!

**Comment by ChrisKian** [comment]
Hey @wanderlast,

If the tests need reworking, that's fine, we just need them to be updated and explicitly clear what is happening.

Also, it's best if you make the test changes, verify the tests all pass, add your changes, and verify again they all still pass (unless there are test cases which specifically rely on your changes, then it's acceptable if those fail at first, or you add them in afterwards).

I can help you if needed, however I'll need to close this PR since it's not complete.  Let me know if you have any troubles.  Thanks!

**Comment by jonathanmccann** [comment]
ci:stop

**Pull request closed without merging**
