### PR TITLE
LPS-65085 master

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-65085

Sitemap.xml is not returned when using valid IP addresses or domain names that are not explicitly set as the virtual host or present in the virtualHost table. Currently the logic uses ```getVirtualHost(host)```, which throws an exception if the virtual host entered does not exist in the database, and does not display the sitemap.xml as expected. I think it would be better to use ```fetchVirtualHost(host)``` and return null and defer to the default virtual host so that the sitemap.xml still displays as expected for valid sitemap.xml URLs rather than throwing an exception.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Do you think this needs a test?

**Comment by dustinryerson** [comment]
I may make one minor change to this fix. Please don't push this up yet. Thanks!

**Comment by jonathanmccann** [comment]
Hey Dustin,

Let me know when you want this to be reviewed. I would say that a test might be good for this class but I'm not sure how it would work out due to how the sitemap is being returned.

**Comment by dustinryerson** [comment]
Hey @jonathanmccann,

I've updated the pull with an additional check to ensure that the host is a valid host if it is not stored in the virtualHost table.

You bring up a good point regarding the test. If you don't mind, let's push this forward (after CI tests pass) without one and see if BChan asks for one?

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Weird. I ran SF and it didn't come up with anything.

**Comment by jonathanmccann** [comment]
It doesn't look like it's coming from your changes:

```
[exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter FAILED
     [exec]     org.junit.ComparisonFailure: ../../../modules/apps/web-experience/site/site-memberships-web/src/main/resources/META-INF/resources/init.jsp expected:<...rtal.kernel.service.[]MembershipRequestLoc...> but was:<...rtal.kernel.service.[GroupLocalServiceUtil" %><%@
     [exec]     page import="com.liferay.portal.kernel.service.]MembershipRequestLoc...>
```

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mika for further review: https://github.com/mikakoivisto/liferay-portal/pull/124

**Pull request closed without merging**
