### PR TITLE
LPS-79311

### PR DESCRIPTION
**Pull request by ChrisKian**
LPS: https://issues.liferay.com/browse/LPS-79311
LPP: https://issues.liferay.com/browse/LPP-29419

From @joshuacords:
> These changes make sense to me. I'm not 100% on moving the properties.put("collision", contextPath) into the if (!collidedBundleIds.isEmpty()) brackets, but I don't see why you would want to set the property if it isn't a real collision and it wasn't ever called before anyways. (Because "false" was never passed in for collision before.)
> 
> The one downside I see is that when the bundles are started, both conflicting modules will be throwing a collision error. (Or if there's N modules, I would assume 2^N errors would be thrown). Considering that preventing this would take extra checks or addition variables, I believe it's fine to leave it as it is.
> 
> Notes from @JaredDomio
> Problem: When two bundles have the same Web-ContextPath no log message is displayed to illustrate the potential problem having two Web-ContextPath set to the same value can have. Having the Web-ContextPath set to the same value can cause unexpected behavior for the portlets with the same Web-ContextPath. Without an error or warning message it can be difficult for the user to identify the root cause of the issue.
> 
> Solution: There already exists a collision check in EventUtil.java that can identify when multiple bundles have the same Web-ContextPath. I made slight modifications to the collision check and added a log statement at the end of the collision check. The collision check is triggered when a portlet is first deployed. The log will give user a warning and list out all bundles that have collisions if a collision is detected.

### CODE REVIEW

**Comment by ChrisKian** [comment]
Test failures seem unrelated.  See https://github.com/ChrisKian/liferay-portal/pull/38

**Comment by jonathanmccann** [comment]
@ChrisKian What does the log look like when logging the list? I'm worried it'll output the object rather than the strings inside of it.

**Comment by JaredDomio** [comment]
@jonathanmccann, Here's a screen shot of the log. 
image

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1385

**Comment by jonathanmccann** [comment]
@JaredDomio Thanks for the screen shot!

**Pull request closed without merging**
