### PR TITLE
LPS-88170 Changed variables and created check for bad column variables

### PR DESCRIPTION
**Pull request by gregory-bretall**
Resent from 
https://github.com/gregory-bretall/liferay-portal/pull/130#issue-236664662

Test Results: 
https://github.com/gregory-bretall/liferay-portal/pull/130#issuecomment-445047051
https://github.com/gregory-bretall/liferay-portal/pull/130#issuecomment-445025157

https://issues.liferay.com/browse/LPS-88170

It  seems to make sense to me, but I don't really know if there are any standards for stuff like this from whoever is in charge of service builder's code.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
1. If you're going to change the template then you'll need to rebuild all of the services. I would say to leave the service alone to avoid needing to change so many files.

2. Is there a reason you're adding a new `bad_column_variables` instead of using the existing `bad_column_names`? The later already seems to have references to variables to avoid clashes and these are technically bad column names.

**Comment by gregory-bretall** [comment]
@fortunatomaldonado could you look into Jonathan's comment here and resend your PR when you've updated with those suggestions in mind?

**Comment by fortunatomaldonado** [comment]
Hello @jonathanmccann,

From my understanding, the `bad_column_names` are still being used in the database creation [but are being modified.](https://github.com/liferay/liferay-portal/blob/master/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java#L5433) Most of the words in this list will not cause any errors and so if I included the full list, it will require customers, that are using these names, to upgrade their database. I think. 

That is why I wanted to change the variable names that are causing issues in the template and create a new list to prevent any work for the customers. 

Let me know if this makes sense or if I am completely off.

**Comment by jonathanmccann** [comment]
That makes more sense, thanks for explaining that.

We'll still have to re-run the service builder so our existing files have the new variable names (`oValue`, etc.) or we can leave that out and move forward with the blacklist.

**Comment by fortunatomaldonado** [comment]
By blacklist, do you mean the `bad_column_names` or another list with only the error causing words?

Yeah I am not sure what would be the best option. The customer that brought up this issue, is using `value` as a column name and that's why I was trying to prevent any further work on their end. Do you have any strong opinions on which road we should take? If not, I can ask the SME for Core, which I believe is Minhchau.

**Comment by jonathanmccann** [comment]
I meant blacklist as the one you created but change the variable names to what they are currently (`values` vs `oValues`) - https://github.com/jonathanmccann/liferay-portal/pull/1728/files#diff-b59a9b088deaba504cad3ae87968f166

I'd rather not have to modify every service file we maintain but understand why you want to do it. I would go ahead and ask either of them (Minhchau or Eric) to see what they think and we can go from there.

**Comment by fortunatomaldonado** [comment]
Okay got it.

I'll do that, thank you for your help!

**Pull request closed without merging**
