### PR TITLE
[TECHNICAL-SUPPORT] LPS-70427

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @joshuacords how many roles did you test this with? Looking at https://github.com/jonathanmccann/liferay-portal/pull/1219/commits/5cf5781139efc9fd20c73ffe7aee342251ce63a9#diff-ac60ac04b003694cd8fa94f1464c6a51R1390 makes me think we'll go over the parameter limit on particular databases (SQLServer, etc.) See https://issues.liferay.com/browse/LPS-69836 for an example of this.

It shouldn't be hard to modify and it would future proof ourselves in case the list of role IDs does get large in the future. Let me know what you think though.

**Comment by joshuacords** [comment]
Let me make that modification.

**Comment by jonathanmccann** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1226

**Pull request closed without merging**
