### PR TITLE
LPS-72274 Log and create a UI warning for unmapped mvcRenderCommandName's

### PR DESCRIPTION
**Pull request by SGM3**
This PR does needs a build-lang. Adds additional logging to MVCPortlet to log bad usage of mvRenderCommandName's.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@SGM3 Please look at my changes for simplifying the logic.

Also, after seeing the UI message, I talked with @dustinryerson and we agreed that the UI messages should be reserved for information that the end user should see. Since this message would probably be confusing for most users, the warning log should be sufficient and give enough information about the issue that happened. I dropped the commits dealing with the UI and am only pushing forward the commits for adding the logging.

Please let me know if you have any concerns.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1309

**Comment by SGM3** [comment]
Not exactly my concern but from Nathan Shaw from [LPSP-241](https://issues.liferay.com/browse/LPSP-241):

> If an incorrectly mapped mvcRenderCommandName is provided the server silently re-displays the current page. I've seen this mentioned several times now and what is really needed is 1) a UI message that the command failed, and 2) a WARN-level statement in the server logs. This was happening a lot with custom portlets following the regression in FP8 which changed some portlet ids but it makes the developer experience much more difficult at any time.

**Comment by SGM3** [comment]
The UI message approach I took might be confusing (with this approach since it highlights on which portlet the command failed), but maybe a (senna?) UI message similar to the "Oops, this is taking too long" would be more appropriate? Not familiar how to adopt that approach.

**Comment by jonathanmccann** [comment]
I think that it still goes back to whether or not normal users are going to be running into this issue and if the message would be useful for them. If this issue is occurring, it's probably due to a bad portlet and the developer needs to address it. They should have access to the logs and can see the error.

If after this is committed, you're still getting pushed (or want to push) for a UI message, then feel free to open that discussion with Dustin.

**Comment by SGM3** [comment]
Also worth mentioning, action requests with a bad command name fail quite verbosely. Nathan contrasted this with how, from the perspective of the user, the portlet functionally hits the doView as if the the command name was parsed from the request.

I would also argue similar to how the action request does not silently "do nothing", the portlet shouldn't simply re-render with the doView as if nothing had gone wrong.

Ideally this type of issue should be made very apparent during the development phase. I would either make the argument to either include a UI message or make the log level `ERROR` since this is a detected configuration error. This is just my personal opinion.

**Pull request closed without merging**
