### PR TITLE
LPS-4959 Provide the current portal server port when generating the p…

### PR DESCRIPTION
**Pull request by ericyanLr**
…ortal URL

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Eric,

If you still have your test environment available, could you try testing out what gets returned from

PortalUtil.getLayoutSetDisplayURL

It has similar logic using Http.HTTP_PORT so if that call returns the incorrect URL as well, we should fix it there too.

**Comment by ericyanLr** [comment]
Hey @jonathanmccann,

I have just updated my branch with a new commit to update the getLayoutSetDisplayURL method as well.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3885

**Pull request closed without merging**
