### PR TITLE
[TECHNICAL-SUPPORT] LPS-74930

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Jonathan,

it turns out we don't need to seperate out the key generation to a new method, there are several places throughout the file that generate a key for a file name, but in a few different ways. The agreed upon way seems to be just generate a key in the method where it is needed. Let me know if trhere are any questions.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
A few things:

1. ```s3Object``` is no longer being used so we don't need it nor the finally block.
2. ```doesObjectExist``` throws ```AmazonServiceException``` and ```SdkClientException```. We should handle it along with the NoSuchFileException like ```getS3Object``` does.

**Comment by SamZiemer** [comment]
Thanks, Jonathan, I have resent it here: https://github.com/jonathanmccann/liferay-portal/pull/1426

**Pull request closed without merging**
