### PR TITLE
LPS-57125 Revert "LPS-16283"

### PR DESCRIPTION
**Pull request by ericyanLr**
This reverts commit ad44128a204876bcb94575d72f7283377c04ee0d.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Can you please outline why we need to revert this fix? Also, did you test the steps on LPS-16283 and confirm that it works properly?

**Comment by ericyanLr** [comment]
Hey Jonathan,

Below is an overview for the reversion.

##### Why Revert LPS-16283
>
* The fix from LPS-16283 introduces a problem that forces a redirect to the default landing page whenever BASIC_AUTH is used.
* For our case, when a user tries to view a private rss feed and is first required to login via BASIC_AUTH, the expected result should be the RSS Feed after a successful login.
* Instead, the user is redirected to the default landing page.

##### Does Reverting "LPS-16283" cause a regression for the original issue?
>
* The supposed issue was that the user would not be redirected to a custom set landing page (Ex: http://localhost:8080/web/guest/customLandingPage) after logging in via BASIC_AUTH
* Normally, if a user accesses the main portal (http://localhost:8080) via the normal login, they would be redirected to the landing page.
* But, accessing the portal via BASIC_AUTH actually should not have the same behavior.
For this case, accessing the main portal (http://localhost:8080) via BASIC_AUTH should show the home page.
* If the user wanted to be redirected to default landing page via BASIC_AUTH, they can instead access the main servlet (http://localhost:8080/c), which should direct the user to the default landing page

##### Actual Results after reverting LPS-16283
>
* When the user is accessing a private rss feed via BASIC_AUTH, they are redirected to the RSS Feed after logging in successfully.
* When the user is accessing the main portal (http://localhost:8080) via BASIC_AUTH, they are redirected to the home page after logging in successfully
* When the user is accessing the main servlet (http://localhost:8080/c) via BASIC_AUTH, they are redirected to the default landing page after logging in successfully

**Comment by jonathanmccann** [comment]
Reviewed and sent to Hugo for further review: https://github.com/hhuijser/liferay-portal/pull/2428

**Pull request closed without merging**
