### PR TITLE
LPS-96793 Add Data Provider fields to FieldSettings

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-96793

Adding the Data Provider fields to the `FieldSettings` so that it will not be removed when creating a Data Provider.
Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jeyvison for further review: https://github.com/jeyvison/liferay-portal/pull/438

**Comment by jonathanmccann** [comment]
ci:stop

**Pull request closed without merging**
