### PR TITLE
LPS-65342

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
just fyi, julio said this could forwarded to the collaboration team

**Comment by jonathanmccann** [comment]
@ChrisKian @BryanEngler,

Isn't https://github.com/jonathanmccann/liferay-portal/pull/978/commits/e18217938c467ecf7308c4a1561f62c02eabb91f making the fix the way Julio said not to make it?

Also, where is the fix for User Groups?

**Comment by ChrisKian** [comment]
Looking at Julio's responses, he never mentioned roles.  Also, I couldn't find anything similar to a portletDataHandler for roles.

The fix for userGroups is here https://github.com/jonathanmccann/liferay-portal/pull/978/commits/ff854804b35b7f1669f5deca04604a09862beae7#diff-71e719e586300333a4fe871d75de78f7R56.  The usergroup is stored in the group_ table, so we call for the group to be deleted here https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/UserGroupLocalServiceImpl.java#L354.  This will run the same logic for group, which calls the portletDataHandler.  Then, as we delete the group, if the group is a site, we use the groupId to delete, otherwise (it's a userGroup) we use the classPK.

Let me know if you have any questions, or if you have a better solution on how to delete announcementsEntries for roles.

**Comment by jonathanmccann** [comment]
I tested again and could still reproduce the issue with User Groups and even regular Groups were broken as well. I'm not sure if something got changed in the source formatting, but please test this out again and let me know if you cannot reproduce or have any questions.

**Pull request closed without merging**
