### PR TITLE
LPS-57822 Application display templates active permissions are not ch…

### PR DESCRIPTION
**Pull request by Preston-Crary**
...ecked when defineding permissions of Site/Organization Roles, see edit_role_permissions_resource.jsp

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Preston,

1. Why are you adding the logic to the JSP instead of extracting it out of both JSPs to a Util class?
2. Why did you not copy over the logic surrounding "supportsFilterByGroup"?

**Comment by Preston-Crary** [comment]
1. Because I wanted to leave out the "supportsFilterByGroup" logic it would be somewhat awkward to extract.  I chose to instead focus on cleaning up 537ba69a543a2a167ed8f6a31bc844f43382dd33.
2. The "supportsFilterByGroup" logic does does not need to be executed because we know that it supportsFilterByGroup since we are working with an ADT, that's why it is hardcoded.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/978

**Pull request closed without merging**
