### PR TITLE
LPS-58006

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@kevinccruz 

Does this fix need to be applied to other portlets as well?

**Comment by kevinccruz** [comment]
@jonathanmccann I'm actually not sure, but from what I've heard this is something that was fixed/sdh'ed before.

**Comment by jonathanmccann** [comment]
Ok, can you please test it out then and let me know? Just taking a quick look, there seem to be many other places that open up a dialog in order to select an object and some of them already use "destroyOnHide". I want to make sure we fix this everywhere so that we don't keep having to fix the same bug over and over again.

**Comment by kevinccruz** [comment]
@jonathanmccann Great call, just tested others and found 3 more (all in document library). I've gone ahead and sent another pull request to you, so you can feel free to close this one at your convenience.

**Comment by BryanEngler** [comment]
1approvalsm

**Pull request closed without merging**
