### PR TITLE
LPS-82327 Created a check for the filename to prevent xss

### PR DESCRIPTION
**Pull request by gregory-bretall**
Resent from https://github.com/gregory-bretall/liferay-portal/pull/82

Test Results: https://github.com/gregory-bretall/liferay-portal/pull/82#issuecomment-396761800

https://issues.liferay.com/browse/LPS-82327

Explanation for changes found here: https://github.com/gregory-bretall/liferay-portal/pull/82#issue-194417357

Please note that the purpose of replacing the .html# with a string instead of empty string is cover the case where a file named .html#.{image file extension} is uploaded and keeping that file name valid.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@gregory-bretall @fortunatomaldonado To me it makes more sense to add the `#` character to the property `dl.char.blacklist`. What do you think?

**Comment by gregory-bretall** [comment]
Hi @jonathanmccann, I think we had originally avoided that because we wanted to make sure valid filenames with # in them wouldn't be filtered. However, we were unsure whether having # in a filename is valid or not, so I can see removing that as a possible alternate solution. Let me know your thoughts @fortunatomaldonado

**Comment by fortunatomaldonado** [comment]
Hey @gregory-bretall @jonathanmccann, adding # to dl.char.blacklist would be simpler, but then again we need to think about the clients who are already using a # in a filename and how this solution would affect them.

**Comment by jonathanmccann** [comment]
Ok, what about using `HTMLUtil.escapeURL` so that the pound sign is escaped?

**Comment by fortunatomaldonado** [comment]
I believe it already does that. The # gets turned into %23 in the URL if I'm not mistaken.

**Comment by jonathanmccann** [comment]
The URL itself is escaped but I'm talking about at the spot where you made your current fix. Something like:

https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/servlet/ServletResponseUtil.java#L660

We could change the logic to also test if the file name has `#` in it or other reserved characters for URLs that we allow within file names. Once it's escaped, the alert pop up no longer appears.

**Comment by fortunatomaldonado** [comment]
Oh okay, I see. Yeah if it works that would be a lot clearer and cleaner.

**Comment by jonathanmccann** [comment]
Alright, go ahead and investigate that then and send it up if you think it's better.

**Comment by fortunatomaldonado** [comment]
Thank you for your help!

**Comment by fortunatomaldonado** [comment]
@jonathanmccann, I tried using the `URLCodec.encodeURL`, `HtmlUtil.escapeURL`, and even both on the file name but the script was still able to run. Were you able to get it to work?

**Comment by fortunatomaldonado** [comment]
Resent here: https://github.com/jonathanmccann/liferay-portal/pull/1644

**Pull request closed without merging**
