### PR TITLE
LPS-57957 Update liferay workflow definition xsd to correctly validat…

### PR DESCRIPTION
**Pull request by SamZiemer**
…e scripted assignemnt.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Sam,

Why are you just updating liferay-workflow-definition_6_2_0.xsd instead of 7_0_0 as well? Seems like the same code is in both places.

**Comment by SamZiemer** [comment]
I have updated the 7.0.0 workflow as well. 6.1.0 and 6.0.0 workflows do not have scripted assignments so they do not need to be updated.

**Comment by jonathanmccann** [comment]
I went ahead and squashed the commits. Thanks for making the changes.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/727

**Pull request closed without merging**
