### PR TITLE
[TECHNICAL-SUPPORT] LPS-72295

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman 

This pull relates to: https://github.com/jonathanmccann/liferay-portal-ee/pull/259

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by mbowerman** [comment]
@jonathanmccann @SamZiemer The test failure appears to be caused by https://github.com/brianchandotcom/liferay-portal/pull/48774

**Comment by SamZiemer** [comment]
Thanks for checking into that @mbowerman

**Comment by mbowerman** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
https://github.com/migue/liferay-portal/pull/980

**Pull request closed without merging**
