### PR TITLE
LPS-61372

### PR DESCRIPTION
**Pull request by mbowerman**
Add hasStagedVersion method to calendars to prevent user from modifying staged calendar on live site

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by mbowerman** [comment]
I ran the source formatter and re-pushed.

**Comment by mbowerman** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Please separate out the fix and the autogenerated code into different commits.

**Pull request closed without merging**
