### PR TITLE
[TS] LPS-102621

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-102621

Hi @jonathanmccann ,

Can you help me review this pr?

The root issue seems to be that DLAppService does not provide a fetch method for retrieving a fileEntry. 

This is problematic when a fileEntry needs to be retrieved within a FreeMarker template. Since FreeMarker templates do not allow for exceptions, there's no way to handle exceptions within the template itself.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
I think the change is fine. We will need to log a message when catching the exception though. The other part I'm wondering about is if you would want to narrow the scope of the caught exception. There is another fetch method in the class that does something similar but narrows in specifically on the NoSuchFileEntryException - https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppServiceImpl.java#L3272-L3291

Let me know what you think.

**Comment by jonathanmccann** [comment]
Closing per our discussion.

**Comment by ericyanLr** [comment]
revised pr as discussed and resent to Adolfo: https://github.com/adolfopa/liferay-portal/pull/1104

**Pull request closed without merging**
