### PR TITLE
[TECHNICAL-SUPPORT] LPS-68877

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@gregory-bretall Are "Asignee" and "AsigneeToMe" in

```[a-zA-Z]{4}update(Asignee|AsigneeToMe)```

spelled correctly? Also, should "AsigneeToMe" be "AssignedToMe"?

**Comment by gregory-bretall** [comment]
Those spellings, while generally incorrect, are consistent with the names of those elements as they are rendered on the page.  The misspellings would need to be corrected in the originating jsp to be fixed.

**Comment by jonathanmccann** [comment]
Thanks for taking a look. I'll leave it alone for right now to avoid breaking something, but if you have some time it might be good to refactor that so the naming is consistent.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/1699

**Pull request closed without merging**
