### PR TITLE
LPS-74160

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Did you test LPS-67463 to confirm that is still fixed? Also, if we're reverting LPS-71933, then shouldn't we provide a different fix for it or at least reopen the LPS?

**Comment by mbowerman** [comment]
I did not test LPS-67463 explicitly using the exact steps they provided, but I did log in as test test after enabling LDAP export, which I believed was enough to verify that the issue was still fixed.

I don't know what to do about LPS-71933, because it seems like there is no way to fix that LPS while also ensuring that the database and LDAP are matched with each other as closely as possible. As I understood it though, the LPS is just a performance improvement. I would think that it should be the expected behavior that a database transaction would fail if the corresponding LDAP export fails. Otherwise, there will be inconsistencies between the database and LDAP, which at least leads to this issue, and possibly several others that have not been discovered yet.

**Comment by jonathanmccann** [comment]
Closing since we don't want to reintroduce LPS-71933. @holatuwol will speak to you about this fix.

**Pull request closed without merging**
