### PR TITLE
LPS-68680

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @BryanEngler,

Is there a reason you changed from a Set to a HashSet? Curious if this has any affect on the display since now they are unordered.

**Comment by BryanEngler** [comment]
it was already a hashset before my SF. thats what SetUtil.fromList() returns: https://github.com/jonathanmccann/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/SetUtil.java#L214
it seemed to return consistently on the few tests i did with it as a hashset, and i figured the order wasnt all that big of a deal, but they were small tests and in a more complex env we might see some inconsistency so instead of leaving it to chance i updated the pr and it now uses a TreeSet which will use String.compareTo() to order the elements alphabetically. if you have any questions let me know

**Comment by jonathanmccann** [comment]
Thanks @BryanEngler for taking a look and updating the pull.

@gregory-bretall please combine your similar commits. I went ahead and squashed them together for you. For the future, separate your commits by the logic they are performing. Import statements are necessary for the first commit to compile, so they should all be included together. Likewise, you introduced the source formatting issue in the first commit, so simply fix it there. This helps clean the commit history clean and makes it simpler to review.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Pei-Jung for further review: https://github.com/pei-jung/liferay-portal/pull/142

**Pull request closed without merging**
