### PR TITLE
[TECHNICAL-SUPPORT] LPS-68710

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SGM3

### CODE REVIEW

**Comment by jonathanmccann** [comment]
I'm curious about https://github.com/jonathanmccann/liferay-portal/pull/1139/commits/92aaa27a47470bc080701b4a999ee66e974f547a

What do you mean by continuously updating an article? How do you reproduce that bug?

Also, adding a suggestion the first time to a child article results in the success message showing, but every subsequent time it is broken. Do you know why it works the first time through but not the others?

**Comment by SGM3** [comment]
A scenario on the current master in liferay-portal to reproduce the bug, if
you add 4 or 5 suggestions to any KB Article,
the URL itself exceeds 2000 characters and tends to fail, redirects the
user to the base KB page, displaying the available
parent KB articles.

Also, with my build, it seems to be working fine. I'll make a *.avi file
with CamStudio (need to configure it so it doesn't create a 1G files).

Best Regards,
Shanon Mathai

**Comment by jonathanmccann** [comment]
That's fine, I just needed some steps to see it reproduced locally.

Do you have any thoughts to my second question about why it works when adding the first suggestion but not afterwards?

**Comment by SGM3** [comment]
I have just tried a fresh clean build of my branch into a clean bundle (all work, temp, data and osgi/state removed), re-based with the latest master as of this morning.

I am unable to recreate the the issue you're seeing. The Child and Parent KB Articles do display the success message every time I hit submit for with a suggestion. If adding a suggestion to the child KB article works the first time, but the second (or third) time redirects you to the page listing all the parent KB articles, sounds like you do not have my change to "BaseKBPortlet.java" (my second commit). The change set in this PR does contain the change [BaseKBPortlet.java](https://github.com/jonathanmccann/liferay-portal/blob/92aaa27a47470bc080701b4a999ee66e974f547a/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/portlet/BaseKBPortlet.java)

**Comment by jonathanmccann** [comment]
I'm sorry, that behavior is what I was seeing without your changes. So Master, with no fix, adding a suggestion works properly, display the correct message, and you are not redirected to the wrong page. I'm wondering why it works currently on Master the first time through but not subsequent times.

Your fix does work, but I'm curious to see if it's the correct fix since it seems things are working properly at least during the first run through.

**Comment by SGM3** [comment]
In master, try adding 5 suggestions to any KB Article. This should cause the URL to get to long and redirecting you to the base page. I would have to check the latest master.

**Comment by jonathanmccann** [comment]
I understand that. What I'm talking about is something different.

In Master, adding a suggestion to a child article the first time results in the success message being displayed correctly and the user is not redirect. What I want you to investigate is why this works the first time and then why it is failing on subsequence suggestions. I want to make sure that we are making the correct fix. It seems strange to me that all of this redirection logic is necessary because when adding a suggestion the first time, everything works fine. So it seems that something is happening afterwards to cause this situation. Instead of focusing on the redirects, the fix might be figuring out what happens after adding the first suggest to cause subsequent tries to not work as expected.

In the end, your fix might be the correct one, but I want to understand more fully the issue before making these changes, since it does work properly the first time.

**Comment by SGM3** [comment]
The behavior described is dependent on the navigation to the Child KB article.

I only get that behavior in master when navigating to the child KB by clicking the subtext in the parent KB, then clicking the child KB article. The first request succeeds and intermittently fails on requests after, sometimes on the next request, sometimes on the a few after. The parent article never seems to submit the suggestion with a success message, it always redirects to the base page.

My analysis of the issue shows that there were roughly two issues. 

The first was the child KB article seemed to place a (relative path) URL as the redirect which affected the back button functionality and what page is loaded on submit. This is dependent on the page used to access the child KB. Setting a full path URL seems to all unify the behavior and correct the functionality for the most part. Back button functionality was still broken, but you were still able to submit suggestions, until the URL became too long. This was covered in the first commit

The second issue is what the I had mentioned last. The portlet was appending the current URL (with the current redirect parameter) to the new URL parameter. The back button relied on the embedded redirect parameter it seemed and the URL itself was getting too long. This was covered in the second commit.

**Comment by jonathanmccann** [comment]
Thank you for the detailed explanation.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3608

**Pull request closed without merging**
