### PR TITLE
[TECHNICAL-SUPPORT] LPS-64687

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @ericyanLr

From Eric:

>After looking through other portlets, such as Web Content Display and Asset Publisher, it looked like the options that involve a pop up generally hide the default success message after the action completes.

>This fix basically hides the default success message when modifying a list within the DDLDisplayPortlet.
If you would like to see some examples, you can search "hideDefaultSuccessMessage" in master.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @ericyanLr @SamZiemer,

When I test out the issue, now I receive no success message whatsoever. Reading over the ticket it seems this is not achieve the expected result:

Expected Result:
Success message is given to the user in the DDL Display portlet.

Am I testing this wrong or is it behaving as you expected?

**Comment by ericyanLr** [comment]
Hey @jonathanmccann @SamZiemer ,

You are correct, currently the changes would hide the default success message when modifying a list within the DDLDisplayPortlet.  No success message would be displayed whatsoever.

***Questions***
Do we need to make sure the Expected Result stated on the ticket is met?
Should I first ask the reporter if hiding the default success message could be the expected behavior? 

***Explanation for the Fix***
Looking at other portlets that use pop-ups to add/modify entries, I found that they generally do not display a default success message after the action completes.  A few of the portlets that I found that exhibited this behavior were Web Content Display, Asset Publisher, and Polls.

The changes for this fix are based on the Web Content Display portlet. 
The use of the parameter "hideDefaultSuccessMessage" can be found in 
* com/liferay/journal/content/web/display/context/JournalContentDisplayContext.java

```
public String getURLEdit() {
	...

	PortletURL portletURL = latestArticleAssetRenderer.getURLEdit(
		(LiferayPortletRequest)_portletRequest, null,
		LiferayWindowState.POP_UP, redirectURL);

	portletURL.setParameter(
		"hideDefaultSuccessMessage", Boolean.TRUE.toString());
	portletURL.setParameter("showHeader", Boolean.FALSE.toString());

return portletURL.toString();
```

Thanks!

**Comment by jonathanmccann** [comment]
Hey @ericyanLr,

Thanks for the information. I went ahead and tested Web Content and Polls and editing the asset does not result in a success message, like you said. Also, please see below for answers to your questions.

1. Do we need to make sure the Expected Result stated on the ticket is met?

Not necessarily, especially in this case since we're following the pattern set forth by other portlets. However, you will need to explain the behavior and why you fixed it in this way on the LPS so that when QA tests the fix, they do not fail it since it doesn't behave as the description states it should.

2. Should I first ask the reporter if hiding the default success message could be the expected behavior?

Generally, the expected outcome will fit in line with the rest of the portal. In this case, their way of how the portal should work does not line up with the rest of the portlets' pattern.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/1366

**Comment by ericyanLr** [comment]
Thanks @jonathanmccann !

I will remember to explain the behavior and the fix when proposing the solution.

**Pull request closed without merging**
