### PR TITLE
[TECHNICAL-SUPPORT] LPS-71181

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @JonathanAichler

Notes from Jonathan:

> This pull request is for the part of my fix that is independent of anything else. I will send the other pull request that is dependent on these changes.
> 
> https://issues.liferay.com/browse/LPS-71181

Relates to https://github.com/jonathanmccann/com-liferay-journal/pull/13

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
the error that closed this seems to be a problem with the PR tester. Minhchau mentioned it here: https://github.com/brianchandotcom/liferay-portal/pull/48025

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/855

**Comment by jonathanmccann** [comment]
@JonathanAichler Be sure to include the LPS number in your commit messages.

**Pull request closed without merging**
