### PR TITLE
LPS-62457

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman @BryanEngler 

A couple of things:

1. The Javascript does not compile correctly (missing parentheses). Please be sure to test your changes before submitting them. This is why the Calendar wasn't displaying properly for me.

2. When clicking on the event and choosing the user's attendance via the pop up instead of going through "View Details", it will decline all of the repeated events. Is this the functionality that you want?

3. If a secondary user chooses to attend a specific event in a line of repeated events and then the creator of the event deletes all occurrences of the event, the secondary user still has the single event on their calendar. I don't think the approach of deleting the event and adding a new one will work in the long term because of behavior such as this. I assume if the creator of the repeating event made changes to it, it would not propagate to the single event the secondary user has.

Please let me know if you have any questions.

**Comment by mbowerman** [comment]
Hey Jonathan, regarding your third point, I created [LPS-62735](https://issues.liferay.com/browse/LPS-62735) to deal with issues like that. It's part of a problem that already exists in the portal, rather than a new problem introduced by my fix, which is why I thought it would be OK to go ahead and submit this fix anyway.

**Comment by jonathanmccann** [comment]
Hey Michael,

Thanks for that. In that case, wouldn't the fix for LPS-62735 completely change the logic you're using here? I feel like if we fix that issue, we can't be creating single events that should be in a sequence of repeating events.

**Comment by mbowerman** [comment]
I don't think it would completely change it. I'm envisioning that the fix to LPS-62735 would add a new column to the calendar booking table (perhaps called "originalRecurringBookingId") that would point to the recurring event that a modified instance spawned from. In that case, the only modification that would have to be made to my fix would be to make sure that the originalRecurringBookingId points to the original recurring event when we add the new event.

**Pull request closed without merging**
