### PR TITLE
LPS-62142 Fix XSS vulnerability

### PR DESCRIPTION
**Pull request by dustinryerson**

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Dustin,

Should we be using HtmlUtil.escapeURL instead of just .escape?

Thanks.

**Comment by dustinryerson** [comment]
Good question. Let me look into that and test it and I'll get back to you.

**Comment by dustinryerson** [comment]
Hey Jonathan,

I think the current solution is the right one. They both fix the XSS issue, and the only difference I could find in function was the following (see screenshots below).

1. **Using HtmlUtil.escape():**
image

2. **Using HtmlUtil.escapeURL();**
image

Do you agree? I can do further testing if necessary.

Thanks!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Tomáš for further review: https://github.com/topolik/liferay-portal/pull/260

**Comment by arbetts** [comment]
@dustinryerson @jonathanmccann 

not sure if you two already talked about this but we use escapeURL when the url is going to be used in the query string of another url (like redirect). the more general escape is designed for security; to remove potential scripts or disallowed protocols from urls so that we do not introduce XSS issues.

**Pull request closed without merging**
