### PR TITLE
LPS-66690

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Sorry, made a small change to the commit

**Comment by mbowerman** [comment]
Actually, there's still a significant problem with this fix. Even if the default locale gets changed, the old default locale will still persist throughout the database in things like DDMStructures, DDMTemplates, etc. In order to fully fix this issue, I would probably need to make it so that any time the default locale changes AND the old default locale is no longer enabled, we check every DDMStructure, DDMTemplate, User, Layout, etc. to see if they have references to the old default locale, and update those references to point to the new default locale. But this would take me a very long time to do, and I'm not even sure where I would put such a method.

**Comment by jonathanmccann** [comment]
I would bring the issue up the engineering and let them decide the best solution, since this could potentially be a very large change. Let me know if there's anything I can do to help.

**Pull request closed without merging**
