### PR TITLE
LPS-75045 - Reindex affected users when parent organization changes

### PR DESCRIPTION
**Pull request by ericyanLr**
Notes from @wanderlast:

> ### Links:
> LPS: https://issues.liferay.com/browse/LPS-75045
> Related LPP: https://issues.liferay.com/browse/LPP-27284
> 
> Hi!
> 
> ## _Synopsis_
> The issue is that when a parent organization is added or removed from an organization the permissions of the organization members are not updated. The problem can be 'fixed' currently by restarting the server, or in Liferay's control panel under Server Administration -> "Clear content cached across the cluster".
> 
> The root cause of the bug is that users are not reindexed when organizations are updated, meaning that adding or removing a parent organization does not update the user's organizational permissions as it should.
> 
> ## _Related History_
> This problem has cropped up multiple times with other, similar areas of the code. Specifically [LPS-68988](https://issues.liferay.com/browse/LPS-68988) fixed it with regards to UserLocalServiceImpl functions. This fix is near identical to the fix I applied--calling a reindex whenever a change is made.
> 
> Model listeners were used to handle cache errors in a similar manner to this fix in [LPS-75016](https://issues.liferay.com/browse/LPS-75016), although reindexing is not performed in these listeners--only the cache clear.
> 
> ## _Fix_
> The fix itself that was used is a model listener, per Minchau's suggestion. The model listener listens to any updates to the organization and performs a reindex if the parent organization's ID has changed. Separate threads are used to prevent the portal from hanging in the case of a large organization reindex.
> 
> Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by ericyanLr** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
The test failure is relevant. Please run the source formatter.

**Comment by jonathanmccann** [comment]
ci:stop

**Pull request closed without merging**
