### PR TITLE
LPS-88701 Updated portlet anchoring

### PR DESCRIPTION
**Pull request by ajsampang67**
**Relevant tickets:**
https://issues.liferay.com/browse/LPS-88701
https://issues.liferay.com/browse/LPS-85800

**Explanation:**
- Reverted LPS-85800; the removal of this block of code resulted in the bug described in LPS-88701
- Changed `'... = p_' + portletId` to `... = window.location.hash`, this fixes the bug described in LPS-85800
- Changed `window.location.hash = ...` to `window.location.href = ...`, this fixes the anchoring for Chrome browser

### CODE REVIEW

**Comment by ajsampang67** [comment]
ci:test:sf

**Comment by ajsampang67** [comment]
ci:test:relevant

**Comment by ajsampang67** [comment]
Test failure seems unrelated; was unable to reproduce the unique failed test.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/2005

**Pull request closed without merging**
