### PR TITLE
LPS-79071

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @joshuacords

From Josh:
https://issues.liferay.com/browse/LPS-79071
https://issues.liferay.com/browse/LPP-29463

BufferOverflowException will be thrown if https://github.com/joshuacords/liferay-portal/blob/fa4d4fcbbf37fddccc03cb7d90016e74ee250c5e/portal-kernel/src/com/liferay/portal/kernel/io/OutputStreamWriter.java#L119 called and the _inputCharBuffer's limit was set to 1. Under normal circumstances this won't happen, however the use of the flip method which can set the limit to 1 here: https://github.com/joshuacords/liferay-portal/blob/fa4d4fcbbf37fddccc03cb7d90016e74ee250c5e/portal-kernel/src/com/liferay/portal/kernel/io/OutputStreamWriter.java#L150 relies on the compact() call to reset the limit. However, the next call to the _encodeLoop method can throw an Exception which allows the compact() method to never be called.

I've added a finally to clear the _inputCharBuffer to reset its position and limit in case the exception is thrown.

### CODE REVIEW

**Comment by ChrisKian** [comment]
CI seems kind of broken, see test failure: https://github.com/ChrisKian/liferay-portal/pull/33#issuecomment-375527055

I doubt Josh's changes would have caused any real failures anyways.

**Comment by jonathanmccann** [comment]
@joshuacords Do we still need to clear if the compact was run successfully?

**Comment by joshuacords** [comment]
@jonathanmccann, no we don't. So the options would be either put the clear() in a catch that also throws the IOException or potentially just move the compact method from the try to the finally.

**Comment by ChrisKian** [comment]
@joshuacords if we throw an error at _encodeLoop, then have compact in the finally, would compact be guaranteed to work, or would the charBuffer be in a state which could prevent the compact from functioning properly?

If that's the case, it might be best to replace the "finally" with a catch, then have it throw the error after it clears the charBuffer.  This way we aren't swallowing any exceptions, but rather just clearing the charBuffer before proceeding.

CC @jonathanmccann (sorry for not catching this)

**Comment by joshuacords** [comment]
@jonathanmccann  @ChrisKian 

I believe there is a case where compact() will not work if the _encodeLoop() throws an exception. 
The [compact method](https://docs.oracle.com/javase/7/docs/api/java/nio/CharBuffer.html#compact()) can set the position to 1 or 2 which would overflow the inputBuffer if its next use was a  write(int c) call.
Because of this I think compact() should only be used if the _encodeLoop was completed successfully. And clear() should be called if an Exception is thrown.
I believe this code would achieve the desired behavior:

try {
	_encodeLoop(_inputCharBuffer, endOfInput);
	_inputCharBuffer.compact();
} 
catch (IOException e) {
	_inputCharBuffer.clear();
	throw e;
}

**Comment by jonathanmccann** [comment]
Thanks for taking a look. Please send me an updated pull and I can forward it along.

**Comment by joshuacords** [comment]
Updated here: https://github.com/jonathanmccann/liferay-portal/pull/1583

**Pull request closed without merging**
