### PR TITLE
Lps 79021 pr

### PR DESCRIPTION
**Pull request by gregory-bretall**
https://issues.liferay.com/browse/LPS-78396

https://github.com/gregory-bretall/liferay-portal/pull/48/

Explanation of changes: https://github.com/gregory-bretall/liferay-portal/pull/48#issue-176832138

Ci Test Results https://github.com/gregory-bretall/liferay-portal/pull/48#issuecomment-375409162

@brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
When verifying the fix, it seems that the "Description" is not shown in the Control Panel version of the portlet and there does not seem to be configuration options to allow this like there is when adding the portlet to the page. Do you know if there is a way to achieve this? If not, it might be better to show the description by default since I assume that's what the client is expecting.

Also, the steps to reproduce on the LPS don't mention the fact that you need to change the configuration in order to display the description.

**Comment by gregory-bretall** [comment]
@brianikim Could you take a look at Jonathan's comment when you have a chance?

**Comment by jonathanmccann** [comment]
@brianikim The property you mentioned worked for the Control Panel view. Please update the LPS to make a note of changing the configuration on the portlet as well as adding the portal property in order to reproduce the issue.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/4278

**Pull request closed without merging**
