### PR TITLE
[TECHNICAL-SUPPORT] LPS-70935

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @NolanChan 

Notes from Nolan:
> I've uploaded two screenshots on LPS-70935 about how the Version History looks in 62x, and how the proposed Master change will look. This code change adds the author and date fields underneath the change log field in the Versions sidebar info

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
It seems the semantic versioning issue happens without this fix.

**Pull request closed without merging**
