### PR TITLE
[Community Contribution] LPS-98452

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-98452

Forwarded from https://github.com/liferay/liferay-portal/pull/3523.

The log message is useful, so it makes for it to be visible by default. Current change is to bump the log level of the message to INFO and to enable INFO logging by default for the logger.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Reviewed and sent to Preston for further review: https://github.com/Preston-Crary/liferay-portal/pull/840

**Pull request closed without merging**
