### PR TITLE
LPS-88551

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPP-32429
https://issues.liferay.com/browse/LPS-88551

From @wanderlast:

> This is very similar to what was submitted to you previously, but with additions made by @ealonso as well as a test fix made by myself to address the issue brought up by QA here: https://github.com/brianchandotcom/liferay-portal/pull/66720
> 
> Please let me know if you have any questions or concerns. Thanks!

Here's a diff of the latest two commits, for easy reading: https://github.com/jonathanmccann/liferay-portal/compare/c44a0525aa9065717ce9572626668e565688ad0e...bd2a6c0048d01ecc33fe9168aa724eab3ff00348

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/66781

**Pull request closed without merging**
