### PR TITLE
LPS-53643 Unable to import site page LAR file due to dependencies from a...

### PR DESCRIPTION
**Pull request by ChrisKian**
...n unrelated site

Updated https://github.com/jonathanmccann/liferay-portal/pull/603 based off comments from https://github.com/juliocamarero/liferay-portal/pull/3249#issuecomment-75027686

Description:
Given that we generate a LAR file from one site which contains a public page with an Asset Publisher portlet (Site A), and a different site on the same environment contains a structure which is linked to a template (Site B), importing the LAR file of the Public Pages (generated from Site A) into a new bundle will result in an error indicating that the Portal is unable to import the LAR file due to a missing the structure dependency from the other site (Site B).
The file Public_Pages-201502032216.lar cannot be imported.
There are missing references that could not be found in the current site. Please import the following elements first:
Dynamic Data Mapping Structure: Structure on Site B(Referenced by a Portlet: Asset Publisher)
This should not be the case, as the Asset Publisher's scope indicates that it will only gathering information from Site A, and not Site B. Also, we are only importing Site A's content.
Steps to reproduce:
On server 1 :
1. Create 2 blank sites called "Site A" and "Site B"
2. On site B, create a new web content structure called "Structure on site B"
3. On site B, create a template for the structure.
4. On site A, add a page, then add an Asset Publisher to that page.
5. Edit the Asset Publisher configuration, change any settings and save.
6. Export the pages of site A, keeping all options to their default values.
On server 2 :
7. Create a new blank site
8. Import the lar file exported form server 1 to that site
Expected Result:
Nothing in the Asset Publisher's configuration is referencing the "Structure on site B", the lar file should import without issues.
Actual Results:
the import fails. The error message states that the lar file is missing the referenced structure "Structure on site B" from the portlet Asset Publisher
Branch:
commit f6b3d31
Reproduced
Master:
commit 188d32a
Reproduced

Note for QA: When attempting to test the pull request, one of your tests will likely be to import the exported LAR file. LPS-53646 will block you from completely importing the LAR, however you can see we no longer have missing-references when initially adding the file for import (see the attachments for the parent LPP as well as for LPS-53646).

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Chris,

Does this include a message for the user to explain why the import/export isn't completing successfully? https://github.com/juliocamarero/liferay-portal/pull/3249#issuecomment-75234035

**Comment by ChrisKian** [comment]
Hey Jonathan,

  It treats a missing parent/ancestor reference like any other.  Here is a screenshot of an example.  I exported the child of "Blank Site A", deleted "Blank Site A" and its child, then attempted to import the LAR.  @juliocamarero, is this acceptable?
testingmissingparentresult

**Comment by jonathanmccann** [comment]
Thanks for the screen shot. Also, be sure to include any source formatting I do if you need to resend a pull request. I have made some changes this time as well, let me know if you have any questions.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3254

**Pull request closed without merging**
