### PR TITLE
LPS-67303 Add companyId to CompanyThreadLocal for each company to ens…

### PR DESCRIPTION
**Pull request by SamZiemer**
…ure getAvailableLocales gets the correct list of locales

This fix addresses the issues noted by Alberto here: https://github.com/migue/liferay-portal-ee/pull/38#issuecomment-237837043

Getting the company ID and setting it via CompanyThreadLocale for each company present will allow LanguageUtil.getAvailableLocales to receive the correct locales for the company.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
I believe you can simply use CompanyLocalService.getCompanies() instead of crafting your own SQL. Also, I'm not sure if you need to reset the CompanyThreadLocal to whatever it was set before this method or if it gets reset automatically. Let me know if you have any questions.

**Comment by achaparro** [comment]
Hey @jonathanmccann,

Regarding your comments:
1- We have to use SQL to get the company here because the code is part of the core (where the company service is declared) and, if the Company table changes, the upgrade won't work in the future because the database won't be syncronized in that point with that hypothetical new company service.
2- The other point is true, we should set the original companyThreadLocal value in the finally clause.

Let me know if you any question.

Cheers.

cc @SamZiemer

**Comment by SamZiemer** [comment]
Hi @achaparro,

I've updated the fix with a finally clause setting the companyId back to its original value.

https://github.com/jonathanmccann/liferay-portal/pull/1090

**Pull request closed without merging**
