### PR TITLE
LPS-60013

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@BryanEngler @mbowerman 

I just had a couple of questions:

1. Don't "_wikiPageLocalService.fetchWikiPage(classPK)" and "_wikiPageLocalService.getPage(classPK)" return the same thing? If they do, then if the page is null, then it will always throw the NoSuchPageException making this logic very convoluted.

2. Why are we calling the same exact code when we catch the exception and when the type is latest? Isn't there a better way to restructure this method so that we don't repeat ourselves?

To me, it seems we need to do something like this:

```
@Override
public AssetRenderer<WikiPage> getAssetRenderer(long classPK, int type)
	throws PortalException {

	WikiPage page = _wikiPageLocalService.fetchWikiPage(classPK);

	if (page == null) {
		if ((type == TYPE_LATEST_APPROVED) || type == TYPE_LATEST) {
			WikiPageResource pageResource =
				_wikiPageResourceLocalService.getPageResource(classPK);

			page = _wikiPageLocalService.getPage(
				pageResource.getNodeId(), pageResource.getTitle(),
				null);
		}
		else {
			throw new IllegalArgumentException(
				"Unknown asset renderer type " + type);
		}
	}

	WikiPageAssetRenderer wikiPageAssetRenderer = new WikiPageAssetRenderer(
		page);

	wikiPageAssetRenderer.setAssetRendererType(type);
	wikiPageAssetRenderer.setServletContext(_servletContext);

	return wikiPageAssetRenderer;
}
```

Let me know what you guys think and if I misunderstood something in the fix.

**Comment by jonathanmccann** [comment]
Actually, in that scenario, type is no longer even necessary so it could be reduced to just:

```
@Override
public AssetRenderer<WikiPage> getAssetRenderer(long classPK, int type)
    throws PortalException {

    WikiPage page = _wikiPageLocalService.fetchWikiPage(classPK);

    if (page == null) {
        WikiPageResource pageResource =
            _wikiPageResourceLocalService.getPageResource(classPK);

        page = _wikiPageLocalService.getPage(
            pageResource.getNodeId(), pageResource.getTitle(),
            null);
    }

    WikiPageAssetRenderer wikiPageAssetRenderer = new WikiPageAssetRenderer(
        page);

    wikiPageAssetRenderer.setAssetRendererType(type);
    wikiPageAssetRenderer.setServletContext(_servletContext);

    return wikiPageAssetRenderer;
}
```

**Comment by mbowerman** [comment]
1. fetchWikiPage(classPK) actually works differently from getPage(classPK). fetchWikiPage(classPK) returns a WikiPage whose _pageId field matches classPK, whereas getPage(classPK) returns a WikiPage whose _resourcePrimKey field matches classPK. 

   The reason we call both methods is because we don't actually know whether the method that called getAssetRenderer passed in a pageId for the classPK argument, or if it passed in a resourcePrimKey instead.

   Additionally, getPage(classPK) will only ever return a page that has been approved.

2. If we pass in the TYPE_LATEST_APPROVED parameter, then we want to first check if there is an approved version. If there is, then we MUST return that version. If there is not an approved version, then we want to return the unapproved version (or at least, this is how I understood @sergiogonzalez's comments on [my previous PR] (https://github.com/sergiogonzalez/liferay-portal/pull/2699)). Therefore, I don't think we should simply make the type parameter irrelevant.

   It is possible to have two WikiPages with the same resourcePrimKey (see screenshot below). This seems to happen whenever a page has been edited. The edited page receives a new pageId, but keeps the same resourcePrimKey as the original. 

   Therefore, if the classPK argument that has been passed in corresponds to the resourcePrimKey, we need to call getPage(classPK) first if we are using TYPE_LATEST_APPROVED. This will ensure that if there are multiple pages in the database with the same resourcePrimKey, and only one is approved, we will return the approved version.

two wikipages with the same resourceprimkey

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/2727

**Pull request closed without merging**
