### PR TITLE
[TECHNICAL-SUPPORT] LPS-70357

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mbowerman The logic seems to be changed now. Instead of overwriting the ```assetCategoryIds```, we're now appending to them. Could you explain this logic a bit?

**Comment by mbowerman** [comment]
@jonathanmccann,

First of all, the code was poorly written before. This line:

`assetCategoryIds = GetterUtil.getLongValues(queryValues);`

should have been this

`return GetterUtil.getLongValues(queryValues);`

But instead we continued looping, even though there's no need to.

It's guaranteed that there will only be only be one queryValues object for which queryContains=true AND queryAndOperator=true AND queryName="assetCategories". That's why we "overwrote" it before, because we knew we'd only encounter one such queryValues object. You can prove this to yourself by trying to add multiple "Contains All of the following Categories" filters in the Asset Publisher's Configuration UI - the UI won't let you, it'll display an error saying you need to only have one "Contains All of the following Categories" filter.

What my fix does is it takes into account that we might also want to add a value from a "Contains Any of the following Categories" query to the list of required categories. In the case that you only have one category listed in a "Contains Any of the following Categories" filter, logically, you know that that category is required. This is the behavior in 6.1, but for some reason was changed in 6.2.

So now, instead of simply returning the array of categories in a "Contains All of the following Categories" filter, what we do now is we append the array of categories in a "Contains All of the following Categories" filter to an array of "Contains Any of the following Categories filter" that only has one category listed.

If there is a "Contains Any of the following Categories filter", but it has more than one category, then of course it wouldn't be appended to the list of required categories, and we'd just return the array of categories from the "Contains All of the following Categories" filter (if such a filter exists).

Let me know whether this explanation makes sense to you.

**Comment by jonathanmccann** [comment]
Got it, thank you for the detailed explanation, I appreciate it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/779

**Pull request closed without merging**
