### PR TITLE
LPS-98828

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-98828
https://github.com/fortunatomaldonado/liferay-portal/pull/8

Reviewed fix from @ricardocousolr and looks good. The validation checks both original and repeatable fields when necessary. Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
This looks fine to me as well. Please check the source formatting error and once that is resolved forward the fix on to https://github.com/jeyvison

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Pull request closed without merging**
