### PR TITLE
LPS-77038

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-77038

Resend and rebase of https://github.com/ealonso/liferay-portal/pull/1350 with the null check (added into final commit).  Let me know if you have any questions

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by jonathanmccann** [comment]
It looks like Eudaldo edited his comment and wants the new method more localized rather than in PortalImpl:

https://github.com/ealonso/liferay-portal/pull/1350#issuecomment-358235798

Could you please take a look?

**Comment by ChrisKian** [comment]
Got it, I'll get the new fix going.  Thanks!

**Comment by ChrisKian** [comment]
Resent, see https://github.com/jonathanmccann/liferay-portal/pull/1506

**Pull request closed without merging**
