### PR TITLE
LPS-57822 Application display templates active permissions are not ch…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…ecked when defineding permissions of Site/Organization Roles

See, edit_role_permissions_resource.jsp

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Preston,

In "edit_role_permission_resource.jsp", we're only setting the scope to "SCOPE_GROUP" if the role type is regular and if groups is not empty. Is there a reason your code does the opposite?

**Comment by Preston-Crary** [comment]
Sorry, good catch.  I should really never send pulls after lunch.

**Comment by jonathanmccann** [comment]
Thanks for updating the pull. In the case where it is a regular role, why does "edit_role_permissions_resource" search for groups based on role permissions instead of just checking the number of groupIds?

**Comment by jonathanmccann** [comment]
Preston, did you see my question above?

**Comment by jonathanmccann** [comment]
Closing per discussion.

**Pull request closed without merging**
