### PR TITLE
LPS-92135

### PR DESCRIPTION
**Pull request by brianikim**
Hello @jonathanmccann ,

https://issues.liferay.com/browse/LPS-92135

Currently, the behavior of search results for a web content with a parent folder and the behavior of accessing web content with a parent folder are both inconsistent.

The more detailed information can be found in the LPS ticket as the inconsistency is extensive.

I have resolved the inconsistency as guided by the PTR for LPS-92135.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
This should go through both WCM and Search teams.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @jonathanmccann ,

The second test failure looks like a ci issue.

As for the results of the first one, the tests do not look related.


Sincerely,
Brian Kim

**Comment by jonathanmccann** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1788/commits/1983014da808f61bf736fae18eb709a61c998c88 - This seems a little strange to me to be passing around `null` (https://github.com/jonathanmccann/liferay-portal/pull/1788/commits/1983014da808f61bf736fae18eb709a61c998c88#diff-51b0fa7e3d7b2046879f598d8e2a28d0R189) and not using `Validator.isNotNull` (https://github.com/jonathanmccann/liferay-portal/pull/1788/commits/1983014da808f61bf736fae18eb709a61c998c88#diff-51b0fa7e3d7b2046879f598d8e2a28d0R114). In the former, if you still want to return `null` then simply return `_folderTitleLookup.getFolderTitle(folderId)` because it's either returning a string or null.

https://github.com/jonathanmccann/liferay-portal/pull/1788/commits/7f26282fb317110cdabe44c48c6739197acd61aa - The logic added is almost a complete duplication of the previous methods. The previous ones should be updated to call the new methods passing in `VIEW` for the `actionId` to limit the amount of duplication.

Please resend and let me know if you have any questions.

**Pull request closed without merging**
