### PR TITLE
Lps 54965

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
these test failures show a gap in our testing because of the poor exception handling we had...

the errors show that this LPS change is rather important :)

**Comment by arbetts** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by holatuwol** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/338

**Pull request closed without merging**
