### PR TITLE
LPS-77796 Created a check to add the changeableDefaultLanguage to ava…

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
…ilableLocales

When the OSGi property "changeableDefaultLanguage" is active, it will allow the user to change the default language while creating a web content. When changing the default language, the new language is not stored in the availableLocales and its content will not be saved.

I created a check to detect when "changeableDefaultLanguage" is active and store the new language in availableLocales if it is not already there. This will then be able to store the content of the language.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Reviewed and sent to Rafael for further review: https://github.com/rafaprax/liferay-portal/pull/311

**Comment by jonathanmccann** [comment]
@fortunatomaldonado For the future, please send pulls through your mentor (Greg).

**Comment by fortunatomaldonado** [comment]
Okay will do, thank you!

**Pull request closed without merging**
