### PR TITLE
LPS-90129 remove HTML escape

### PR DESCRIPTION
**Pull request by ryannealeigh1**
https://issues.liferay.com/browse/LPS-90129

Resubmit of https://github.com/jonathanmccann/liferay-portal/pull/1772

Does not regress [LPS-71236](https://issues.liferay.com/browse/LPS-71236) based on my testing.

### CODE REVIEW

**Comment by ryannealeigh1** [comment]
ci:test:sf
ci:test:relevant

**Comment by ryannealeigh1** [comment]
ci:test:relevant

**Comment by ryannealeigh1** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jürgen for further review: https://github.com/jkappler/liferay-portal/pull/391

**Pull request closed without merging**
