### PR TITLE
[TECHNICAL-SUPPORT] LPS-72834

### PR DESCRIPTION
**Pull request by JoshuaStClair**
In [LPP-25693](https://issues.liferay.com/browse/LPP-25693), the client describes that the current error messages for remote staging, when a user is not present on the remote server, are too vague and provide no insight to the user without the help of the console. The only UI indicator of an error is the tiny exclamation mark by the "Go to Remote Live" button, which is easy to miss. Even so, this error only says "An unexpected error occurred." which isn't helpful for resolving the problem. 
In order to fix this, I added a SessionError message that appears at the top, which specifically describes this scenario displaying: "An error occurred while authenticating user {0} on the remote server." The exclamation mark will also be more specific in this case saying: "An error occurred while authenticating user."
While looking over the code, I noticed a lot of areas that could use refactoring. Particularly in view.jsp, the when/otherwise tags had redundant nested conditions that were always true given that it had already passed the outer condition. I simplified these conditions to make the code easier to follow and maintain.
Next, if I wanted to add Session Error messages where the exception was being thrown, I would need to add it to the scriptlets in the view.jsp file. Instead of building off of the bad code, I decided to move the try catch block, along with a lot of the other scriptlets, inside the StagingBarPortlet:render command to make it easier to maintain in the future. By moving some of the setAttribute calls into the render command, I also took out redundant attributes whose only difference was the namespace: "view.jsp-" before the keys. I modified the corresponding included jsp's that used those attributes. 
Also, just to note, the "Go to Remote Live" link doesn't actually work right now, per [LPS-72443](https://issues.liferay.com/browse/LPS-72443)

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Looks pretty good @JoshuaStClair. One concern I have is that in the Java we're now catching exceptions, logging the error, but then continuing on. Is this how the JSP behaves? I would assume the JSP would error out if it ran into an exception, but I'm not 100% sure.

**Comment by jonathanmccann** [comment]
@JoshuaStClair Have you had a chance to review my previous comment?

**Comment by JoshuaStClair** [comment]
Hi @jonathanmccann, I actually didn't get an email notification so I missed that comment. Sorry about that. 
In regards to your comment, I think you may be right that the JSP would error out if it ran into an exception. I wanted to keep the code as similar as possible during the migration but I found that we were not catching exceptions in the JSP. When I moved it into the render method, I was not able to throw the exceptions because I would no longer be overriding the super.render method signature. Thus I decided to log them and continue. But I guess to keep in line with the behavior of the JSP, I should log the error and return if we get exceptions.
I can also double check that that is the expected behavior when an uncaught exception is throw in the JSP but I'm pretty sure you're right.

**Comment by jonathanmccann** [comment]
It looks like we can handle it a few different ways:

Add a session error and return - https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/portlet/DDLPortlet.java#L140

Wrap the exception in a PortletException - https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/portal-workflow/portal-workflow-definition-link-web/src/main/java/com/liferay/portal/workflow/definition/link/web/internal/portlet/WorkflowDefinitionLinkPortlet.java#L76

Also, it seems that one of your catch blocks is not necessary - https://github.com/jonathanmccann/liferay-portal/pull/1348/commits/112508c2575409c6e7cea48141291b7c38524044#diff-61a5377d82a1e1e054ecf01791e791ddR158

Please take a look and refactor how the exceptions are utilized and resend this fix.

**Comment by JoshuaStClair** [comment]
Will do, I will make the changes and resubmit the PR. 
In regards to your last comment, that was actually a unique case. Intellij will say it's not necessary because the method signature for getGroup does not throw an exception. However, source formatter caught that case and said it's missing a catch block. Stepping into the implementation, we see that an exception is actually thrown by [ReflectionUtil](https://github.com/jonathanmccann/liferay-portal/blob/112508c2575409c6e7cea48141291b7c38524044/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L589). (I'm not entirely sure what that does though)

**Pull request closed without merging**
