### PR TITLE
LPS-57292

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Are the results always returned in reverse order? If so, could we simply set the summary for only the first search result? Also, there seem to be other places where the summary is set, does this fix need to be applied there as well?

**Comment by BryanEngler** [comment]
if youre just searching by the ID, then the order might be fairly consistent, i dont know for sure... but when you search by keywords in the title, it seemed like the order of the results became more random. basically you could get a hit for a past version of an article, but in the results we would still want to show the current title of the article as long as the keywords are in the current title. in general i couldnt really see a pattern but if you want me to look into that i could try to figure it out. to me i guess it just seemed safer to rely on the version than on the order of the results observed in a few simple tests where i didnt really see any consistency.

as far as "other places" goes, i saw in BaseSearchResultManager the logic is basically duplicated, so i guess it could be changed there although that code doesnt seem to get run since DefaultSearchResultManagerImpl inside of SearchResultManagerImpl overrides it. not really sure whats going on there... in all the other places ive seen it seems like the summary is being set for the first time so i dont think there needs to be any comparison of versions there.

**Comment by jonathanmccann** [comment]
I'm just worried about the potential overhead if we're searching through hundreds of versions of articles and wondered if there was a quicker way to get the correct summary. Do you think this is possible or is there another way to cut down on the overhead?

I think it might be good to make the same change in the Base, just for consistency sake.

**Comment by jonathanmccann** [comment]
Closing in favor of removing summary from "search_resources.jsp" as discussed.

**Pull request closed without merging**
