### PR TITLE
LPS-88551

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-88551

From @wanderlast:

> In 7.1 the user has the option to add a regular layout/page as a default display page to a web content structure. However, currently, the process fails in two different places which causes the display page setting to not save properly. The first was introduced in commit c2ddb3ed68aec3b08d7606394781f1b29459a507. This commit adds a logic check for a layoutPageTemplateEntryId == 0. Structure Default Values always have this value so this automatically preempts any attempt to reach the logic to add the assetDisplayPage seen in lines 1524-1527. I'm uncertain why this check was added, but the reasoning on the commit does not seem relevant to it (this is more than a rename) so it seems reasonable to remove.
> 
> Second, when the method addAssetDisplayPageEntry() is reached, anattempt to retrive a Plid using _getPlid() will be made. However, it will not be able to fetch a LayoutPageTemplateEntry, returning null and returning an error at the end of _getPlid() due to attempting to use getPlid() on a null entry. Logic is added in the null case to check for a Layout not just a LayoutPageTemplateEntry. The specific logic being used is due to the constraints of the information present which is that we have the layout's UUID, groupID, and companyID, but not any record of whether it is a private layout or not. Since the layout plid appears to be identical in all cases that the layout's uuid is the same, I don't believe this logic should cause any errors.
> 
> Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
[Test failures look unrelated](https://github.com/ChrisKian/liferay-portal/pull/82#issuecomment-452556955), but I'll have them rerun just in case.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/2069

**Pull request closed without merging**
