### PR TITLE
[TECHNICAL-SUPPORT] LPS-63370

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@Alec-Shay Does this make the translations inside of "modules/apps/foundation/login/login-authentication-google-web/src/main/resources/content/Language.properties" and "modules/apps/foundation/portal-settings/portal-settings-authentication-opensso-web/src/main/resources/content/Language.properties" irrelevant now?

**Comment by Alec-Shay** [comment]
I think the property in the path you mentioned for Google login authentication is used elsewhere (C:/Git/liferay-portal/modules/apps/foundation/login/login-authentication-google-web/src/main/resources/META-INF/resources/html/portlet/login/navigation/google.jsp), for something other than the label for the authentication menu, but the one for OpenSSO might be unused now. I haven't tried removing it to see if it affects anything else.

**Comment by jonathanmccann** [comment]
Ok, try removing both of them and see if the translation you added gets picked up automatically or if we still need those two entries in the modules.

**Comment by Alec-Shay** [comment]
Just tested it with and without those entries, and it still seems to pick up the ones I added for the Authentication menu in the Instance Settings.

For the Google entry specifically, because it's in a totally different module, I still can't say for certain whether removing it would affect other components possibly using it, but as far as I can tell, it is not being used.

**Comment by Alec-Shay** [comment]
I suppose since this is the case, then translations for all other locales (at least that were originally available in these other directories) may need to also be moved to this location.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Pei-Jung for further review: https://github.com/pei-jung/liferay-portal/pull/100

**Comment by jonathanmccann** [comment]
@Alec-Shay Please see my changes.

**Comment by Alec-Shay** [comment]
@jonathanmccann Thanks Jonathan. Shouldn't some of the automatic translations (at least the ones that actually differ) be added to the new location in their respective locale's .properties file though? Because there were a few (specifically for the "google" key at least) that had translations that were removed.

**Comment by jonathanmccann** [comment]
Yes, however, I don't have the license/credentials for the translation software we use, so I usually leave that up to BChan to build and commit.

**Comment by Alec-Shay** [comment]
Ah, okay. Sounds good.

**Pull request closed without merging**
