### PR TITLE
[TECHNICAL-SUPPORT] LPS-70514

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman 

This fix has an additional pr with the journal repo: https://github.com/jonathanmccann/com-liferay-journal/pull/11

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman Is there a reason you went with enumerating all possible options for the ```settings_``` column instead of just searching for ```classNameId:classTypePk```?

https://github.com/jonathanmccann/liferay-portal/pull/1210/commits/4e0cfe00b1ddae13964d82e5cd896df93c4e9ddc#diff-4a198b73ed2129637d0939506d5a146aR203

**Comment by mbowerman** [comment]
@jonathanmccann, I was worried that just searching for `classNameId:classTypePK` might produce a false positive (it'd be extremely unlikely, but it'd be possible nonetheless).

For instance, suppose the string to search for is "21000:12345". What if there was a settings_ entry that looked like "selectedClassNameIds=21000:123456"? We wouldn't want to the method to find this instance, but it would find it if I only searched for `classNameId:classTypePK`

**Comment by jonathanmccann** [comment]
Thanks for that explanation, that makes sense.

One more thing, is there a reason you chose to create the new ```LinkedFileEntryTypeException``` instead of using ```RequiredFileEntryTypeException```? We could avoid increasing the version. If you want to use that new exception, why did you change the ```build.gradle``` of modules that do not require this new class?

**Comment by mbowerman** [comment]
I used the new Exception so that I could display a separate error message from the error message displayed when a RequiredFileEntryTypeException was thrown (see https://github.com/jonathanmccann/liferay-portal/pull/1210/commits/4bc143d3e1687b961dd88fa63eb3184e9ebac67f). However, I'm not sure this even matters, because in my testing, the error message didn't even get displayed; instead, I was taken to a separate page that just gave a generic message like "Your request failed to complete". This might be a separate bug though (I had the same result when I tried to delete a DLFileEntryType that resulted in a RequiredFileEntryTypeException).

I updated the `build.gradle` files based on Minhchau's fixdeps script. I just ran `fixdeps com.liferay.portal.kernel com.liferay.asset.kernel.persistence` and committed all the changes that were made. I have no idea how it decides which `build.gradle` files to modify, but before running the script, I got a bunch of "Unresolved requirement" errors when starting up the portal.

**Comment by jonathanmccann** [comment]
Interesting about the build files. Good to know though. Thanks for the detailed responses, I appreciate it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3784

**Pull request closed without merging**
