### PR TITLE
J cords lps 99857

### PR DESCRIPTION
**Pull request by joshuacords**
[LPS-99857](https://issues.liferay.com/browse/LPS-99857)
[LPP-34711](https://issues.liferay.com/browse/LPP-34711)

**Problems:** The first time an article appears on a site, the notification template used should be "added". In the case of staging to a live site - if the article was modified in the staging site and then published, the notification template used was "updated".
Additionally, when staging the PortletRequestModel was null, jumping out of the try even though the articleContent and articleDiffs could still be retrieved. This caused the "updated" template to be missing that information in the email.

**Solutions:** Check to see is the article is the oldest article version instead of version 1.0. 
Surround the PortletRequestModel in a try.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@joshuacords Can you explain why creating a new PortletRequestModel throws an exception? I'd rather not have an empty catch block if it can be avoided.

**Comment by joshuacords** [comment]
Hello @jonathanmccann,

When a non-staging article update or creation happens, the serviceContext is created in UpdateArticleMVCActionCommand.doProcessAction() [here](https://github.com/liferay/liferay-portal/blob/1e8886f5efce2601b4cb38d230a63d7cbeadc0e1/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/portlet/action/UpdateArticleMVCActionCommand.java#L160-L161). This ultimately comes from the actionRequest. This will contain the _httpServletRequest which serviceContext.getLiferayPortletRequest() will to provide to PortletRequestModel() [here](https://github.com/joshuacords/liferay-portal/blob/01310c98e17145bab281ca6931c88f03ef3261ea/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L8315-L8317).

When publishing an article, the stack is being generated by JournalArticleStagedModelDataHandler.doImportStagedModel() and the serviceContext is created  [here](https://github.com/liferay/liferay-portal/blob/7a1468c988fd178d443cd986bc63842b619b43dd/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/exportimport/data/handler/JournalArticleStagedModelDataHandler.java#L827-L828). In this case there is no actionRequest carrying the _httpServletRequest to populate in the serviceContext, so it is left null and will fail in the try catch. However, getArticleDisplay() can [handle a null portletRequestModel](https://github.com/joshuacords/liferay-portal/blob/01310c98e17145bab281ca6931c88f03ef3261ea/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L7799).

**Comment by jonathanmccann** [comment]
Got it. In that case can we emulate [JournalArticleTag](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-taglib/src/main/java/com/liferay/journal/taglib/servlet/taglib/JournalArticleTag.java#L58-L61) and others like it to make sure the request and response are not null before attempting to create the PortletRequestModel?

**Comment by joshuacords** [comment]
Yep, that would work. Would you like me to resend it?

**Comment by jonathanmccann** [comment]
You can do a force push or send a new pull, either is fine with me.

**Comment by joshuacords** [comment]
Done

**Comment by jonathanmccann** [comment]
Thanks for pushing that up.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/2508

**Pull request closed without merging**
