### PR TITLE
LPS-63997 redirect with a 404 error and throw NSGE to prevent securit…

### PR DESCRIPTION
**Pull request by SamZiemer**
…y scans from thinking server is down with internal server error.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Why did you choose to include a NoSuchGroupException when the other servlets use a NoSuchLayoutException or even the same IllegalArgumentException?

**Comment by SamZiemer** [comment]
The IllegalArgumentException was still giving me a internal server error page, rather than a not found page. I can change it to a NoSuchLayoutException however.

**Comment by jonathanmccann** [comment]
Alright, let's do that to follow the other servlets' pattern.

**Comment by SamZiemer** [comment]
changed to to NSLE

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sam to further review: https://github.com/samuelkong/liferay-portal/pull/762

**Pull request closed without merging**
