### PR TITLE
LPS-75134 S3Store leaks HTTP connections when serving files as stream

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-75134

Hi @jonathanmccann,

**Regarding the second commit:**
Currently, when we request a file, the following happens:
1. Retrieve the file from the cache
2. Cleanup the cache (Delete cached files with lastModified < a set # of days)
3. Return the retrieved cache file

Reference: [S3Store.java#L187-L191](https://github.com/ericyanLr/liferay-portal/blob/f6d08808b2939b7e294e6c00a086ca7b7ec26f0f/modules/apps/foundation/portal-store/portal-store-s3/src/main/java/com/liferay/portal/store/s3/S3Store.java#L187-L191)

Currently, a cached file's lastModified date is never updated.
This means that if we retrieve a cached file, it's possible the cleanup process would delete that file.
If that we're to happen, the returned cache file would actually be no longer available.

This commit makes it so the cache file's **lastModified** will be updated with the current time whenever it is used. 

Having an updated **lastModified** timestamp would prevent the **clean up process** from removing recently used cache files.

----
Please let me know if you have any questions or concerns.
Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@ericyanLr Does https://github.com/jonathanmccann/liferay-portal/pull/1442/commits/7832806df4e0d164add7f3b047b21c2a6820417d#diff-ac42552ac4028ae65034f4b90af1a00cR207 get closed by whatever is consuming the input stream? I want to make sure we don't trade HTTP leaks for unclosed input streams.

**Comment by ericyanLr** [comment]
Hi @jonathanmccann,

While I was creating this fix, I noticed that there are actually many places in the code that could potentially end up calling this method, since it can be called using DLStoreUtil.getFileAsStream(...). 

I tried my best to go through all of them while I was creating this fix and they all appear to be getting closed properly.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/5049

**Pull request closed without merging**
