### PR TITLE
LPS-67230 Since the only impact in the portlet not existing is that the url is not properly generated when submitting the email, we shouldn't force to have both private mesagging portlets in order for the app to work. Just have a blank link in the mail.

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @jonathanmccann @daniel-t-song @SamZiemer 

I changed the logic of this pull. Can you please double check it and test it to see if it actually solves the bug?
I'd rather not force to have Private Messaging portlets if the only consequence of not having it is that the email doesn't contain the link.

Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@daniel-t-song Can you please pull down this branch and test the behavior since you are the most familiar with the ticket? Let me know if you run into any issues or if this is resolves the incorrect behavior.

**Comment by daniel-t-song** [comment]
I'll get to this as soon as I finish up another ticket.

**Comment by daniel-t-song** [comment]
@sergiogonzalez, thanks for taking the time to make this change! I tested it out and I do like how the message does go through, but the recipient does need to add the Private Messaging portlet in order to see it on the Liferay instance. I will talk with Angelo about this and see what he thinks. 

There is some discussion at the moment as to where to move forward with this portlet since technically it is a Lab portlet if I am not mistaken, but I will update this PR with anything I get as soon as I hear about.

Regards,

Daniel

**Comment by daniel-t-song** [comment]
@sergiogonzalez, question about the email: I am currently using a Fake SMTP and it hasn't detected any messages that I am sending via the Private Messaging portlet while it is working for whenever I make a user. 

Also, do you think it is necessary to add an alert if the recipient doesn't have a Private Messaging portlet installed? Or is that unnecessary?

**Comment by sergiogonzalez** [comment]
Hey @daniel-t-song I don't think it's necessary to add any alert or log in case the user doesn't have it installed because there's nothing the user sending the message that can do. 

Can you try with some real email accounts? Just to ensure that it's not a famek smtp issue.

Thx!

**Comment by daniel-t-song** [comment]
Will do @sergiogonzalez! When this is tested properly, should I submit this to @SamZiemer back up the process or will it just be confirmation that it works and you'll send it to Brian Chan?

Thanks again for the help!

**Comment by jonathanmccann** [comment]
Once you complete your testing, I'll submit it to Brian. Just let me know once you're done.

**Comment by daniel-t-song** [comment]
Sounds good @jonathanmccann. I will comment here when I am finished.

**Comment by daniel-t-song** [comment]
Interesting, I used Gmail as my SMTP and Liferay sent me an email for when I made my account, but when I sent Private Messages to the user account connected to my email, I didn't get any emails. 

When you tested this, were you able to get an email sent to the user account?

Here are the settings that I am using for reference: https://gyazo.com/88b07f66474e4c789d241635ce029e69

**Comment by daniel-t-song** [comment]
When both users have the Private Messaging portlet, the email does send while if the recipient doesn't have the Private Messaging portlet installed, it will not send an email. Previously I tested without the Private Messaging portlet installed, but now I tested it with the portlet and it works. 

Debugging without Private Messaging: https://gyazo.com/164a024b737132a248aa8be5fe3113f2
Debugging with Private Messaging: https://gyazo.com/2a0e5dcec213901af51f1904af8d7bd5

By the looks of it, it seems that this fix should do it in terms of sending the message through and the recipient getting the messages upon installing the Private Messaging portlet and will receive emails for any subsequent messages sent to them.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/42475

**Pull request closed without merging**
