### PR TITLE
[TECHNICAL-SUPPORT] LPS-72162

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mbowerman Why is the sourceFileName null? Also, do you need to update the other update methods in this class?

**Comment by mbowerman** [comment]
The sourceFileName is blank because [it is coming from the uploadPortletRequest](https://github.com/mbowerman/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/action/EditFileEntryMVCActionCommand.java#L929), but no file was uploaded.

Presumably, this bug would only apply when you update a DLFileEntry. It should never be a concern when you're adding a new DLFileEntry because the uploadPortletRequest should always be valid in that case. Since none of the other update methods in DLAppServiceImpl appear to have a sourceFileName that is passed in from an UploadPortletRequest, I do not believe it is necessary to update any of the other methods in the class.

**Comment by jonathanmccann** [comment]
The method you're updating calls one of the other update methods:

https://github.com/jonathanmccann/liferay-portal/pull/1303/commits/d7ca48a0affe5f5212b2a58efa0dd626da108dc0#diff-1e6a79c4b4cdd1898d0183cb95a01eeeR2574

Is it possible to enter that if block while the sourceFileName is null?

**Comment by mbowerman** [comment]
I don't see how you would ever reach that else block if the sourceFileName is blank, because in that case, the size would also be coming from the blank uploadPortletRequest, so it should be 0.

**Comment by mbowerman** [comment]
This appears to be a relevant test failure; I'll look into it.

**Comment by mbowerman** [comment]
ci:close

**Pull request closed without merging**
