### PR TITLE
[TECHNICAL-SUPPORT] LPS-73814

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
If we are fetching the users from the Organization, Group, or User Group, wouldn't it be possible that the first user returned is not an administrator?

**Comment by mbowerman** [comment]
I was under the impression that if you assigned a Organization, Group, or User Group to a certain role, then every user who is a member of that Organization, Group, or User Group would inherit that role. Is that not the case?

**Comment by jonathanmccann** [comment]
Yup, looks like that's the case. Thanks for clarifying.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adam for further review: https://github.com/brandizzi/liferay-portal/pull/439

**Pull request closed without merging**
