### PR TITLE
Lps 87985 updated

### PR DESCRIPTION
**Pull request by gregory-bretall**
https://issues.liferay.com/browse/LPS-87985

Resent from https://github.com/gregory-bretall/liferay-portal/pull/133

Test Results and conversation on the issue can be found here: https://github.com/gregory-bretall/liferay-portal/pull/131#discussion_r240411955

@ricky-pan

### CODE REVIEW

**Comment by jonathanmccann** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1731/files#diff-49524ff7524f70487b8e4a55cb8a6563R628 The replace is never assigned to a value so do we even need this block of code?

https://github.com/jonathanmccann/liferay-portal/pull/1731/files#diff-67e70a236fb66e9b127d5cd935fd680dR29 Do we need to check for `endDelimiter` here as well?

@SpencerWoo @ricky-pan @gregory-bretall

**Comment by ricky-pan** [comment]
Hi @jonathanmccann , 
1) Yes, I made a mistake and did not reassign `dateFormatPattern` after calling replace
2) No, because the endDelimiter appears only at the end of some dateFormats using periods

**Comment by ricky-pan** [comment]
2. I think the result would not change, because though it would check for a dateFormat ending with "/" and "-", those would not return true.

**Comment by jonathanmccann** [comment]
Shoot, I was misreading it. Thanks for the clarification.

**Comment by jonathanmccann** [comment]
I tested the pull and there are some issues with it:

1. English (en) - Loses precision on year (2018 vs 18)
2. Hungarian (hu) - When the page is first loaded the date is `18.12.13__.`. When the date is clicked the `__` disappears. I also believe this should have a four digit year.

Please take a look at these issues and resend the pull also including the removal of the `replace` we discussed earlier.

**Comment by ricky-pan** [comment]
Hi Jonathan,
1. The specified Java locale uses "M/d/yy" by default. "yyyy" can be specified in a custom-date-format.
2. You are right. This had to do with replace not working properly because fullYear was not receiving the right values. I edited that as well as the placeholder function that it responds appropriately.

**Pull request closed without merging**
