### PR TITLE
LPS-59052

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @arbetts,

I think I'm a little confused as to the use case of this feature. It seems like it is only for testing purposes, but is that physical testing on the server or via JUnit tests? Also, if that understanding is correct, I feel like an arbitrary timeout doesn't make sense as we should just wait for the task to complete. Let me know if you can provide some more information about this pull, thanks.

**Comment by arbetts** [comment]
@jonathanmccann 

the use case comes directly from Shuyang. he said that he needs the blocking behavior for testing purposes. They have scripts that run tests on the portal that depend on the indexing process to be finished before they run. These are ant scripts that call urls so they need url parameters they can set that will cause the portal to wait.

**Comment by jonathanmccann** [comment]
Thanks for the explanation.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/1938

**Pull request closed without merging**
