### PR TITLE
LPS 58702: LayoutSet should not have any reference of Site Template if there is no layout associated with it

### PR DESCRIPTION
**Pull request by mosoni**
Hi Jonathan,

As discussed and with respect to your comment https://github.com/jonathanmccann/liferay-portal/pull/834#issuecomment-142399909 please find the summary below

1) Have changed the author to myself.
2) FinderImpl approach has been removed as same thing can be done using ActionableDynamicQuery 3) When we delete the Site then it deletes the entry from Layout table, which means there will not be any entry corresponding to group of LayoutSet. Therefore while deleting the site , the page count should be 0 because there is no layout is associated anymore.
3) My fix was not working because VerifyGroup was updating the isSite column as 1 and in my logic i added the check with that column value. In this PR i have changed the Logic which will update layoutSet and Group if there is no layout associated with it.

### CODE REVIEW

**Comment by mosoni** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hi Mohit,

Thank you for making the changes, I appreciate it. I did have one question though: Do we need to check "!group.isStagingGroup()" in the verify process? I see that it is in LayoutSetLocalServiceImpl but not sure if we need it as well.

**Comment by jonathanmccann** [comment]
Hey Mohit,

Thanks for talking to me above the point above. I did have one more question however, do we need to set the Group's site parameter to false in LayoutSetLocalServiceImpl?

**Comment by mosoni** [comment]
Hi Jonathan,

I have taken care of both the situation as in any case Site is false and there is no layout associated with it then reference should be updated, on the other case if Site is true then also we have to check if there is no layout then correct the layoutset as well as group's site as false.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3677

**Pull request closed without merging**
