### PR TITLE
LPS-59156 Long precision is lost in JSON Web Service calls when JSONO…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…bjectImpl is used instead of JSONSerializerImpl

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@Preston-Crary Do we also need to make this fix in JSONArrayImpl? Also, should we use "Long.toString()" or "String.valueOf()"? You used the former in your last pull and the latter in this pull.

**Comment by Preston-Crary** [comment]
Yes, you are correct. I've updated the pull to fix the inconsistency.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Igor for further review: https://github.com/igorspasic/liferay-portal/pull/91

**Pull request closed without merging**
