### PR TITLE
LPS-68655

### PR DESCRIPTION
**Pull request by ChrisKian**
I wasn't quite sure what to change the description to, so I just gave it my best shot.

https://issues.liferay.com/browse/LPS-68655
https://in.liferay.com/web/global.engineering/forums/-/message_boards/view_message/23902816#_19_message_25434389

### CODE REVIEW

**Comment by ChrisKian** [comment]
@jonathanmccann, was this closed in error or should it be sent to the subrepo?

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
In this case, the failing test was "WebDAVLitmusBasicTest" and it was deemed severe enough to warrant automatically closing the pull request. I reopened the pull, retested it, and discovered that it wasn't your fix that was causing the issue.

Please take a look at the following article and included videos to understand the test results:

https://grow.liferay.com/group/guest/learn/-/wiki/Grow/Investigating+Pull+Request+Test+Results

**Comment by jonathanmccann** [comment]
Also, please update the LPS to include steps so that QA can easily find where this message is.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3514

**Pull request closed without merging**
