### PR TITLE
LPS-65463

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Bryan,

Is there a possibility of ending up with a duplicate title since we aren't updating the files that are in the trash? What happens if we try to restore a document and it has a duplicated title?

Thanks.

**Comment by BryanEngler** [comment]
i dont think we would get duplicates. and if we did, there is a page that lets you overwrite or rename the doc from the recycle bin when you restore it.
restore

**Comment by jonathanmccann** [comment]
Awesome, thanks for looking at that.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3118

**Pull request closed without merging**
