### PR TITLE
Lps 124520

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-124520

See ticket for issue description.

The reason the issue occurs is because we are not able to fetch an assetEntry due to utilizing the classNameId of FileEntry when we should be using the classNameId of DLFileEntry.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
`getClassNameId` will always return FileEntry so shouldn't we update what is being returned there since the new check will always be true? https://github.com/jonathanmccann/liferay-portal/pull/1852/commits/8dc5fd3fbb7762e7b09dfaf3a8e0f065d4c19367#diff-5536318382b7e8850960910f22d2f56e1d2627b807c9890b1f0d665f48e7b614R47

**Comment by brianikim** [comment]
Hello @jonathanmccann ,

You are correct, but we cannot alter that method directly as that method is utilized by other classes as well and the other classes assume it will always be a FileEntry model.

As an alternative, I can make the change so that the call is in the folowing:

`getAssetRendererFactoryByClassNameId(PortalUtil.getClassNameId(DLFileEntry.class));`

Let me know if you foresee any issues with the above potential alteration.

Sincerely,
Brian Kim

**Comment by jonathanmccann** [comment]
I think that makes more sense. As long as you're sure the other callers require it to be FileEntry. It seems strange that some would need FileEntry while others need DLFileEntry.

Go ahead and force push and I'll send it along.

**Comment by brianikim** [comment]
Hello @jonathanmccann ,

I made the change and force pushed.

Sincerely,
Brian Kim

**Comment by jonathanmccann** [comment]
Reviewed and sent to the Lima team for further review: https://github.com/liferay-lima/liferay-portal/pull/1190

**Pull request closed without merging**
