### PR TITLE
LPS-124261 Reset the system configuration for blogs when the configurations are updated

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-124261

The issue here was that the RSS toggle for blogs configuration was not being updated. This was caused by the typeSettings not getting updated because the old settings were overridding it.
To fix the issue, I created a resetConfiguration method for ConfigurationOverrideInstance and made a call to that method in processAction() for BlogsAdminConfigurationAction when the action is "update".

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Reviewed and sent to the Lima team for further review: https://github.com/liferay-lima/liferay-portal/pull/1196

**Comment by jonathanmccann** [comment]
@noornajj Nice work on this, thank you.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/9664

**Comment by jonathanmccann** [comment]
Reviewed and sent to Drew for further review: https://github.com/drewbrokke/liferay-portal/pull/1270

**Pull request closed without merging**
