### PR TITLE
[TECHNICAL-SUPPORT] LPS-67892

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @NolanChan

### CODE REVIEW

**Comment by NolanChan** [comment]
nodejs install issues are also happening on CI, so re-opening, hoping that it resolves itself

**Comment by NolanChan** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
I went ahead and reverted the language changes since they were coming across as automatic copy and weren't being translated. I'll leave it up to Brian to translate them properly. Also, the keys were missing periods at the end of the phrase so I added those in as well. Please let me know if you have any questions.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3467

**Pull request closed without merging**
