### PR TITLE
[TECHNICAL-SUPPORT] LPS-74219

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Could you explain a bit why are you checking to see if the servletContextName is the same as the portalServletContextName? I'm not quite understanding the fix based off of the LPS and commit message.

**Comment by mbowerman** [comment]
In a default instance of Liferay in which tomcat is deployed and the portal context is root, the servletContextName will be blank for the filterConfig that corresponds to the portal. However, on WebSphere (or possibly on non-root tomcat, haven't tested), the servletContextName will be non-blank, equal to PortalUtil.getServletContextName(). If this happens, it won't register any [filters with a blank servlet-context-name](https://github.com/jonathanmccann/liferay-portal/blob/master/modules/apps/foundation/portal-security-audit/portal-security-audit-wiring/src/main/java/com/liferay/portal/security/audit/wiring/internal/servlet/filter/AuditFilter.java#L39) since it is looking for filters with servlet-context-name=PortalUtil.getServletContextName() instead. So, whenever we are using the filterConfig corresponding to the portal, we want to make sure that the servletContextName we pass in is blank.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1348

**Pull request closed without merging**
