### PR TITLE
LPS-69227 NullPointerException when enabling local staging for a site that has no name in the instance's default language

### PR DESCRIPTION
**Pull request by cleydyr**
Relevant issue: https://issues.liferay.com/browse/LPS-69227
Forum discussion: https://in.liferay.com/web/support/forums/-/message_boards/message/26314954

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Hey @cleydyr,

Looking over this fix, it seems we'll be looping over all of the entries in the ```nameMap``` and constantly overwriting the ```groupKey``` variable with that name's value. If that's correct, then the ```groupKey``` will always be set to the last entry in the ```nameMap```. Am I understanding that correctly? If so, that doesn't seem like the correct behavior.

**Comment by cleydyr** [comment]
@jonathanmccann you're completely correct. I've put a break once the first valid value is found as a compliment to this fix. Otherwise, it would only be necessary to have a few more interactions over the nameMap, but the groupKey wouldn't end up being null.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/586

**Comment by cleydyr** [comment]
Thanks.

**Pull request closed without merging**
