### PR TITLE
LPS-68647

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @jonathanmccann,

This issue cannot be tested in master because it requires an Oracle database. So I made the fix in ee-7.0.x, verified that the fix worked, and cherry-picked it into master.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman Please be sure you send your pulls through @samziemer first. I'll review this but keep it in mind for next time.

**Comment by mbowerman** [comment]
@jonathanmccann The reason I sent this to you is because the LPP that this is associated with is past its due date. I had thought that in that case we were supposed to send the pull request directly to you. Is this no longer true?

**Comment by jonathanmccann** [comment]
I wasn't aware of that, but it makes sense. Thanks for letting me know.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Miguel for further review: https://github.com/migue/liferay-portal/pull/883

**Pull request closed without merging**
