### PR TITLE
LPS-62148 Account for existing events that 'Repeat On month's Last Da…

### PR DESCRIPTION
**Pull request by ericyanLr**
…y of the Week'

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:retest

**Comment by ericyanLr** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Please be sure to send your pulls to Bryan first.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adam for further review: https://github.com/brandizzi/liferay-portal/pull/150

**Pull request closed without merging**
