### PR TITLE
[TECHNICAL-SUPPORT] LPS-71657

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Make sure you guys are checking the commit LPS number that it's correct next time.

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by mbowerman** [comment]
Hi @jonathanmccann,

Please see https://github.com/jonathanmccann/liferay-portal/pull/1279

**Comment by mbowerman** [comment]
ci:close

**Pull request closed without merging**
