### PR TITLE
LPS-59184

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
just pushed a small change fyi

**Comment by jonathanmccann** [comment]
Hey @ChrisKian,

I just had a couple of questions:

1. What is failing the unique index, is it the templateKey? If it is templateKey, then where does this field get generated since it doesn't exist in 6.1.x?
2. In the steps to reproduce, we're adding two templates, that are both usable, but after the upgrade we end up deleting one of them and now only have one template. Is that correct?

**Comment by BryanEngler** [comment]
i just ran through the steps real quick and this is what i saw....
1 - duplicate data is not actually being created. if the customer has duplicated data i dont know how that happened because in 6.1 we have a unique index IX_E802AA3C on JournalTemplate (groupId, templateId);
if they deleted the index or something like that, not our fault, we dont need to fix it...

in the upgrade process to 6.2 the journaltemplate.templateId gets converted to the ddmtemplate.templateKey. for ddmtemplates that were created in 6.1, the upgrade process to 6.2 uses the current time in milliseconds as the value when adding the ddmtemplate.templateKey. this all means that the unique index IX_E6DFAB84 on DDMTemplate (groupId, classNameId, templateKey) will NOT be prevented from being created due to a data constraint, because the data already had to follow the IX_E802AA3C constraint  (which means regardless of whatever classNameId might be, there wont be any data entries with the same values for groupId and templateKey, therefore fulfilling the constraint requirements for IX_E6DFAB84).

when i ran through the upgrade, this is the error i got that prevented the index from being created:
ERROR 1170 (42000): BLOB/TEXT column 'templateKey' used in key specification without a key length

this error can be resolved using a query such as 
create unique index IX_E6DFAB84 on DDMTemplate (groupId, classNameId, templateKey(255));

im not exactly sure how we would implement that fix, but the proposed solution in this pull doesnt seem to be the correct fix based on the steps i used to test... also, i was using mysql, and its possible there would be some differences with oracle

**Comment by ChrisKian** [comment]
Hey Jonathan,

1.  The unique index is failing when all three columns are duplicated together.  The template key is created in the upgrade process "UpgradeDynamicDataMapping.java".  Basically, we create a new column for the templateKey, then:
```

if (Validator.isNull(templateKey)) {
	templateKey = String.valueOf(System.currentTimeMillis());
}
else {
	templateKey = StringUtil.toUpperCase(templateKey.trim());
}
```
In my testing, after the upgrade, there was no value set for template, but the column wasn't null either, just blank.  I'll retry since the time should be set, and would prevent this issue from happening.

2.  However, looking back, there is a chance the client created unique DDMTemplates which only differ via the script column .  There was no way to me to know this since I cannot gain access to their DB.  So even if duplicate entries are being created, I don't think deleting them is safe.

**Comment by jonathanmccann** [comment]
Thanks for the replies guys. I'm going to go ahead and close this out for the time being since it seems this fix needs to be reworked.

Also, just for the future, a fix like this belongs in the upgrade process where the issue started occurring. If the issue is caused by a bad upgrade then we should fix the upgrade itself instead of cleaning it up afterwards. We also can't have something in a verify process that should only be run once. Once that fix gets committed, then we will have to manually fix the user's database, which could take the form of a verify process or Groovy script.

**Pull request closed without merging**
