### PR TITLE
J cords lps 70427

### PR DESCRIPTION
**Pull request by joshuacords**
Changed Query to use "IN" instead of "OR".

### CODE REVIEW

**Comment by joshuacords** [comment]
ci: reopen
ci: retest

**Comment by joshuacords** [comment]
ci: reopen

**Comment by joshuacords** [comment]
ci: retest

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Thanks for making all these changes!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/800

**Pull request closed without merging**
