### PR TITLE
[TECHNICAL-SUPPORT] LPS-73749

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @JonathanAichler

Notes from Jonathan:

> Here is an updated version for the last PR based off of this thread from the [jQuery Github](https://github.com/jquery/jquery/issues/2432) amongst the jQuery devs.
> 
> LPP
> https://issues.liferay.com/browse/LPP-26346
> 
> LPS
> https://issues.liferay.com/browse/LPS-73749

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@JonathanAichler @SamZiemer Again, please watch your formatting. It has the same issues as the previous pull which I rejected.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/1760

**Comment by JonathanAichler** [comment]
@jonathanmccann I ran the source formatter multiple times to make sure it was ok. Could you let me know what the specific issue is so that I can avoid it in the future? Thanks.

**Comment by jonathanmccann** [comment]
You can see my changes in the pull request I submitted.

If you want to fully check Javascript files for formatting errors, you'll have to use https://github.com/natecavanaugh/check-source-formatting Our regular formatter doesn't usually pick up too many issues with JS files.

**Pull request closed without merging**
