### PR TITLE
Lps 58141 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Jonathan,

I've removed uses of _computerAddress as per your suggestion [here](https://github.com/jonathanmccann/liferay-portal/pull/808)

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @SamZiemer,

Looks like there's a compile error in the plugins. Let me know though.

Thanks!

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1003

**Pull request closed without merging**
