### PR TITLE
LPS-59483 check for null selUser

### PR DESCRIPTION
**Pull request by SamZiemer**
Hey Jonathan,

Hugo suggested on https://github.com/hhuijser/liferay-portal-ee/pull/2708 that we should add this to master rather than being strictly a 6.2 fix since right now it is not an issue in master, but could potentially become one in the future. This will also help keep the two branches in sync.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@SamZiemer I believe this compile errors are coming from the JSPs you modified?

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Looks like I missed changing double quotes to single quotes, thanks for letting me know!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3727

**Comment by jonathanmccann** [comment]
Also, be sure to add Master as the affects version on the LPS.

**Pull request closed without merging**
