### PR TITLE
LPS-78294 Fix Special Character Inconsistency in Documents and Media

### PR DESCRIPTION
**Pull request by gregory-bretall**
CI Tester was failing so test results are not correct. 

Resent from https://github.com/gregory-bretall/liferay-portal/pull/39

Changes made described here https://github.com/gregory-bretall/liferay-portal/pull/39#issue-173266641

@brianikim

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/4251

**Pull request closed without merging**
