### PR TITLE
LPS-69212 Review

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hey @migue,

Could you please explain why you moved UpgradeTeam from the 7.0.0 UpgradeProcess to the 7.0.3 UpgradeProcess? If my understanding of the update*.sql files is correct, we add the uuid_ column to the Team table in 7.0.0. Thus, anyone who is upgrading to 7.0.3 from 7.0.0 or later would already have the uuid_ column in their Team table, populated with valid UUID values.

**Comment by migue** [comment]
Maybe I misunderstood the change then, sorry. Just ignore this commit :D

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/44847

**Pull request closed without merging**
