### PR TITLE
[TECHNICAL-SUPPORT] LPS-70705

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
This width limit seems to be introduced by LPS-61508. Do you know why it was 900 pixels? It seems that this is very purposeful and removing it could have unintended consequences, but I could be wrong. Also, did you test out other places that use Liferay.UrlPreview to confirm that removing the width limit does not break anything there?

**Comment by joshuacords** [comment]
I didn't see other places where the UrlPreview is used. I did make sure it did not undo the original fix which added the 900 pixels max. As far as I understand 900 pixels does not affect other functionality.

**Comment by jonathanmccann** [comment]
Thanks for taking a look.

@carloslancha could you shed some light on this max width and whether or not it needs to be 900 pixels?

**Comment by jonathanmccann** [comment]
https://github.com/carloslancha/liferay-portal/pull/87

**Pull request closed without merging**
