### PR TITLE
LPS-79309

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-79309

My solution to ensure the URL was correct as well as many of the params in the request is to redirect to the default locale's version of the page.  For example, the following URL would go from this:
`http://localhost:8080/badLocale/web/guest/home`
to this:
`http://localhost:8080/web/guest/home`
Then the I18nServlet can figure out the default locale to serve as it normally would when excluding the locale code.

If I based my solution around not redirecting, but rather placing the default locale where needed, the URL wouldn't change (although the page would be the correct locale).  But in my opinion, the real problem with this is sometimes the servlet wouldn't know what's a locale and what's the URL path, so i'd get path infos like this:
`web/guest/badLocale/web/differentSite`
and I'm not sure how to resolve that without tinkering with the request in a hacky way.

Let me know if you have any ideas for a better solution, or if you have other questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Relevant test failures seem unrelated.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/1695

**Pull request closed without merging**
