### PR TITLE
LPS-74194

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-74194

Let me know if you have any questions

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/1078

**Pull request closed without merging**
