### PR TITLE
LPS-55247

### PR DESCRIPTION
**Pull request by BryanEngler**
seems like a correct fix but so did the last one haha. basically the problem was that we are trying to get a layout based on the visibility of the template's layout. but template layouts are always private, so when you create a site, theres a disconnect between the private layout page and the public site page, so we get a NoSuchLayoutException... this basically says if we dont find a layout based on isPrivateLayout, check if the source group is a site template, and if it is, grab the site's layout which will be public (by passing false instead of isPrivateLayout).

### CODE REVIEW

**Comment by BryanEngler** [comment]
Not sure if it applies here but i could maybe also look into using PortletDataHandlerKeys.LAYOUTS_IMPORT_MODE_CREATED_FROM_PROTOTYPE if you think that might be a better way to do it...

**Comment by jonathanmccann** [comment]
Looking at it briefly it seems like it might work. We can discuss it tomorrow and figure out the best way to do it.

**Comment by jonathanmccann** [comment]
Closing per our discussion.

**Comment by BryanEngler** [comment]
new pr at https://github.com/jonathanmccann/liferay-portal/pull/683

**Pull request closed without merging**
