### PR TITLE
LPS-88862

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-88862

From @nellyliupeng, CC @wanderlast 

> Currently, "Sign In" is being used as portlet title as it is the display name for the Login Portlet.
> However, there is an issue as the portlet title does not update when action commands such as "create account" and "forgot Password" within the portlet are called. This fix was made to update the portlet title accordingly. 

Passing SF test: https://github.com/wanderlast/liferay-portal/pull/18#issuecomment-452135677
Passing Relevant tests: https://github.com/wanderlast/liferay-portal/pull/18#issuecomment-452156279

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@nellyliupeng Can you please explain why the current implementation does not work? We seem to use this construct elsewhere so if there's a fundamental reason why setting the title in this way doesn't work then we should update all of them.

In the mean time, please deliver the current solution as an SDH to the client as it works and is a very low risk.

**Comment by nellyliupeng** [comment]
Hi @jonathanmccann!
Thank you for taking a look at this PR. I will go ahead and prepare an SDH as mentioned to the customer (the customer is on 7.0.x).
In response to your question, I am not entirely sure why the current implementation does not work when it's in .java but it does when in .jsp. I will dive deeper into it and compare to the other occurrences and provide an update here.

**Comment by jonathanmccann** [comment]
Thank you for doing that. I'll go ahead and close this for now but please let me know the results of your findings.

**Comment by nellyliupeng** [comment]
Hello @jonathanmccann! 

I wanted to update you with the results of my findings.
I found out that the value of the title is lost as the MVC portlet process handles the render requests and responses. These are my observations:

**With existing implementation:**
```
CreateAccountMVCRenderCommand:
    renderResponse.title is set to "Create Account"

MVCPortlet
    super.render()
        renderResponse.title is set back to "Sign In"	
            (why? here request still contains value of "Sign In")
	    for example, if you evaluated the following at this MVCPortlet:
	    PortalUtil.getPortletTitle(renderResponse) -> "Create Account"
	    PortalUtil.getPortletTitle(renderRequest)  -> "Sign In"    <---- this is what's returned at super.render()

create_account.jsp
    renderResponse.title therefore displays "Sign In"
```


**With introduced solution:**
```
CreateAccountMVCRenderCommand:
    renderResponse.title is null

MVCPortlet
    super.render()
        renderResponse.title is set to "Sign In"	

create_account.jsp
    renderResponse.title is set to "Create Account"
```



Do you have any insight as to why the value of the title is lost with the current implementation?
I noticed that `CreateAnonymousAccountMVCRenderCommand` (from LoginPortlet) may also need to be updated in addition to the solution submitted to avoid the issue described.

Other occurrences of **renderResponse.setTitle()** in .java files:

- There are other MVCRenderCommands that seem to be related to staging, export/import. I haven't been able to identify where in the portal they are displayed in order to test those. 
- Other .java files that contain renderResponse.setTitle() are not MVCRenderCommands
- Lastly, other occurrences of renderResponse.setTitle() appear to be called from .jsps so there may be no issues with those.

**Comment by jonathanmccann** [comment]
Thank you for the explanation, I feel more comfortable about sending this forward now. Please make the following changes though:

1. Make the same change for `CreateAnonymousAccountMVCRenderCommand`
2. Use `LanguageUtil` to translate the key like we do in other JSPs
3. See if the Staging use cases need to be updated as well

For #3 I found how to trigger two of the three use cases:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-web/src/main/java/com/liferay/exportimport/web/internal/portlet/action/ExportImportMVCRenderCommand.java#L62

Click on the dropdown menu for a portlet and select `Export / Import`.

thttps://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-web/src/main/java/com/liferay/exportimport/web/internal/portlet/action/ExportImportMVCRenderCommand.java#L62

Enable local live staging, click on the dropdown menu for a portlet and select `Staging`

https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-configuration-web/src/main/java/com/liferay/staging/configuration/web/internal/portlet/action/ViewMVCRenderCommand.java#L62

I have not been able to trigger this one but I assume if the first two need to be changed this one does as well.

Please let me know if you have any questions.

**Comment by nellyliupeng** [comment]
Hi @jonathanmccann,
Thank you for your reply and for looking over the steps as well. Per your instructions I was able to trigger the usages and debug it!

In regards to the Staging use cases:
They also are facing the same scenario where the renderResponse.title is overridden. Currently:
```
ExportImportMVCRenderCommand
    renderResponse.title is set to "Hello World" (ActionUtil.getTitle(portlet, renderRequest))

MVCPortlet
    super.render()
        renderResponse.title is set to "Export/Import"

export_import.jsp
    renderResponse.title is therefore "Export/Import"
```

This occurs for both `ExportImportMVCRenderCommand` and `PublishPortletMVCRenderCommand`, but currently this doesn't seem to pose a major impact on UI as the title shown does not come from the related jsp and it displays properly (ie. "Hello World - Export / Import" is displayed).

I have prepared the updated fixes for (1) and (2) and will be submitting a new PR with those changes. Please let me know if you deem necessary to remove the renderResponse.setTitle call for the staging use cases and I can include those changes as well.

Thank you once again!

**Pull request closed without merging**
