### PR TITLE
LPS-133676

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-133676 URL of "Link to URL" page not updated during publication

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Since these URLs can lead to external sites is there a possibility that our logic would catch and replace something that should not be replaced?

**Comment by mbowerman** [comment]
I don't believe it should be possible. At least, in theory, the only things that should be flagged and replaced are URL's that point to content/assets on the staging site. From my understanding, this validator is meant to be used on content that can contain URL's of any type, so it should be robust enough to avoid flagging URLs that don't link to the staging site.

If you look at [the code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/exportimport/content/processor/DefaultTextExportImportContentProcessor.java#L38) of this processor, it just calls four specific subprocessors (DLReferences, JournalFeed, LayoutReferences, and LinksToLayout). Each of these subprocessors has their own specific URL pattern that they look for (you can see an example [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/exportimport/content/processor/DLReferencesExportImportContentProcessor.java#L344)), so if a URL doesn't match the pattern of one of those four asset types, then it shouldn't be flagged and replaced, even if for instance the URL happens to have the staging group id in it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Vendel for further review: https://github.com/vendeltoreki/liferay-portal/pull/202

**Pull request closed without merging**
