### PR TITLE
LPS-68773

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@gregory-bretall Does it not need the
```
new com.liferay.marketplace.internal.upgrade.v0_0_1.UpgradeApp()
```
?

**Comment by gregory-bretall** [comment]
In my testing I found that including UpgradeApp caused duplicate information to be added as that upgrade process adds the required column if it doesn't already exist, but the 2_0_0 upgrade step always adds the required column without checking.  I could change it to add a check to the 2_0_0 upgrade step to see if the required column already exists before adding it if we want to add in the UpgradeApp step.

**Comment by jonathanmccann** [comment]
That's alright, I just wanted to be able to explain why it was missing to the engineers. Thanks!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Miguel for further review: https://github.com/migue/liferay-portal/pull/885

**Pull request closed without merging**
