### PR TITLE
LPS-57892

### PR DESCRIPTION
**Pull request by BryanEngler**
seems like bchan did the same type of SF in PortletLocalServiceImpl as what i added... i just assumed it applies here too but if you think it doesnt you can remove the commit

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ChrisKian 

Just want to make sure we should be looking for "requires-namespaced-parameters" and not "com.liferay.portlet.requires-namespaced-parameters" like in the previous pull.

**Comment by ChrisKian** [comment]
Hey Jonathan,

I believe we need to check for both.  Basically, "requires-namespaced-parameters" is set at the portlet level, so it has priority over "com.liferay.portlet.requires-namespaced-parameters" which is set at the WAR level.

What my code change should be doing is using "requires-namespaced-parameters", but if that cannot be found, it should use "com.liferay.portlet.requires-namespaced-parameters", and if that cannot be found, "portletModel.isRequiresNamespacedParameters()".

Unless I am reading what BChan said incorrectly:  https://github.com/brianchandotcom/liferay-portal/pull/29934#issuecomment-138607123

**Comment by BryanEngler** [comment]
i questioned that as well... seems like bchan wants to check "requires-namespaced-parameters" even though we werent doing it previously

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/1775

**Pull request closed without merging**
