### PR TITLE
LPS-55680

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@arbetts I added some comments inline, please take a look.

**Comment by arbetts** [comment]
@jonathanmccann 

before these changes we were catching the error and logging it, but after returning from the boolean method we were throwing an exception if the method returned false.

we are rethrowing an exception right after catching a general Exception in order to throw this specific type of exception FeedContentFieldException. we do this in many places in the portal.

**Comment by arbetts** [comment]
@jonathanmccann 

responded to the inline comments ... if you feel that the refactoring is a problem then you can remove those commits and just use the last one. Thats why put them into separate commits.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3829

**Pull request closed without merging**
