### PR TITLE
[TECHNICAL-SUPPORT] LPS-57844

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Can you take a look at these errors and let me know if they are relevant? I feel like they are since the other pulls aren't failing.

**Comment by arbetts** [comment]
reviewing the test failures now

**Comment by jonathanmccann** [comment]
Closing due to test failure from plugin.

**Comment by lipusz** [comment]
Hi @arbetts 

FYI:

@d8c41ac: you cannot do this, because the assets should be still searchable from the admin portlets even if the group is inactivated.

@adamnagy is working on the final fix for master based on your SDH for ee-6.1.x

**Comment by arbetts** [comment]
@lipusz @adamnagy

thanks

**Pull request closed without merging**
