### PR TITLE
LPS-70492

### PR DESCRIPTION
**Pull request by ChrisKian**
Calling the method "PortalUtil.getControlPanelPortletURL(request, group, portletId, 0, 0, PortletRequest.RENDER_PHASE)" with a null group is the same as "PortalUtil.getControlPanelPortletURL(request, portletId, PortletRequest.RENDER_PHASE)".  So since I only set the group if themeDisplay is null, it's the same logic you showed here: https://github.com/jonathanmccann/liferay-portal/pull/1205#issuecomment-278044525

Let me know if I missed anything else.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3781

**Pull request closed without merging**
