### PR TITLE
Lps 124521

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-124521

See ticket for issue description.

Solution is to increase width for the asset items.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
After implementation:
After

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
Reviewed and sent to the Echo team for further review: https://github.com/liferay-echo/liferay-portal/pull/3187

**Comment by jonathanmccann** [comment]
Reviewed and sent to the Frontend team for further review: https://github.com/liferay-frontend/liferay-portal/pull/601

**Pull request closed without merging**
