### PR TITLE
LPS-69824

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
I made some changes so that if the ```close``` method throws an exception, we still go into the ```catch (Throwable throwable2)``` instead of continuing on with the method. Let me know if you have any concerns about my changes. Thanks!

https://github.com/shuyangzhou/liferay-portal/pull/3588

**Comment by eperezg** [comment]
Hi @jonathanmccann,

I think those changes are a better solution that mine, but I couldn't make it work, I get the following error when trying to use the autocloseable try statement:

`     [echo] /tmp/ServiceBuilder.temp:198:17: expecting EOF, found 'ObjectInputStream'
     [echo] 	at antlr.Parser.match(Parser.java:211)
     [echo] 	at de.hunsicker.jalopy.language.antlr.InternalJavaParser.parse(InternalJavaParser.java:308)
     [echo] 	at de.hunsicker.jalopy.language.JavaRecognizer.parse(JavaRecognizer.java:588)
     [echo] 	at de.hunsicker.jalopy.Jalopy.parse(Jalopy.java:1212)
     [echo] 	at de.hunsicker.jalopy.Jalopy.format(Jalopy.java:1044)
     [echo] 	at de.hunsicker.jalopy.Jalopy.format(Jalopy.java:1017)
     [echo] 	at com.liferay.portal.tools.ToolsUtil.writeFile(ToolsUtil.java:443)
     [echo] 	at com.liferay.portal.tools.ToolsUtil.writeFile(ToolsUtil.java:481)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder._createServiceClpSerializer(ServiceBuilder.java:3037)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:795)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:218)`

Let me know if you have tried to generate a service using this solution.

Regards,
Eduardo.

**Comment by jonathanmccann** [comment]
What command did you use to run the service builder and where did you run it from? I was writing the code in a regular Java class to see if there were any errors but didn't generate a service.

**Comment by eperezg** [comment]
I created a service builder portlet on the plugins repository.
Then I modified the ftl which is on dependencies / com.liferay.portal.tools.service.builder / lib / com.liferay.portal.tools.service.builder.jar in order to apply your changes.

Finally I executed the ant build-service task.

I tested it both on command line and on liferay ide with the same result.

Regards,
Eduardo

**Comment by jonathanmccann** [comment]
Hey Eduardo,

Thanks for letting me know. Unfortunately, my tasks have piled up on me today and I wasn't able to revisit this fix. I'm also going to be out for the next few weeks. Please feel free to send along whatever fix you believe is the best to Engineering for review, although I do think that we should maintain the previous method's logic.

Thanks.

**Pull request closed without merging**
