### PR TITLE
[TECHNICAL-SUPPORT] LPS-72274 Log and create a UI warning for unmapped mvcRenderCommandName's

### PR DESCRIPTION
**Pull request by SGM3**
This PR does needs a build-lang. Adds additional logging to MVCPortlet to log bad usage of mvRenderCommandName's.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Please utilize something like SessionMessages instead of setting attributes on the original request (https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/util/AssetPublisherUtil.java#L511 / https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-publisher-web/src/main/resources/META-INF/resources/configuration/asset_entries.jsp#L89).

Also, be sure to commit your source formatting changes to the commit that introduced them. https://github.com/jonathanmccann/liferay-portal/pull/1316/commits/0f1ea4063f00b19f1441dbc648c85da9b8e93f1b is a bit confusing because it has half source formatting changes and half actual changes.

**Comment by SGM3** [comment]
I have it utilizing SessionMessages now, but now face this new issue:

source formatter changes from
```
SessionMessages.contains(renderRequest, "no-such-mvc-render-command-x")
```
to
```
SessionMessages.contains(renderRequest, "noSuchMvcRenderCommandX")?
```
I looked through the `*Constants` and `*Keys` files from "portal-web/docroot/html/common/init.jsp" for fitting location for the constant string, but do not see a fitting home, any suggestions? I don't think this constant requires a new file.

Simple workaround is to include it as defined string constant and use the constant in scriplet form:
```
    <%
        final String noSuchMvcRenderCommandX = "no-such-mvc-render-command-x";
    %>

    <c:if test="<%= SessionMessages.contains(renderRequest, noSuchMvcRenderCommandX) %>">
```

**Comment by jonathanmccann** [comment]
What's wrong with using "noSuchMvcRenderCommandX" as the key? That's what the example I posted above does.

**Comment by SGM3** [comment]
Following standards, since "no-such-mvc-render-command-x" is a language property, it wouldn't be appropriate. Do you recommend I create a constant class anyway?

**Comment by jonathanmccann** [comment]
In the code that I provided, the key passed from the Java class is used in a conditional statement. If that conditional statement is true, then a language key is used to display the message.

You haven't clarified why you are using a language key as the key in SessionMessages, so I'm trying to get you to follow the example I have given you. In that example the language key is not passed in SessionMessages. Can you please explain why you need the language key in SessionMessages since to me it seems this is unnecessary and we can simply follow the pattern set forth in my example?

**Comment by SGM3** [comment]
I had confused myself with the usual use case of `<liferay-ui:error />` and `<liferay-ui:success />` where the key used is generally what is sent as attributes to the request in `SessionMessages.add`, at least according to the [6.2 Docs](https://dev.liferay.com/develop/tutorials/-/knowledge_base/6-2/using-liferay-uisuccess-and-liferay-uierror-message). Will correct this issue, and send a new PR.

**Pull request closed without merging**
