### PR TITLE
[TECHNICAL-SUPPORT] LPS-70758

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo

Notes from Spencer:

> LPS : https://issues.liferay.com/browse/LPS-70758
> LPP : https://issues.liferay.com/browse/LPP-24273
> 
> When checking to display the main icon, navigation portlet, and search portlet, we add logic that allows them to display when the user is being impersonated.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@SpencerWoo While this seems like it might be a bug, the client's issue does not pertain to impersonation so I'm not sure if this fix will do anything for them. Would you mind clarifying whether or not this issue is necessary for the client or if we should investigate a different solution/different problem?

**Comment by jonathanmccann** [comment]
Nevermind, just saw the full conversation on the LPP.

**Comment by jonathanmccann** [comment]
Should this also be applied to these files as well?

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_normal.vm#L41

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-template/portal-template-velocity/src/main/resources/VM_liferay.vm#L65

**Comment by SpencerWoo** [comment]
Hi @jonathanmccann,

Thanks for the feedback.  I was looking at frontend-theme-classic as one theme, but looking at it now it seems the entire foundation/frontend-theme is one theme.  I will change the files you link / frontend-theme-unstyled and verify both velocity and freemarker templates resolve the issue.

Additionally, I was told it is okay to not fix the issue in every theme in the first PR.  Is this true, or should I also be looking to change the other themes (fjord, 1975 london)?

Thanks again!

**Comment by jonathanmccann** [comment]
Sounds good. I'll close this one out in the mean time then.

**Pull request closed without merging**
