### PR TITLE
LPS-70240

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-70240

### CODE REVIEW

**Comment by ChrisKian** [comment]
CC @ehan

**Comment by ChrisKian** [comment]
When I format, I get this message:
`(c): ./src/main/java/com/liferay/portal/security/ldap/internal/exportimport/LDAPImportContext.java`

Any idea what is wrong?

**Comment by jonathanmccann** [comment]
@ChrisKian You're missing the copyright at the top of the file.

**Comment by ChrisKian** [comment]
Resent with the issue fixed.  See https://github.com/jonathanmccann/liferay-portal/pull/1225

**Pull request closed without merging**
