### PR TITLE
Lps 54744 rebase

### PR DESCRIPTION
**Pull request by arbetts**
BChan asked me to rebase the pull for this, but the diffs were enough that I want to send it through the review process again.

if you can, please take a quick look and see if there is anything i missed, then maybe send it to Mate?

I didn't do a straight rebase because the number of SF commits was getting cumbersome. I squashed some of my commits to try and make it more readable.

Thanks!

https://github.com/brianchandotcom/liferay-portal/pull/28170

### CODE REVIEW

**Comment by arbetts** [comment]
Also... i'm unfamiliar with how we want to reference classes in the module framework so I initially moved a constants class and a display class into the module, but i couldn't compile because of portal dependencies. 

I did my best to guess where the files should end up, but Mate might want to move them.

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
Will look at test failures when I get in this morning

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Closing. If you still need to run tests, you can set up your account to do so and send the pull to yourself.

**Pull request closed without merging**
