### PR TITLE
[TECHNICAL-SUPPORT] lps-71118

### PR DESCRIPTION
**Pull request by SamZiemer**
Hey Jonathan,

When we have a plugin that has many include tags throughout all their jsps rather than using an init.jsp we look up duplicate requirements every time they appear, rather than saving already seen requirements.

This change adds a cache to the jspAnalyzerPlugin to avoid us processing the same requirements multiple times.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
These test failures look real. Let me try running it again.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1291

**Pull request closed without merging**
