### PR TITLE
[TECHNICAL-SUPPORT] LPS-69157

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman This test failure looks related. Please take a look at it and let me know.

**Comment by mbowerman** [comment]
@jonathanmccann Could you please clarify why you believe this test failure to be related? As far as I can tell, it just appears to be the result of a random connection error between the portal and the MBean server.

**Comment by jonathanmccann** [comment]
Well, it looks related because it is called "testUpgradeCreatesCalendarBookingRecurringId" which is very similar to the area that you are fixing. If you don't believe a test failure is due to your changes, you are free to reopen the pull and start the test over again to see if it passes or fails.

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
https://github.com/natocesarrego/liferay-portal/pull/50

**Pull request closed without merging**
