### PR TITLE
LPS-58240

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @ChrisKian,

Just curious, but why did you only make a field for the custom attributes and not for the regular mappings as well? I know a lot of the mappings are already spelled out in the UI, but want a reason to pass along.

Personally, I'm not a big fan of the change since the user should use either the UI or the portal properties, not both. I think that's how engineering will feel about it, but I don't mind passing it along, just need some more information and reasoning to the change.

Thanks!

**Comment by jonathanmccann** [comment]
Also, this seems more like a new feature according to LPS-42829 and LPS-43289, so why are we handling this as a bug now?

**Comment by ChrisKian** [comment]
Hey Jonathan,

I believe most of the non-custom mappings are already exposed.  And, I don't think it's as big of a deal because most clients would likely keep their default LDAP user object variable names the same.

I do agree with you this does seem more like a feature than a bug, however the amount of work required to create this fix was pretty small.  All the logic required was already present, I just had to un-hide the fields and give them names.

The reason I am exposing the custom mappings via the edit LDAP page is due to how limited the custom mapping are in portal properties.  As of now, the only way to add custom mappings to an LDAP configuration is to delete the LDAP server, configure the mappings through portal properties, restart LR, and re-add the LDAP server.

To clarify, updating the custom mappings in portal properties does not take affect for LDAP servers which have already been added to LR.  The "ldap.user.custom.mappings.0" property only applies to LDAP servers added after the property has been set.  With my change, this value is exposed and modifiable.  This essentially allows the portal property to be the default value unless the user changes it.  Therefore, no clashing between portal properties and control panel.

Another consideration is we are currently unable to define any differences in mappings between LDAP servers.  In order for a client to have multiple LDAP servers with different custom mappings, the client would need to update their portal properties with the mappings, restart LR, add their LDAP server, and then repeat that process for every LDAP server.

Ultimately, I trust your judgement, so let me know what you think.

Thanks!

**Comment by jonathanmccann** [comment]
Thanks for the response, Chris. I'll forward it along with your description and we'll see what they say.

Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/754

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/29825

**Pull request closed without merging**
