### PR TITLE
LPS-56462 Move PermissionCache clearing logic into model listeners

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Do we still need all of the other instances of PermissionCachceUtil.clearResource* that are not in the listener?

**Comment by Preston-Crary** [comment]
For the remaining ones we are either not using the persistence layer or are using the thread local to disable cache clearing while we do a bulk change.  So unfortunately, we still need those ones.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/1400

**Pull request closed without merging**
