### PR TITLE
LPS-62819

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mbowerman Will the condition "if (Validator.isNotNull(fileEntryLiveGroupId)) {" every be false or will "if (fileEntryLiveGroupId == GetterUtil.DEFAULT_LONG) {" ever be true? Looking over it, it doesn't seem like these checks are necessary, but please let me know.

**Comment by mbowerman** [comment]
For `if (Validator.isNotNull(fileEntryLiveGroupId))`, it doesn't look like it will ever be false. I'm not sure why I put that in there.

The reason I added `if (fileEntryLiveGroupId == GetterUtil.DEFAULT_LONG)` is because I thought that this import method could get called on importable files that had been generated with the old export method (in which case there wouldn't be a "file-entry-live-group-id" property, which would cause fileEntryLiveGroupId to be set to the default long value). For instance, if the remote staging bundle has not had this fix applied to it yet. Or if this method is called when importing a LAR (not sure if it is or not).

**Comment by jonathanmccann** [comment]
@mbowerman Thanks for the explanation. Also, please add a test to FileShortcutStagedModelDataHandlerTest that covers this new case.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/528

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1368

**Pull request closed without merging**
