### PR TITLE
LPS-78908

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @wanderlast 

From Lianne:

> LPS: https://issues.liferay.com/browse/LPS-78908
> LPP: https://issues.liferay.com/browse/LPP-29392
> 
> The fix is pretty self-explanatory, it replaces groupIds in document links to "[$groupId$]" on export and reverses that upon import with the new groupId. The addition of /documents/ in the find/replace value is to prevent it from catching a number in the portlet's content that coincidentally matches the groupId.

Also, I double checked to see what would happen in the event of linking to an image from a different site, and how it compares to doing the same with a web content (since Lianne's fix only cares about the current site).  Basically, with a web content, if we cannot find the reference, the import fails completely.  With the WYSIWYG portlet, the import succeeds, however there will be a broken link in the display, since it's trying to retrieve something it cannot find.   I think this is alright, given we cannot also export the content from a different site.

Let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
CI was taking a while on my branch.  I'll have it retest here, although there is likely no errors.

**Comment by ChrisKian** [comment]
ci:test

**Comment by jonathanmccann** [comment]
What is the reason for overriding deprecated methods? I haven't looked too deeply into it but it seems odd to me, especially since no other *PortletDataHandler overrides these methods.

**Comment by wanderlast** [comment]
Hi Jonathan,

My reason for using the deprecated methods was primarily due to the time and effort that would be required for an alternative fix versus the current state of the WYSIWYG portlet.

The WYSIWYG Portlet is theoretically only supposed to be used when the "full capabilities of Liferay's CMS system is not needed" and therefore doesn't really have any actual staging infrastructure within Liferay itself. Its content is stored and retrieved in its portlet preferences and everything else goes through the base/default classes. This means that following the normal import/export processes that other portlets use would require quite a few extra classes be written which is admittedly an outcome I wanted to avoid. This is especially in light of the fact that the WYSIWYG portlet is considered to be in its 'final version'. While we still do support it until its EOL (and I would judge this current behavior to be a bug), I'm not sure how valuable it'd be for me to implement most of the staging infrastructure for a portlet that is reaching its EOL.

Speaking more specifically about the method I used, most portlets, if not all, use an "ExportImportContentProcessor" for their processImportPortletPreferences method. Only if one can't be found does the code check for a portlet data handler and use the processImportPortletPreferences method in it. You can see this behavior at PortletImportControllerImpl from line 588-611, where the code would check to see if the WYSIWYG portlet has an ExportImportContentProcessor, find that it doesn't, and then go to the PortletDataHandler -> BasePortletDataHandler -> processImportPortletPreferences (which is the overriden deprecated method) -> doProcessImportPortletPreferences. The current solution in the PR simply substitutes the new WYSIWYGPortletDataHandler for BasePortletDataHandler. While I think it should be possible to create an ExportImportContentProcessor, it would have required extra work with regards to accounting for and writing code related to capabilities. This same logic applies to why I didn't use DLReferencesExportImportContentProcessor--WYSIWYG does not have a staged model and it would therefore require far more work to implement in comparison to the current fix.

If you feel like one of the other classes I mentioned above would be a better fix, please let me know and I'll look into it further. Thanks!

**Comment by jonathanmccann** [comment]
Thank you for that clear explanation, I will be sure to pass that along with the next pull request.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1980

**Pull request closed without merging**
