### PR TITLE
LPS-76248

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@fortunatomaldonado @mbowerman 

1. Why are we calling this method from the ```updateUser``` method? It seems like this is the default locale for the group, so I'm not sure why this should be triggered when updating the user. None of the changes are hit when I change the default locale from the Basic Configuration page, which is where I would expect the bug fix to occur.

2. Why are we looping here when we simply get the first value and then break? https://github.com/jonathanmccann/liferay-portal/pull/1480/files#diff-41dbbd5da040e2489fbe1cf6c13c5af8R1061

**Comment by fortunatomaldonado** [comment]
@jonathanmccann 
1. From my testing, I found that changing the locale in Basic Configuration page and clicking finish would result in the user and the default locale to be different. I may have missed a case where Liferay is started for the first time and so the default locale will be the locale picked by the user in Basic Configuration page and so this would not work. I believe Liferay always has English as default locale and so when picking a different locale will result in having different default and user locales. I can test to see if this is correct if you like and will let you know of my findings.

2. I did this to simply get the key of the nameMap since I did not want to hard code a locale for the key and then find out the locale is not included. 

I hope this makes sense. Any questions, comments, advice please let me know.
Thank you!

**Comment by jonathanmccann** [comment]
@fortunatomaldonado 

From my understanding, this mismatch (the actual bug) only happens one time during the initial set up. Is that the case or if you change the default locale afterwards via the control panel, do you still run into the same issue?

If that is the case, then we should simply update the group's default name at that point instead of tying it in with the user update. When a regular user is updated, the company's default locale is not going to be changing, so 99% of the time this update is not going to be necessary.

I'm thinking it might be good to place the call in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/setup/SetupWizardUtil.java#L107 since this seems to make the most sense.

Please let me know if I'm misunderstanding the issue or if you have any questions.

**Comment by fortunatomaldonado** [comment]
@jonathanmccann 

Yes, the mismatch only happens at set up. The only problem with calling UpdateGroupName in the setupWizard is that the user locale will still be the same as the default locale and so the nameMaps will not be updated.

I agree that this should not be called every time the user is being updated and so I can add an if statement so it only runs when the user and default locale are different. This way it will only have to execute once at set up. Let me know what you think.
Thank you!

**Comment by jonathanmccann** [comment]
Please review https://github.com/fortunatomaldonado/liferay-portal/pull/1

**Pull request closed without merging**
