### PR TITLE
[TECHNICAL-SUPPORT] LPS-70431

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo

Notes from Spencer:

> LPS : https://issues.liferay.com/browse/LPS-70431
> LPP : https://issues.liferay.com/browse/LPP-24204
> 
> The problem is that a NPE is thrown ("Form Text" has a null "values" section for ddmFormFieldValue). There are various places where a fix would work to avoid the NPE and give the proper functionality for this LPS.
> 
> I chose this file to have the fix because it is directly related to FormEmailNotification. The fix itself is checking whether ddmFormFieldValue.getValue() is null. If it exists we sb.append(render) naturally.
> 
> From what I can tell we don't use the fact that NPEs are thrown based on a null "values" section for functionality, but if it is then I should do the fix in another way or in another location.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @SpencerWoo, what is the purpose of looping over the available locales?

**Comment by SpencerWoo** [comment]
Hi @jonathanmccann 

I took the logic of https://github.com/liferay/liferay-portal/blob/b4ac010065e02101cbdf0aec885cf86e8e362609/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-validator/src/main/java/com/liferay/dynamic/data/mapping/validator/internal/DDMFormValuesValidatorImpl.java#L168-L180 as the proper Validator-esque way to validate a Value.

There they're validating the values of the Value, which admittedly probably isn't necessary for our case.  I don't believe methods are called on value.getString(locale) and I don't expect a NPE to be thrown from HtmlUtil.escape(null).

**Comment by jonathanmccann** [comment]
Got it. My initial thought was to simply check if the value for that locale is not null. If ```ddmFormFieldValue.getValue()``` is not null, does it automatically have a value for each locale? If so, then we can simply check for null on that instead.

**Comment by SpencerWoo** [comment]
I think you're right to only check if the value for the specific locale is not null.  ddmFormFieldValue.getValue() returns a map of its Locales and I'm uncertain if they're initialized with a value.
`if (ddmFormFieldValue.getValue() != null) {
if(Validator.isNull(value.getString(locale)){`

If we want we also don't really need to check the locale's values for this issue.  Even if they are null there doesn't seem to be any method calls based on the locale value and HtmlUtil.escape(null) doesn't throw an NPE.
`if (ddmFormFieldValue.getValue() != null) {`

**Comment by jonathanmccann** [comment]
Sounds good. Go ahead and put that fix together and send me a new pull. Thanks!

**Pull request closed without merging**
