### PR TITLE
LPS-58319

### PR DESCRIPTION
**Pull request by BryanEngler**
we do the same thing here https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/META-INF/resources/edit_record.jsp#L136

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Bryan,

Why are you using ddmStructure instead of recordSet? Also, be sure to link the LPP to the LPS.

Thanks.

**Comment by BryanEngler** [comment]
im using ddmStructure because thats what was originally being used to get the classPK, so i just extracted it out of the liferay-ddm:html tag so that we could set different values for the classPK. also, in a way it kind of is using the recordSet because its getting the ddmStructure from the recordSet in line 33

**Comment by jonathanmccann** [comment]
Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/766

**Pull request closed without merging**
