### PR TITLE
LPS-68309

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@BryanEngler @ChrisKian,

In the breaking commits on the LPS, it looks like the Folder object's also were displaying a description as well as the Files. Should that be fixed as well or has something changed in the mean time?

**Comment by ChrisKian** [comment]
Hey @jonathanmccann, 

I linked the wrong line of code, I meant to link https://github.com/liferay/liferay-portal/commit/dc0008ba98ca41d8b326310752d417e4a1098721#diff-e3592a02fa7985b1216042eadc48afcdL102

Anyways, I believe the same issue is likely happening for the folder as well.  Would you like to me to fix the issue and send you a new pull?

Thanks

**Comment by jonathanmccann** [comment]
That sounds good to me, thanks.

**Comment by ChrisKian** [comment]
See https://github.com/jonathanmccann/liferay-portal/pull/1070

**Pull request closed without merging**
