### PR TITLE
[Community Contribution] LPS-73604

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-73604

### CODE REVIEW

**Comment by holatuwol** [comment]
The code is mostly the same as from the original pull request, https://github.com/liferay/liferay-portal/pull/1689, but with localization changes removed, because the pull request is two years old and so a lot of the translations were probably updated.

I'm transitioning it through the regular community contribution workflow because there is a customer who asked about it (see [PTR-1126](https://issues.liferay.com/browse/PTR-1126)), so I thought we might as well move it forward and see where it goes.

To make it easier to apply, strip out all the language changes.

```bash
git show --name-only ceph~1..ceph | grep -vF Language_ | xargs git format-patch ceph~1..ceph --
sed -i.bak 's@/apps/foundation/@/apps/@g' *.patch
```

Add a line break to `@Meta.AD(description = "bucket-name-help", name = "bucket-name")` so that the closing parentheses exists on its own line, and make that a commit. This allows us to use `git am` to capture the generated `.patch` file.

Update the generated .patch file so that the Language.properties update for `s3-store-configuration-name` says "S3 Store" instead of "S3 Store Configuration". Combined with the change above, this will allow `git am` to apply the patch successfully.

```bash
ls -1 *.patch | sort -u | xargs git am
```

Run source formatter, make that another commit. Then squash all three commits together.

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8126

**Pull request closed without merging**
