### PR TITLE
LPS-79521 Implement New Search Method

### PR DESCRIPTION
**Pull request by brianikim**
Test Drive for CI:Test

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by brianikim** [comment]
ci:retest

**Comment by brianikim** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
It doesn't seem like a version increase is required. However, your autogenerated changes need to be in a separate commit. Please separate the changes and then forward it on to dacousalr. Thanks!

**Pull request closed without merging**
