### PR TITLE
LPS-70668

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-70668

Let me know if you have any questions

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @ChrisKian why did you choose to go with a listener instead of deleting this subscription when all the other subscriptions are deleted? I would assume you have the groupId there as well but I'm not sure.

**Comment by ChrisKian** [comment]
I tried to follow what blogs was doing because the situation was very similar.

Basically, the reason the subscription for the messageboard wasn't being deleted was because we set the classPK as the groupId in the subscription table when the category is the group default (0).  Because of this, there is no way to link the portlet to the subscription entry, so we have to do it through the group.  Blogs does the same exact thing across the board.  I believe this is because the portlet would be the same across the group (instantiated?).

See https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-service/src/main/java/com/liferay/blogs/internal/model/listener/GroupModelListener.java

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3797

**Pull request closed without merging**
