### PR TITLE
LPS-59031

### PR DESCRIPTION
**Pull request by BryanEngler**
From Preston:
"Please send through the UI team so they can assess if we need to update the server admin page from a UX perspective."

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@Preston-Crary This feature doesn't make much sense to me. If the user wants to only reindex certain assets then they can simply choose to reindex them one at a time. This feature would make much more sense as a portal property or something that could be saved and retrieved upon startup.

**Comment by Preston-Crary** [comment]
The idea behind this is if an admin needs to do something really heavy on the index, like staging or deleting a folder with 100k files in it.  They can disable the indexer for a particular asset and then re-enable it and reindex that asset without having to shutdown and set properties.

I agree we should also have unified properties to turn off indexers when the portal starts up.  If you want I can add the properties to this ticket as well - I was planning on doing that separately since we'll need to deprecate some properties.

**Comment by jonathanmccann** [comment]
I guess I still don't understand the use case because at some point, the asset will need to be reindexed so what is the benefit of deferring it?

I do think that this feature needs to have a way to be saved but I wasn't thinking just via portal properties because that will force the user to have to restart, like you said. However, before you implement that, I would confer with engineering first to see if this is something they want.

**Comment by jonathanmccann** [comment]
Also, does this enable / disable the indexer just in the Server Administration area or if you disable it then it disables it globally? If it's globally, I think that will open up many pitfalls and many people will start complaining that their search isn't returning correct results, etc because they forgot they disabled the indexer.

**Pull request closed without merging**
