### PR TITLE
[TECHNICAL-SUPPORT] LPS-70814

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

Notes from Alec:
> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-24318
> https://issues.liferay.com/browse/LPS-70814
> 
> The "Web Content" layout type was removed in DXP (apparently with [this technical task](https://issues.liferay.com/browse/LPS-54976)), and has been deprecated since 6.1. According to [our documentation on removed features here](https://grow.liferay.com/people/Removed+Feature+Support), the fact that it was deprecated in previous versions means that this counts as clear documentation for the purposes of its removal -- however, there should still be a way to handle previously existing layouts.
> 
> As it is now, after an upgrade to DXP with "Web Content" pages, the layout stays as an "article" type in the database (which is no longer a valid type), and so it ends up just being a blank page without customizations. From a user's perspective, the content appears to have gone "missing" (although it still exists in the site).
> 
> The change in this pull is to create an UpgradeProcess to convert the layout to a 1-column, "portlet" type with a Web Content display -- which looks very different, but at least keeps the content intact, so it does not appear to have gone missing (and the page can still serve its previous purpose, although it looks different). We have opted for this route since the message in 6.2 indicating its deprecation (shown in the [attached image](https://issues.liferay.com/secure/attachment/204650/deprecated.png) on the ticket) seems to indicate that this is the form that should be used to replace this old page type moving forward.
> 
> We are aware that this is probably the extent of the assistance we can offer to customers from support, but want to at least make sure that doing this minimizes the perceived user experience for upgrades where this feature may still have been used previously, despite its deprecation. Please let me know if there are any disagreements, suggestions, or improvements that should be made to this approach though. Thank you.
> 
> Also, please note that there appears to be an issue upgrading to master that complicated testing -- to work around this, I was forced to manually update the build number for portal in the "release_" table from 7010 to 7003 before starting up Liferay post-upgrade. I'm not sure what's causing this but it was necessary for testing this in master (testing in ee-7.0.x seemed to work fine).
> 
> Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@Alec-Shay,

With this, could we remove the following code?

https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/layout/layout-admin-web/src/main/resources/META-INF/resources/layout/details.jsp#L161

It looks like this is checking for layouts of type "article" but I'm not 100% sure.

**Comment by Alec-Shay** [comment]
@jonathanmccann 

I agree, that's what it seems to be doing and if this is implemented, then it won't be necessary. I haven't tested it myself, however -- I can do so if necessary.

**Comment by jonathanmccann** [comment]
Yes, please do. If it's obsolete, we should definitely remove it.

Also, if there is no "article-id", should we still continue with upgrading the layout?

https://github.com/jonathanmccann/liferay-portal/pull/1233/commits/6123c39893cc5c32ef8d226b465de153ce24e112#diff-804c039366512751c4d104e9b811651fR93

**Comment by Alec-Shay** [comment]
Alright, I will do that when I have a minute.

As for whether it should still be upgraded if there's no articleId... Well, initially I'd assumed so, but I guess it's hard to say really. I guess, if we really wanted to just upgrade all article layouts, we might want to just have an empty web content display -- but we didn't have any clear documentation for this upgrade path to begin with, so I'm totally just guessing for that use case.

**Comment by jonathanmccann** [comment]
Got it, that makes sense.

I'll leave this open, but if  you need to remove that code, feel free to send me a new pull.

**Comment by Alec-Shay** [comment]
Thanks. Will get back to you on that.

**Comment by Alec-Shay** [comment]
Re-sent with the change at: https://github.com/jonathanmccann/liferay-portal/pull/1235

**Pull request closed without merging**
