### PR TITLE
LPS-78493 - don't automatically capitalize the word 'this' in language keys

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Jonathan!

LPP: https://issues.liferay.com/browse/LPP-27641
LPS: https://issues.liferay.com/browse/LPS-78493

Currently the word 'this' is automatically capitalized when running buildlang. While in-line with general capitalization rules for titles, it's not necessarily a safe assumption that a language key with no punctuation at the end is a title. Material Design standards state that punctuation should, in fact, be avoided at the end of most lines. The fix I'm sending is simply removing the automatic capitalization.

Let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@wanderlast If we're going to push this forward, I would assume there are a number of language keys that would need to be regenerated since now they would have a lowercase "this", right?

**Comment by wanderlast** [comment]
@jonathanmccann I don't believe so, but I may be misunderstanding how it works. As far as I'm understanding, looking at langbuilder, this change should affect keys in the following ways:

1. Pre-existing keys are not affected, their contents remain the same (This stays This, this stays this).
2. New keys that contain the word "this" keep that capitalization regardless of punctuation.
3. New keys that contain the word "This" keep that capitalization regardless of punctuation.

**Comment by wanderlast** [comment]
ci:reopen

**Comment by wanderlast** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
If the pre-existing keys aren't changed, won't the client raise a concern about those since they don't conform to their standards?

I also spoke with Angelo and we want to wait for a final response on the PTR before pushing this forward.

**Comment by wanderlast** [comment]
I'm personally uncertain if the client cares about the old keys. The issue has always been in relation to creating new keys, so I'm uncertain if they're simply choosing to not use them/rewrite them anyway.

Ok, thanks for the information!

**Comment by wanderlast** [comment]
ci:close

**Comment by wanderlast** [comment]
Resent here: #1562

**Pull request closed without merging**
