### PR TITLE
LPS-48992

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/23957

**Comment by jonathanmccann** [comment]
Hey @brianchandotcom @sergiogonzalez 

The test DLFileEntryLocalServiceTest#testDeleteFileEntriesIteration was added before DLFileEntryLocalServiceImpl#deleteFileEntries was converted to use a dynamic query. Like Sergio said, the interval action was introduced to encapsulate the logic of methods that could not leverage a dynamic query.

If you want I can remove DLFileEntryLocalServiceTest#testDeleteFileEntriesIteration so that the test is consistent with the Service method.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/2204

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/2208

**Pull request closed without merging**
