### PR TITLE
LPS-76299

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Question from Preston:

"does deploying portal/modules/apps/foundation/portal-osgi-debug/portal-osgi-debug-declarative-service not log the problem?"

@mbowerman @fortunatomaldonado

**Comment by fortunatomaldonado** [comment]
@jonathanmccann 
 It does, but when problems like this occurs, most customers do not know of this process and so they waste time debugging and troubleshooting the problem. If they do know how to deploy this service, the log message it displays only tells them that there is an error but does not provide useful information of why the service is failing. This fix is suppose to make it easier for customers by logging the problem on start up without them having to do anything and specifying why the service fails. Let me know if more information is needed.

**Comment by jonathanmccann** [comment]
After speaking with Preston, we should investigate making the logging better in the declarative service module since this type of logging will hurt start up performance and in a production environment clients should not be running into these issues. This logging is useful for development only that is why the declarative services module is not deployed by default.

**Comment by fortunatomaldonado** [comment]
Okay that makes sense. Thank you for the information!

**Pull request closed without merging**
