### PR TITLE
LPS-57240

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ChrisKian @BryanEngler 

A couple of questions:

1. Why are we making isPasswordModifiable public instead of a protected method, since it's only used in UserLocalServiceImpl?
2. Why are we trying to get the LDAP context? Seems like a lot of overhead when we could simply return based on the user's LDAP server ID.

**Comment by ChrisKian** [comment]
@jonathanmccann 

1.  I originally had the isPasswordModifiable method being called from password.jsp.  When I moved the logic into UserLocalServiceImpl, I must have overlooked changing it to protected.

2.  The reason for getting the LDAP context is in case the user is no longer part of said LDAP.  If we were to import a user from the LDAP, then remove or disable that LDAP server, the ldapServerId field in the user object would still be populated, but the LDAP server it is referencing would be null.  Getting the context ensures an active LDAP server, otherwise we should treat that user like one created through the portal (or at least that is what I think would be best).

**Comment by jonathanmccann** [comment]
For 2, what is the LDAP server is having connection issues at the time the password is being changed? Then the user's password will be modified and we still have the same problem. I think we need a solid way of determining whether or not the user is from LDAP. Looking at UserGroup, there is a column named "addedByLDAPImport" and it doesn't look like we reset that if the user takes down the LDAP server. Let me know what you think.

**Comment by ChrisKian** [comment]
I never thought about a hiccup in the LDAP server.  So you're suggesting if we were to remove the LDAP server, we need to update the UserGroup "addedByLDAPImport" to false, then check on this value rather than retrieving the  ldapContext?  I think that's a good idea; I will work on it.

**Comment by jonathanmccann** [comment]
I think that setting the UserGroup's attribute to false would be interesting, but we'd have to set the User's ldapServerId back to -1 and then we can just check against that. Updating the UserGroup as well would just be an added bonus. However, I'm not sure of the implications of this (disabling and reenabling a server, deleting a server permanently, using two LDAP servers and only disabling the first one, etc). Let me know if you have any questions or run into any issues. I'll close this pull in the mean time.

**Pull request closed without merging**
