### PR TITLE
LPS-103270

### PR DESCRIPTION
**Pull request by brianikim**
Redirected from : https://github.com/SamZiemer/liferay-portal/pull/677 as requested by @SamZiemer

P.S.: This PR is low priority

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@brianikim @katienesterovich 

If we are adding a new class `AssetAutoTaggerSystemConfigurationModelListener` do we still need to validate the system's configuration within the company scoped listener?

Also, shouldn't we have the same validation logic in the system listener as the company one? As it stands it seems we could have `0` for the value in system but not in company, if I'm reading it correctly.

**Comment by katienesterovich** [comment]
> Shouldn't we have the same validation logic in the system listener as the company one? As it stands it seems we could have 0 for the value in system but not in company

The existing logic prevents the user from allowing more tags in the company scope than in the system scope. 0 means that the scope is unlimited - i.e. If system max == 0/unlimited, our company scope has to be 0/unlimited, too.

**Comment by jonathanmccann** [comment]
Thank you for that explanation. I think the only issue I see now is that you are able to set the company value to 0 and then the system value to 1. With this you're technically in an invalid configuration and won't be able to save the company settings without changing the value. That could be looked at under a different LPS though.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adolfo for further review: https://github.com/adolfopa/liferay-portal/pull/1129

**Comment by katienesterovich** [comment]
Great catch - you're right, I've only considered configurations being set in the System > Company order. We don't have a validator in place for System checks once the Company max has been set. Would you like me to file an LPS ticket?

**Comment by jonathanmccann** [comment]
Yes please, thank you.

**Pull request closed without merging**
