### PR TITLE
[TECHNICAL-SUPPORT] LPS-73061

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
Reviewed and sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/655

**Pull request closed without merging**
