### PR TITLE
Lps 98371b

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-98371

Updated from https://github.com/jbalsas/liferay-portal/pull/1827#pullrequestreview-266858716

> please see my comment about inlining svgs in code to verify if that addresses your issue as well.

> After that, please resend to the appropriate person in the forms team. Maybe jeyvison? :)

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@SpencerWoo Can you push up the needed source formatting changes? Thanks.

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jeyvison for further review: https://github.com/jeyvison/liferay-portal/pull/552

**Pull request closed without merging**
