### PR TITLE
LPS-87024 Added asterisk and removed Disable checkbox when DDM Date i…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…s required.

https://issues.liferay.com/browse/LPS-87024

Resent from https://github.com/gregory-bretall/liferay-portal/pull/128

Test Results: https://github.com/SpencerWoo/liferay-portal/pull/30#issuecomment-444213644

@noemi-zamarripa

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Why is
```
if (required) {
	showDisableCheckbox = false;
}
```
necessary? I would assume the check later on suffices:
```
<c:if test="<%= nullable && !required && showDisableCheckbox %>">
```

**Comment by noemi-zamarripa** [comment]
The c:if test does not suffice in this case because the showDisableCheckbox property, by default, is set to true. So even if the check is done, there is never any logic to denote that the box should not be displayed if required is set to true by the user.

**Comment by jonathanmccann** [comment]
Yes, but all three of those conditions are &&'d together so if one of them is `false` then the entire check fails. In this case, `required` is set to true so the `if` statement should return `false` and the body is not executed.

If I'm still not understanding please feel free to come over and talk through it with me.

**Comment by noemi-zamarripa** [comment]
My mistake, you are correct. That bit of code can be removed then.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jeyvison for further review: https://github.com/jeyvison/liferay-portal/pull/165

**Pull request closed without merging**
