### PR TITLE
LPS-53865

### PR DESCRIPTION
**Pull request by holatuwol**
Please see: https://issues.liferay.com/browse/LPS-53865

### CODE REVIEW

**Comment by holatuwol** [comment]
Not including site-scoped permissions at this time because of some complexities involving site/organization hierarchies that are handled in-code rather than built up to be cached.

**Comment by jonathanmccann** [comment]
Hey MCD,

You said that you're storing on portal-wide roles in the UserPermissionCheckerBag, but is there a possibility for RoleLocalServiceImpl.hasUserRole to be called for a site role? If so, then wouldn't "userPermissionCheckerBag.hasUserRole(role)" always return false?

**Comment by holatuwol** [comment]
Yes, but that's how Liferay behaved before as it's only being called for company-scoped roles.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/726

**Pull request closed without merging**
