### PR TITLE
LPS-58435 Show both the resource and the name in the title

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Please follow the logic/pattern set forth in javascript.js:

```
getCalendarName: function(name, calendarResourceName) {
	var instance = this;

	if (name !== calendarResourceName) {
		name = [calendarResourceName, STR_DASH, name].join(STR_SPACE);
	}

	return name;
}
```

**Comment by jonathanmccann** [comment]
Also, be sure to not chain together methods:

```
calendar.getCalendarResource().getName(locale)
```

**Comment by SamZiemer** [comment]
I have updated the pull as requested

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adam for further review: https://github.com/brandizzi/liferay-portal/pull/31

**Pull request closed without merging**
