### PR TITLE
[TECHNICAL-SUPPORT] LPS-68107

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @ericyanLr

Notes from Eric:

> Original LPP Ticket: LPP-22465
> 
> I am sending you two pull requests for these LPS Tickets:
> 
> LPS-68107
> LPS-68110
> They are both for the same LPP Ticket above.
> The two LPS Tickets are related, but do not depend on one another.
> I sent them together to hopefully make it easier for review.
> 
> Please let me know if you have any questions.
> Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ericyanLr Should one of the commits be for LPS-68110 or are they both for LPS-68107 and happen to resolve LPS-68110 as well?

**Comment by jonathanmccann** [comment]
Nevermind, I see Sam broke it up into two pulls.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3469

**Comment by ericyanLr** [comment]
Yep, two pull requests for the same LPP.

**Pull request closed without merging**
