### PR TITLE
LPS-90129 remove HTML escape

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-90129

@ryannealeigh1 

> Is there a reason we aren't also changing the other escapes?

> I looked into this and even if you put newlines in the title field of the Web Content, the same error does not occur, so it is unnecessary to remove those escapes. I also just tested using other special characters and there are no issues.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
I agree that this would reintroduce the XSS issue. Please take another look at this issue keeping in mind that possibility.

**Comment by ryannealeigh1** [comment]
@jkappler @jonathanmccann I do not believe that this will cause a regression as assetRenderer.getSummary() calls this [HtmlImpl.stripHtml](https://github.com/liferay/liferay-portal/blob/3b9b23556f5658a5d9ceabf40809b5aadb136059/portal-impl/src/com/liferay/portal/util/HtmlImpl.java#L696-L744), essentially creating a double escape situation. I'm not sure the best step forward though. Maybe the assetRender.getSummary() implementation should be changed to remove this stripHtml() call.

**Comment by ryannealeigh1** [comment]
@jkappler @jonathanmccann I followed the reproduction steps [here](https://issues.liferay.com/browse/LPS-71236) and could not reproduce even without the HtmlUtil.escape() call in place due to anything between angle bracket <> tags being stripped by stripHtml()

**Pull request closed without merging**
