### PR TITLE
LPS-93851 Avoid removing FieldSettings

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-96425

When creating a form, the `FieldSettings` are being checked for repeatable context and are removed in `_removeFieldContexts` which is causing issues while creating a form.

To prevent this, we check if `columnFieldContext.fieldName` can be found in the `FieldSettings` and we can skip it in the remove process.
Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@fortunatomaldonado Is LPS-93851 the correct LPS? I'm showing that one as Closed already so we should avoid committing against it.

**Comment by fortunatomaldonado** [comment]
@jonathanmccann,

I apologize, I wrote the wrong LPS on the ticket. I will adjust the fix right now.

**Comment by fortunatomaldonado** [comment]
I forced-pushed the updated commit. Let me know if I should send a new PR.
Thank you.

**Comment by jonathanmccann** [comment]
That should be fine, thanks. I'll pass this along shortly.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jeyvison for further review: https://github.com/jeyvison/liferay-portal/pull/418

**Pull request closed without merging**
