### PR TITLE
Lps 78980

### PR DESCRIPTION
**Pull request by gregory-bretall**
https://issues.liferay.com/browse/LPS-78980

Please note that we currently have an SME Request open related to this issue to determine the correct behavior in relations to Site Member permissions. See https://issues.liferay.com/browse/LPP-29466

The idea behind the change is to move the preparePortlet and scopeGroupId/siteGroupId reset logic out of render_portlet.jsp and LayoutAction so that the id's get properly reset when navigating to a page with a different scope.

Let me know if you have any questions.

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Shouldn't we wait for the SME to respond or is the request different from what is being fixed here?

**Comment by gregory-bretall** [comment]
The question is different than what is being fixed here. What this is fixing is the incorrect scopeGroupId causing permissions to not be correct. The SME Request is about how we should handle permissions that no longer appear for a given portlet's scope.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/5871

**Pull request closed without merging**
