### PR TITLE
[TECHNICAL-SUPPORT] LPS-74454

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-74454
> https://issues.liferay.com/browse/LPP-26631
> 
> Deleting an instance or multiple instances (with Following option) of a recurring calendar booking will now notify participants.
> The children of the calendar event were found through different logic than what deletes the events because changing the deleteCalendarBooking method [here](https://github.com/liferay/liferay-portal/blob/3244e1d8430abffb737ad6aeeac50749cbce8faf/modules/apps/forms-and-workflow/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L516) and elsewhere would create cascade of changes to the portlet.
> Originally I found that the best pattern to follow would be: 
> -Users aren't notified if the deleted event is in the past.
> -User is notified with Deleted template if 1 occurrence is deleted
> -User is notified with Updated template if multiple occurrences are deleted
> However, our framework doesn't have the supporting methods necessary to easily implement this. In particular calendarBooking.getStartTime() is not updated when the first event in a recurring series is deleted. As such, I just to the Delete Notification Template when a user deletes 1 or more instances of a Calendar Booking. This breaks with the implementation a little, but it doesn't seem worth the effort to follow it perfectly in this case.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @joshuacords this looks good. The only thing is that for the public methods where you changed their parameters, they need to be left in tact, deprecated, and point to the newer implementation. That way, if someone was using the old API, it's still available but will be removed at a later point.

Once that is done, please send the pull through to natocesarrego for review.

**Comment by joshuacords** [comment]
Hello @jonathanmccann, 
How should I setup the logic when the old method signature is used (which does not pass in the user who deleted the CalendarBooking)? Should I not send notifications in that case? Should I send notification from the user who created the CalendarBooking? Or should I do something else?

**Comment by jonathanmccann** [comment]
Sorry, I didn't fully think about the situation.

In that case, we'll do a "with no direct replacement" deprecation where we blank out body of the method. If you search for that text, you'll find examples of where we did this.

**Comment by joshuacords** [comment]
@jonathanmccann, thanks

**Comment by jonathanmccann** [comment]
@joshuacords These test failures seem related as well. Seems like the Calendar tests are failing to compile.

**Comment by joshuacords** [comment]
I see, I'll take a look at it Tuesday.

**Comment by joshuacords** [comment]
Continued here: https://github.com/jonathanmccann/liferay-portal/pull/1409

**Pull request closed without merging**
