### PR TITLE
Lps 54744 pr 17

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
we need to add line 73 to the source formatter exceptions... see the commits under LPS-54638 for details

**Comment by arbetts** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mike for further review: https://github.com/mhan810/liferay-portal/pull/453

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1014

**Pull request closed without merging**
