### PR TITLE
Lps 59212

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
plugins pr https://github.com/BryanEngler/liferay-plugins/pull/3

**Comment by jonathanmccann** [comment]
Ah, sorry, I thought the plugins were failing the test as well. I'll remove the commit since it's not necessary, thanks for letting me know.

**Comment by jonathanmccann** [comment]
Holding off on this until I have the plugins pull as well.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1025

**Pull request closed without merging**
