### PR TITLE
[TECHNICAL-SUPPORT] LPS-70065

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo

Notes from Spencer:

> Ticket : https://issues.liferay.com/browse/LPS-70065
> 
> When a currentURL is not passed a currentURL is generated to be used as backURL.  The generated currentURL redirects to the distorted CSS page.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@SpencerWoo based on your comment on the LPS, I assume this fix is no longer necessary?

**Comment by SpencerWoo** [comment]
@jonathanmccann I believe this fix is no longer necessary.  

The "cancel" button (when configuring site pages) now simply redirects to the pageURLs instead of creating a backURL / having back button functionality.

**Comment by jonathanmccann** [comment]
Ok. I'll close this pull. Go ahead and close out the LPS as well since it's not needed.

**Pull request closed without merging**
