### PR TITLE
[TECHNICAL-SUPPORT] LPS-69679

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @NolanChan 

Notes from Nolan:

> Commit msg: Liferay no longer throws exception when unused class annotation is not included in portlet
> 
> clazz.getAnnotation() causes an error to be thrown for portlets that don't include all relevant classes that have annotation references in their files. Customer portlets are breaking because of this issue, and so we included clazz.getAnnotation() in a try/catch to escape before the error could be thrown.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@NolanChan,

I'm a bit iffy on how this all works, so please forgive me if I'm not understanding correctly.

Looking at the fix, you're asking to get any and all annotations, but the only ones we care about are WebServlet, WebFilter, and WebListener. What happens if there is an annotation that isn't one of those three? Will we still run into the same error? Also, what if it has WebServlet but not WebFilter, wouldn't that result in the same issue?

**Comment by NolanChan** [comment]
Hi Jon,

Thanks for the questions. clazz.getAnnotations() and clazz.getAnnotation(some class) share the same underlying code `annotationData().annotations`. That means that the annotations are compiled regardless of what action we're trying to perform. This is the step that errors out in the process, so clazz.getAnnotations() should discover early one whether or not there are viable annotations included in the portlet. Please let me know if this is unclear, I'm still trying to understand annotations myself

**Comment by jonathanmccann** [comment]
Hey @NolanChan,

Thanks for the response. I'm still curious about why this is failing in this particular case and not in others. Debugging through the code, many different classes come through this code with no annotations but no NPE is thrown. Do you know why the client's particular WAR is throwing the NPE? It could be an issue with their implementation and not ours.

Also, I'm wondering why ```clazz.getAnnotations()``` does not throw an NPE but ```clazz.getAnnotation(WebServlet.class)``` does. Like you said, the underlying code is the same, so I would assume both would throw an NPE.

Finally, if you want to give what I said a test, it seems the annotations are method annotations - http://stackoverflow.com/questions/6535676/webservlet-annotation-with-tomcat-7

**Comment by NolanChan** [comment]
Hi @jonathanmccann 

The first case that this portlet fails on is when it is looking up the annotations for `interface org.springframework.ldap.repository.config.EnableLdapRepositories`. The customer has a bunch of Spring jars in their WEB-INF/lib folder that probably have requirements (the suspect ones are named spring-ldap*.jars). I would guesstimate that Liferay doesn't contain the necessary classes for the annotations. 

These stackoverflow questions seem to reflect the need to add more dependancies when an `ArrayStoreException` comes up:
http://stackoverflow.com/questions/25857126/spring-boot-requestmappinghandlermapping-java-lang-arraystoreexception
http://stackoverflow.com/questions/24352967/spring-boot-errorjava-lang-arraystoreexception-sun-reflect-annotation-typenotp

I'm also confused when you wrote 

> "clazz.getAnnotations() does not throw an NPE but clazz.getAnnotation(WebServlet.class) does."

 In my testing, the two always fail at the same time, which is why I used them interchangeably.

**Comment by jonathanmccann** [comment]
If you say:

>In my testing, the two always fail at the same time, which is why I used them interchangeably.

Then your fix still throws an exception, but this time it is caught and the message is logged instead of bubbling up?

**Comment by NolanChan** [comment]
Hi Jon,

I believe you're correct. The exception is still thrown (since the class dependency doesn't exist in Liferay) but we catch it instead of letting it cause the "catastrophic error"

**Comment by jonathanmccann** [comment]
Got it. I thought that the fix was checking to see whether or not there were any annotations, but the fix really lies in triggering the exception and catching it instead of allowing it to trickle up to the caller.

Still not sure about this fix, but we'll see what Engineering has to say about it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1269

**Pull request closed without merging**
