### PR TITLE
LPS-81901 set configuration scope

### PR DESCRIPTION
**Pull request by gregory-bretall**
Test results here: https://github.com/gregory-bretall/liferay-portal/pull/80#issuecomment-395593172
https://issues.liferay.com/browse/LPS-81901

Resent from https://github.com/gregory-bretall/liferay-portal/pull/80

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@gregory-bretall @SpencerWoo Please fix the source formatting errors and then forward on to topolik.

**Comment by SpencerWoo** [comment]
@jonathanmccann I'm not aware of any SF errors here.  Should I still forward this to topolik?

**Comment by jonathanmccann** [comment]
```
Wed Jun 13 11:10:17: ~/repositories/liferay-portal/portal-impl (pull-request-1641-LPS-81901) $ fsc
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
Buildfile: /home/jonathan/repositories/liferay-portal/portal-impl/build.xml
   [delete] Deleting: /home/jonathan/repositories/liferay-portal/null1527840432.properties

format-source-current-branch:
   [delete] Deleting: /home/jonathan/repositories/liferay-portal/null1527840432.properties

format-source-all:
     [echo] 
     [echo] Please run the following command from /home/jonathan/repositories/liferay-portal/modules to show status updates during the Source Formatter execution:
     [echo] 
     [echo] ../gradlew -b util.gradle formatSourceCurrentBranch
     [echo] 				
     [java] Loading file:/home/jonathan/repositories/liferay-portal/portal-impl/classes/system.properties
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/home/jonathan/repositories/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/home/jonathan/repositories/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
     [java] > 80: ./modules/apps/portal-security-sso/portal-security-sso-google-api/src/main/java/com/liferay/portal/security/sso/google/configuration/GoogleAuthorizationConfiguration.java 24 (SourceCheck:JavaLongLinesCheck)
     [java] > 80: ./modules/apps/portal-security-sso/portal-security-sso-ntlm-api/src/main/java/com/liferay/portal/security/sso/ntlm/configuration/NtlmConfiguration.java 32 (SourceCheck:JavaLongLinesCheck)
     [java] > 80: ./modules/apps/portal-security-sso/portal-security-sso-openid-api/src/main/java/com/liferay/portal/security/sso/openid/configuration/OpenIdConfiguration.java 32 (SourceCheck:JavaLongLinesCheck)
     [java] > 80: ./modules/apps/portal-security-sso/portal-security-sso-facebook-connect-api/src/main/java/com/liferay/portal/security/sso/facebook/connect/configuration/FacebookConnectConfiguration.java 24 (SourceCheck:JavaLongLinesCheck)
     [java] > 80: ./modules/apps/portal-security-sso/portal-security-sso-opensso-api/src/main/java/com/liferay/portal/security/sso/opensso/configuration/OpenSSOConfiguration.java 32 (SourceCheck:JavaLongLinesCheck)
     [echo] 
     [echo] This target does not format .es.js files. Please run the following command from /home/jonathan/repositories/liferay-portal/modules to do so:
     [echo] 
     [echo] ../gradlew npmRunFormat
     [echo] 				

BUILD SUCCESSFUL
Total time: 15 seconds
```

**Comment by jonathanmccann** [comment]
Your changes are going over the 80 character limit as noted in the output above.

**Comment by SpencerWoo** [comment]
ah thanks!  Will fix

**Pull request closed without merging**
