### PR TITLE
Lps 54821 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Jonathan,

I have been in discussion with Julio and Eduardo regarding this issue. In order to resolve this issue for master the plan is to move the logic from the 6_0_0 upgrade process to the 7_0_0 upgrade process. For 6.2 and 6.1, we will return this logic to the verify process. Let me know if you have any questions.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Also be sure to add Master as the affects version on this one as well.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3729

**Pull request closed without merging**
