### PR TITLE
Lps 79998 pr

### PR DESCRIPTION
**Pull request by gregory-bretall**
https://issues.liferay.com/browse/LPS-79998

Changes explained here: https://github.com/gregory-bretall/liferay-portal/pull/79#issue-192775850

Test results here: https://github.com/gregory-bretall/liferay-portal/pull/79#issuecomment-394822203

Reason why changes to https://github.com/jonathanmccann/liferay-portal/commit/64bf6272f99b7304e6937232f6f40a2349dcbbbd are different is because of an issue where in normal use the break lines are added to the editor before the image is added. Feel free to let @fortunatomaldonado know if you want this to be looked further into

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@gregory-bretall @fortunatomaldonado For the future, there's no need to reassign the LPP to the reviewer.

I made some changes as well, please review them and if you agree then forward the pull on to Sergio.

https://github.com/fortunatomaldonado/liferay-portal/pull/2

**Comment by fortunatomaldonado** [comment]
@jonathanmccann, 
Thank you for the information as well as refining the code. Unfortunately, we need to have two lineBreak elements since an element can not be at two locations at once. So inserting the same element twice is not adding two elements but placing the element in a new location. I do like the simplification of [editor_image_uploader](https://github.com/fortunatomaldonado/liferay-portal/pull/2/commits/a2733d9348fb64161b1394393e42ede9c1400d9f#diff-2fe509829dbf76cb8f8457e05c944683R209) and will add it to the fix. 
If there is no other feedback I will send out a pull to Sergio.
Thank you for your help!

**Comment by jonathanmccann** [comment]
Sounds good to me. Be sure to include that tidbit so that Sergio doesn't try the same thing as I did.

**Comment by fortunatomaldonado** [comment]
https://github.com/sergiogonzalez/liferay-portal/pull/4479

**Pull request closed without merging**
