### PR TITLE
[TECHNICAL-SUPPORT]

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo

Notes from Spencer:

> https://issues.liferay.com/browse/LPS-72290
> 
> Implements frontend validation to reject empty polls before submission (based on Web Form Portlet) and should prevent Poll NoSuchChoiceExceptions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ericyanlr I know you recently worked on an issue with screen readers not being able to see hidden divs. Would the same issue arise with this code or is it safe?

**Comment by ericyanLr** [comment]
Hi @jonathanmccann,

Yes, I believe the same issue would arise.  Hiding/showing elements by changing css does not work for many screen readers, such as JAWS screen reader.

The easiest fix seems to be to use the `<aui:validator/>` tag.

**Comment by jonathanmccann** [comment]
Thanks @ericyanLr. @SpencerWoo could you please work with Eric or take a look at his fix and revamp yours a bit so that we can play well with screen readers?

**Comment by SpencerWoo** [comment]
@jonathanmccann Okay thanks, I'll work with @ericyanLr

**Pull request closed without merging**
