### PR TITLE
LPS-56075

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
This test is failing on other pulls as well.

**Comment by jonathanmccann** [comment]
1. Do we need "_organizations" and "_roles" in the test?
2. Can we return immediately if the user is an admin in SearchPermissionCheckerImpl.doGetPermissionFilter?

**Comment by jonathanmccann** [comment]
Rename chileClauses in Test.

**Comment by Preston-Crary** [comment]
1. Removed "_organizations" and "_roles" from test and replaced with manual tearDown method.
2. Returned before populate method in the case where the user is an admin.
3. Removed chile clauses method and replaced it with a much better TestFilterVisitor inner class.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/1561

**Comment by jonathanmccann** [comment]
Reviewed and sent to Hugo for further review: https://github.com/hhuijser/liferay-portal/pull/2427

**Pull request closed without merging**
