### PR TITLE
LPS-70705 Add class container to modal content

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by carloslancha** [comment]
Hey @jonathanmccann It's ok to remove the max-width: 900px stuff but in order to follow lexicon patterns we need to use a container to limit the width of the preview.

Thanks!

cc @marcoscv

**Comment by jonathanmccann** [comment]
@carloslancha Thanks for taking a look!

@joshuacords Can you please test the updated fix to confirm the issue is still resolved?

**Comment by joshuacords** [comment]
@jonathanmccann Tested it and the issue is resolved.

**Comment by jonathanmccann** [comment]
@joshuacords Thanks for testing!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/47127

**Pull request closed without merging**
