### PR TITLE
LPS-70168 Revert

### PR DESCRIPTION
**Pull request by sergiogonzalez**
See comment in https://github.com/sergiogonzalez/liferay-portal/pull/3739#issuecomment-275630640

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman If you're good with this, I'll send it up to Brian.

**Comment by mbowerman** [comment]
@jonathanmccann I'm not sure I'm OK with that SF change. He replaced "IS NULL" with "is null". Did he test it after he did that? In my testing, "is null" would get reworded to "= null", which would cause the SQL not to return the correct results. However, "IS NULL" would get correctly interpreted by the SQLTransformer, and would be left alone. I'm OK with the Validator and the jsp change, however.

**Comment by jonathanmccann** [comment]
Good catch. Do you agree @sergiogonzalez?

**Comment by mbowerman** [comment]
Although in looking at the SQLTransformer and CustomSQL, I can't actually find any evidence that what I said is true (unless if it was the MySQL driver that was doing the transformation). And moreover, we appear to use "is null" in other Upgrade processes (for instance, https://github.com/liferay/liferay-portal-ee/blob/ee-7.0.x/portal-impl/src/com/liferay/portal/upgrade/v6_0_12_to_6_1_0/UpgradeUserName.java#L51). Let me do some more testing and get back to you guys.

**Comment by mbowerman** [comment]
Hey @jonathanmccann, @sergiogonzalez, you guys can push this up to Brian. I'm not really sure what I was seeing before, but my testing indicates that this query is working fine now.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/46455

**Comment by sergiogonzalez** [comment]
Hey @mbowerman @jonathanmccann sorry for jumping in late. I did that change because we tend to use lower case and after a quick search I found out lots of usages with `is null` in lower case so it should be fine.
Thanks!

**Pull request closed without merging**
