### PR TITLE
LPS-75593 After session timeout Social Ratings notifies user to sign in

### PR DESCRIPTION
**Pull request by ericyanLr**
Related Tickets:
[LPP-27545](https://issues.liferay.com/browse/LPP-27545)
[LPP-75593](https://issues.liferay.com/browse/LPP-75593)

Hi @jonathanmccann,

For this pr, we weren't sure if we're supposed to generate the language files.

Please let us know if there's anything we need to add/change.
Thanks!

Notes from @fortunatomaldonado:

> When the session times out and the user tries to rate a thread, the output will print "NaN". This is because the user does not have permission to leave a rating without being signed in.
> 
> The fix for this was checking when we receive the "NaN", which indicates the user is signed out, and graying out the rating icons. The user will no longer be able to click on the icons, but can see a tool tip stating to log in.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/1797

**Comment by jonathanmccann** [comment]
@fortunatomaldonado @ericyanLr Please see my changed.

**Comment by fortunatomaldonado** [comment]
@jonathanmccann Thank you for the help!

**Pull request closed without merging**
