### PR TITLE
LPS-55161

### PR DESCRIPTION
**Pull request by jgok**
Hi Jon,

This is a PR for LPS-55161. After talking with Minhchau, the previous fix that I provided did not actually solve the memory issue, so he recommended that we change the storage in PortalPreferences from xml to JSON. 

Also, let me know if this fix would be suitable as an SDH.

Thanks,
Josh

### CODE REVIEW

**Comment by jgok** [comment]
ci:retest

**Comment by jgok** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Josh,

Wouldn't we have to upgrade the old preferences so that they're not lost or are you just trying to upgrade them lazily?

Thanks.

**Comment by jonathanmccann** [comment]
Couple of things:

1. Upgrade the old preferences via an upgrade process like we discussed
2. "ATTRIBUTE_MAP" should be a constant instead of a string literal and should also describe what attributes it's holding, not just a generic name
3. Squash all your source formatting commits together
4. Not sure if that's the best way to see if an object is within the JSON but it seems a little clunky to me

Thanks!

**Pull request closed without merging**
