### PR TITLE
LPS-52763

### PR DESCRIPTION
**Pull request by BryanEngler**
so basically the goal of this fix is to list all of the assets in the manual configuration of the AP that are in the 'assetEntryXml' portlet preference. to do that we basically ignore all of the filtering by permissions, visibility, and statuses when getting the assets and their renderer. 

i actually wrote the fix on 62x since i couldnt test on master, so this is just a forward port of that. https://github.com/BryanEngler/liferay-portal-ee/commit/741a3ecacb5901641289548e3e8ae338c25ea4e9

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey Bryan,

I don't think we can just remove the permission check because while it'll make all of the assets show up in the configuration window, if the user cannot view it then they will be confused when they look at the portlet and that asset is no longer there. Also, this may show privileged assets (at least their title) to users who shouldn't be able to see them.

**Comment by BryanEngler** [comment]
pushed new changes... this one still checks for view permissions (when journal.article.view.permission.check.enabled=true)

although if a user has permission to configure the AP, but doesnt have permission to view already selected articles, this will still be "broken" because we have to way to handle a situation where you need to "sort things you cant see"... which is kind of why i ignored permissions in the first place just assuming that no one would set up their roles that way, but i guess you never know...

**Comment by BryanEngler** [comment]
not sure if the pr will update when you reopen it but the branch should be at https://github.com/BryanEngler/liferay-portal/commit/a6f46b675e7a617ab95bdeef65770706e8bc3017 just so you can verify

**Comment by jonathanmccann** [comment]
I can't seem to reopen this pull request. Can you send me a new one? Thanks.

**Pull request closed without merging**
