### PR TITLE
LPS-57318

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@ssmith353 Should we fix the other usages of "+= StringPool.FORWARD_SLASH" as well or are the other frequencies not broken? Also, couldn't we just use "*" instead of "1/1" to denote every day?

**Comment by ssmith353** [comment]
Hey @jonathanmccann, the daily frequency is the only one that would have an issue with the += StringPool.FORWARD_SLASH. Since it is the only one that could create a date that would forever imply a specific day of the month, every month, when that was not intended. 

See the day of week schedule - it is dependent on each day of the week chosen, like Day 1, and will occur on its intended regular basis based on the cron data created. 

According to Quartz the * is an appropriate trigger for that column. I'll test it to see if it produces the same result.

**Comment by jonathanmccann** [comment]
Closing in favor of using "*", fixing monthly frequency, and adding a test.

**Pull request closed without merging**
