### PR TITLE
LPS-69227 Use *ModelListener instead

### PR DESCRIPTION
**Pull request by cleydyr**
Happy New Year! :)

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @cleydyr,

Reading over Daniel's comment (https://github.com/danielkocsis/liferay-portal/pull/586#issuecomment-261945372), it seems like he wanted a model listener on the Company object listening for a change to the locale. I was wondering why you chose to make the listener for when a User object is updated?

Thanks.

**Comment by cleydyr** [comment]
Hey, @jonathanmccann. You're correct about Daniel's comment. But the thing is that the locale information is actually stored on the User table. Liferay uses the default user entry to store that information for the company, so it makes more sense to listen for changes on the User, which has the update local information, instead of listening for Company.

Regards.

**Comment by jonathanmccann** [comment]
Perfect, thanks for the explanation!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/591

**Pull request closed without merging**
