### PR TITLE
LPS-71842

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-71842

This issue only affects bundled release versions of DXP.  Although this could be considered a fix for the release team to take care of, it really doesn't make sense to have the scripting executors in different locations.  This fix resolves the error for DXP bundles, and organizes the modules folder just a little more.

Let me know if you have any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Do I need to modify this commit by adding the relang lines above the '-fixupmessages' for python and ruby?  https://github.com/jonathanmccann/liferay-portal/pull/1286/commits/784328c6c354e97f0bf655647476459039be46b5

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/1297

**Pull request closed without merging**
