### PR TITLE
LPS-66637

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Bryan,

Did you test the steps for LPS-51671 and confirm that we did not reintroduce that issue? Also, the commit message for that fix reads "Since we decided to not update portlet last publish dates when remote staging, then do not rely on them when calculating start date" so do we now update the dates when doing remote staging?

Thanks.

**Comment by BryanEngler** [comment]
ya i had tested LPS-51671 and from what i saw it looks good.

if you look at https://issues.liferay.com/browse/LPS-55458 and https://issues.liferay.com/browse/LPS-52793, it seems that both of those tickets were basically reporting this same issue, and both were closed without verifying that the issue was actually fixed. in my tests i saw that we are updating the last publish date with remote staging so i think we can safely remove the check now

**Comment by BryanEngler** [comment]
you can also reference 12e264a5c19625b65dd9cef27bbd62e673e8cbda

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1497

**Pull request closed without merging**
