### PR TITLE
LPS-78433 | master

### PR DESCRIPTION
**Pull request by MichaelPrigge**
https://issues.liferay.com/browse/LPS-78433

This resolves a regression caused by [LPS-73350](https://issues.liferay.com/browse/LPS-73350) fb2241828d95722815bf9543967c8da2277e10be.

This fix is also a blocker for the backport of LPS-73350 which a customer is waiting on.

Testing is not currently possible on master but this fix works on 7.0.x after backporting the above mentioned LPS ticket.

Let me know if you have any questions. Thanks!

/cc @JaredDomio

### CODE REVIEW

**Comment by MichaelPrigge** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@MichaelPrigge These test failures seem relevant. I'm going to re-run the tests to confirm.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by MichaelPrigge** [comment]
@jonathanmccann, you're right they do look related. Will wait to see the second run results.

**Comment by jonathanmccann** [comment]
Looks like they're still occurring and I haven't seen them on other pulls today. I'll go ahead and close this out for the time being while they are investigated.

**Pull request closed without merging**
