### PR TITLE
LPS-68191

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
I feel like these errors are stemming from the changes made, what do you think?

**Comment by BryanEngler** [comment]
ya i saw errors like that on https://github.com/BryanEngler/liferay-portal/pull/192 so i had eric update the tests on https://github.com/BryanEngler/liferay-portal/pull/193 and i didnt see the failures there, but ya it still seems broken in these failures...

**Comment by jonathanmccann** [comment]
Alright, I'll ask Angelo to have someone look over the fix and the ticket while Eric is out.

**Pull request closed without merging**
