### PR TITLE
[TECHNICAL-SUPPORT] LPS-69746

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@joshuacords @SamZiemer These test failures are due to the change in the UI for the name. Can you please work with QA to figure out if we are responsible to fix the tests or if there is someone I can send this pull to and they can fix the test failures?

**Comment by SamZiemer** [comment]
The changes to fix will be made and sent on a new PR.

**Pull request closed without merging**
