### PR TITLE
LPS-75732

### PR DESCRIPTION
**Pull request by mbowerman**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Where was this translation generated?

**Comment by fortunatomaldonado** [comment]
@jonathanmccann Ruud Kluivers did the translation after I got permission from Nicole Mak.

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@fortunatomaldonado Thanks for that information.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/1798

**Pull request closed without merging**
