### PR TITLE
LPS-78109 Call Correct cssClass for Shopping Categories Kebab Menu Po…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…sition

Resent from https://github.com/gregory-bretall/liferay-portal/pull/24

@brianikim

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Is there a reason we need this CSS at all? Looking at other places where there is similar functionality, there is no CSS and removing it seems to look fine.

**Comment by gregory-bretall** [comment]
I'm not sure. @brianikim could you test what the behavior is for this fix with the cssClass removed from the JSPs entirely? Please leave a comment on this PR once you've done so and if Jonathan is right and removing the cssClass attribute entirely also fixes the issue without causing any regressions then I'll close this PR and you can resend your changes to me.

**Comment by brianikim** [comment]
@jonathanmccann @gregory-bretall ,
Removing it causes no issue. I will resend a PR with the updated change.

**Pull request closed without merging**
