### PR TITLE
LPS-55602 Exclude article content from keyword search to improve performance when using DB

### PR DESCRIPTION
**Pull request by arbetts**
…ct non-searchable articles

### CODE REVIEW

**Comment by jonathanmccann** [comment]
This commit message doesn't seem to line up with the LPS title or steps to reproduce. Please update.

**Comment by arbetts** [comment]
will update pull with better message

**Comment by arbetts** [comment]
ok.. updated message and did a force push

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eduardo for further review: https://github.com/epgarcia/liferay-portal/pull/267

**Pull request closed without merging**
