### PR TITLE
LPS-69601 User not redirected to set new password when require password reset is true but password policy does not require password reset

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-69601

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
@jonathanmccann I've updated the fix and have rebased it on top of the latest commits in master. I also added an explanation of my fix [here](https://issues.liferay.com/browse/LPS-69601?focusedCommentId=910323&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-910323).

Please let me know if you have any questions or if the fix needs additional revisions.

Thanks!

**Comment by dustinryerson** [comment]
Please hold off on pushing this forward until I do one last round of testing tomorrow. Thank you!

**Comment by dustinryerson** [comment]
Hey @jonathanmccann, sorry for the delay. I've confirmed in my testing that this fix works. Please move forward with the code review whenever you can and let me know if you have any questions.

Thanks!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Tomáš for further review: https://github.com/topolik/liferay-portal/pull/405

**Pull request closed without merging**
