### PR TITLE
LPS-55223

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/692

**Comment by jonathanmccann** [comment]
@BryanEngler @ChrisKian 

If you enter "13/01/2015" as the date, it adds a month and comes out being "01/01/2016" and if you enter "01/111/2015" it comes out as "04/21/2015". Is there any way to avoid this day/month addition?

**Comment by ChrisKian** [comment]
We can probably avoid it, however it may be a requirement to leave it as-is.  See: http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.12

Look specifically at item 5 for months, and item 8 for days on the MakeDay() function.  We follow this specification in other parts of alloy, so I assume it is relevant here as well.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/1231

**Pull request closed without merging**
