### PR TITLE
LPS-54080 document library exception handling

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hmmm, I didn't change PermissionsURLTag.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
The NoSuchDirectoryException is used in the plugins. Please send a pull to resolve those as well.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/2347

**Pull request closed without merging**
