### PR TITLE
LPS-64536

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by arbetts** [comment]
@jonathanmccann 
microblogs test failure is: 
"Microblogs#deleteStatus --> FAILED: WaitForSPARefresh#waitForSPARefresh"

scanXMLLog failure is:
"org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect)" when amending a background task with className = "com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor"

I think these might be unrelated to my changes.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/4088

**Pull request closed without merging**
