### PR TITLE
LPS-88224 - fixed shallow copy in layout staging clone methods

### PR DESCRIPTION
**Pull request by ajsampang67**
Relevant Tickets -
https://issues.liferay.com/browse/LPS-88224

The clone methods call a constructor, which would do a shallow copy of the Layout/LayoutRevision/LayoutSet objects. Added a .clone() to the parameters passed to the constructor to deep copy.

### CODE REVIEW

**Comment by ajsampang67** [comment]
ci:test:relevant

**Comment by ajsampang67** [comment]
ci:test:sf

**Comment by ajsampang67** [comment]
Checking test failures now

**Comment by ajsampang67** [comment]
From what I can tell, test failures are unrelated. Looks like some data could not be imported due to incorrect versions. Tried to recreate failures (with OOTB portlets/pages) and behavior was correct, with no error.

**Comment by jonathanmccann** [comment]
@ajsampang67 It should be fine since they're all happening in upstream as well. I'll push this along by the end of the day.

**Comment by jonathanmccann** [comment]
https://github.com/moltam89/liferay-portal/pull/456

**Pull request closed without merging**
