### PR TITLE
Lps 77942 pr

### PR DESCRIPTION
**Pull request by gregory-bretall**
Resent from https://github.com/gregory-bretall/liferay-portal/pull/16
@brianikim

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
If the tests pass on your branch, we don't need to re-run them.

**Comment by gregory-bretall** [comment]
Thanks for letting me know

**Comment by jonathanmccann** [comment]
Reviewed and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/55352

**Pull request closed without merging**
