### PR TITLE
[TECHNICAL-SUPPORT] LPS-66642

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Michael,

Why does "LocaleUtil.getDefault()" return a locale that is not enabled? This seems like the bug we should be fixing instead of working around the issue and allowing for a locale that the user explicitly disabled.

Thanks.

**Comment by mbowerman** [comment]
Hey @jonathanmccann,

The "default" locale is apparently being set according to the user.language and user.country attributes in the _properties map in SystemProperties.java... but I couldn't find any information about how the _properties map in SystemProperties.java was generated. So I wasn't sure if I should change the way we set the default locale or not.

**Comment by jonathanmccann** [comment]
It seems like it's coming from "system.properties", if I'm understanding you correctly:

```
    #
    # Set the default locale used by Liferay. This locale is no longer set at
    # the VM level. See LEP-2584.
    #
    user.country=US
    user.language=en
```

Granted, the portal property you set should have overridden that:

```
    #
    # This sets the default locale of the portal, overriding the properties
    # "user.language" and "user.country" specified in system.properties.
    #
    #company.default.locale=en_US
```

It also could be that you need to set the "locales" property to the two locales you wish to use. Could you investigate that a little bit more and let me know what you find?

**Comment by mbowerman** [comment]
It looks like the "locales" portal property specifies the available locales, and the "locales.enabled" portal property specifies the enabled locales. Not sure what the difference is, but I'm assuming that "locales.enabled" needs to be a subset of "locales", and the default locale should be in "locales.enabled".

Apparently the "company.default.locale" portal property was disabled as of [LPS-30667](https://issues.liferay.com/browse/LPS-30667), so it's completely irrelevant here. I guess the customer put it in their portal properties a long time ago, and was never told that it got disabled (and none of the rest of us knew either).

Do you know if the system.properties file is meant to be accessible and modifiable by the user? I couldn't even find the file in my bundle (and putting the system properties I wanted to modify inside of portal-ext.properties didn't work). I was able to find system.properties in the source code, but I have no idea what happens to it when it gets compiled.

If the user is supposed to be able to easily write to the system.properties file, I would like to make a fix that causes the portal to refuse to start if there is a conflict between the "locales" portal property, the "locales.enabled" portal property, and the "user.country" and "user.language" system properties, and instead throws an error telling the user that they need to make their locales properties consistent before starting Liferay. What do you think?

**Comment by jonathanmccann** [comment]
The "system.properties" file gets placed inside of the "portal-impl.jar". You can customize the same way you would "portal.properties" by specifying a "system-ext.properties". I believe it would go within "ROOT/WEB-INF/classes", but I'm not entirely sure.

I'm not sure if refusing to start the portal would be an accepted idea, but I think you're going in the right direction. Perhaps if they do not match, you can simple use the default locale that is set within portal.properties instead? Also, it might be good to look into why we have extremely similar properties in two different places. As shown by this issue, it seems to be a recipe for disaster.

I'll go ahead and close this for now, but let me know if you need anything from me.

**Pull request closed without merging**
