### PR TITLE
LPS-71408

### PR DESCRIPTION
**Pull request by mbowerman**
Hey @jonathanmccann,

I'm sending this directly to you since the LPP ticket is past its due date and we've been getting some pressure from the customer.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@mbowerman Which part of the new dynamic query accounts for ```WHERE (AssetEntry.classPK IS NULL)```?

Also, could you please explain what the follow blocks of code are doing:

```
assetEntryDynamicQuery.add(
	classNameIdProperty.eq(classNameId));
```

```
dynamicQuery.add(
	fileEntryIdProperty.notIn(assetEntryDynamicQuery));
```

**Comment by mbowerman** [comment]
@jonathanmccann The dynamicQuery isn't a "literal translation" of the SQL query, so to speak, but it should return the same results. The "literal translation" SQL query of the dynamic query that I made should be this:

`SELECT
	{DLFileEntry.*} 
FROM
	DLFileEntry
WHERE
	DLFileEntry.fileEntryId NOT IN 
	(
		SELECT
			AssetEntry.classPK
		FROM
			AssetEntry
		WHERE
			AssetEntry.classNameId = ?
	)
`

And the classNameId parameter would be the DLFileEntry class name id.

Hopefully this clarifies the matter. If you believe that the query I mentioned above is not equivalent to the dynamicQuery that I created, or if you believe that it will not return the same set of results as the query listed in portal.xml:

`SELECT
				{DLFileEntry.*}
			FROM
				DLFileEntry
			LEFT JOIN
				AssetEntry ON
					(AssetEntry.classPK = DLFileEntry.fileEntryId)
			WHERE
				(AssetEntry.classPK IS NULL)
`

then please let me know and we can investigate further.

**Comment by jonathanmccann** [comment]
Thanks for the explanation, I have a better understanding of the fix now. To me, they look like they'd accomplish the same thing, but let's see what Sergio says about it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3871

**Pull request closed without merging**
