### PR TITLE
LPS-57240

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@ChrisKian @BryanEngler 

1. What happens if there are two LDAP servers, one being used as a backup, and the first LDAP server is deleted? Will the user's ldapServerId be set to -1 or will it transfer over to the secondary LDAP server? I think that upon logging in again, that user's ldapServerId will be reset to whichever server they logged in from, but I'm not sure. Also, I don't know if the lapse of not being considered from LDAP would cause any issues.
2. Testing against the ldapServerId should be either ">=" or "<". See https://github.com/liferay/liferay-portal/blob/master/modules/portal/portal-ldap/src/com/liferay/portal/ldap/DefaultPortalLDAP.java#L347 and https://github.com/liferay/liferay-portal/blob/master/modules/portal/portal-authenticator-ldap/src/com/liferay/portal/authenticator/ldap/LDAPAuth.java#L507
3. It might be good to also disable the password text field so that users cannot even try to update it. In the same vein, wouldn't we have to disable the forgot password feature as well?

Let me know what you think.

**Comment by ChrisKian** [comment]
1.  If the primary LDAP server was deleted, the ldapServerId field for the user would be set to -1.  Re-logging in should re-import the LDAP users, thus setting the ldapServerId to the back-up server.  The only issue which could arise is if the admin reset the users PW directly after deleting the LDAP server, but before re-importing the backup.  This would result in the user being able to log in with the reset PW and the LDAP PW, but this would only persist until their data was re-imported.  Also, any other changes made in LR would not reflect to the LDAP.

I'm not sure how we would check if a user was in the backup server without going through each user and checking if they belong in said LDAP.

2.  ldapServerId < 1 it is then.  The default user has an ldapServerId of 0, so I just wanted to make sure they were considered non-LDAP.

3.  For consistency and simplification, we just decided to use the UserPasswordException class.  This class also gives us a good way of displaying to the admin why they cannot change the PW, and how to be able to do so.

Assuming the forgot password feature resets the PW and export is not enabled, yes I believe we would need to disable it.

I trust your judgement, so just let me know how I should proceed.

**Comment by jonathanmccann** [comment]
Hey Chris,

Unfortunately, I didn't have time today to look over your comments in detail. I would suggest either talking it over with Dustin or MCD to get their thoughts on our concerns and see how we should proceed. I'll go ahead and close this, but if nothing needs to be changed go ahead and forward it to Dustin.

Thanks!

**Pull request closed without merging**
