### PR TITLE
Lps 73031 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi, Jonathan, This change updates the upgradeDocumentLibraryPortletId class. In DXP we have removed the Documents and Media Display portlet, however, we did not take into account instances where a display portlet was made non-instantiable. This leads to an issue where an index unique constraint is violated in resource permission and portlet preferences.

I added an instance ID to all documents and media display and documents and media portlets. I also needed to update any layouts with either portlet placed in the layout.

Let me know if there are any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
A couple of questions:

1. Do we not need the logic to reuse portlet IDs ```updateDuplicatePortletPreferences``` like we do in ```updateDuplicateResourcePermissions```?

2. In https://github.com/jonathanmccann/liferay-portal/pull/1346/commits/35857a7fc3e22aae253c221fe7d1b257f78c6b9f what is the advantage of using "plidsEncountered"? We already have the typeSettings fetched from the database so it seems it would be cleaner to simply always use that value.

**Comment by jonathanmccann** [comment]
Answers:

1. Portlet Preferences will be unique and only need to be updated once.

2. The same layout may be returned by multiple portlet preferences so instead of overwriting previous changes, keep track of them and update all changes at once.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3908

**Pull request closed without merging**
