### PR TITLE
[TECHNICAL-SUPPORT] LPS-73354

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @thomasstew

Notes from Thomas

> Relevant Ticket:
> [LPS-73354](https://issues.liferay.com/browse/LPS-73354)
> 
> In this bug, the [$TO_ADDRESS$] and [$TO_NAME$] variables are incorrectly set to the value of [$FROM_ADDRESS$] when creating email notifications for Asset Publisher subscriptions. The emails are delivered to the correct recipients, but if we try to name those recipients in the email body using these variables, they are mishandled.
> 
> Bulk emails are meant to have the same email body, which means no personalized names.
> Since we want to be able to utilize these variables within email templates for Asset Publisher subscriptions, it is best to not send them in bulk - since we are then able to individualize each email sent out with the respective names and addresses of the recipients.
> 
> Let me know if you have any questions!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@thomasstew Is the default ```false```? If so, we can simply remove this line of code.

**Comment by thomasstew** [comment]
Hi @jonathanmccann,
It appears that it does default to false. Should I resend?

**Comment by jonathanmccann** [comment]
That's ok, I'll remove and pass it along. Thanks for looking that up.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/1010

**Pull request closed without merging**
