### PR TITLE
LPS-73857

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-73857

Let me know if you have any questions on this one.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Test failures seem unrelated; I didn't touch LayoutsTree.java.

**Comment by jonathanmccann** [comment]
Is the path either going to be a directory or a file? Or is there a chance that both delete methods need to be executed?

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/3952

**Pull request closed without merging**
