### PR TITLE
[Technical Support] LPS-59967

### PR DESCRIPTION
**Pull request by dustinryerson**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Hopefully the tests pass on this run, but in case they don't you can reference https://github.com/dustinryerson/liferay-portal/pull/44. I ran the tests there to ensure the one test that was consistently failing for my previous pull passed for this new fix.

**Comment by jonathanmccann** [comment]
Hey @dustinryerson, should we actually remove the property or simply return and not set anything? It seems like from the documentation it should be removed (IE there is already a parameter "test", we pass in null for it, it should be removed).

**Comment by dustinryerson** [comment]
Let me check and get back to you on this.

**Comment by dustinryerson** [comment]
Gonna resend this one more time when I have a better solution.

**Pull request closed without merging**
