### PR TITLE
LPS-68191

### PR DESCRIPTION
**Pull request by ericyanLr**
Hey Jonathan,

I am resending this pull request as a follow-up to the previous pr: https://github.com/jonathanmccann/liferay-portal/pull/1102.
I have not made any additional changes, but simply rebased the changes to the latest master.

## Status
Currently, all tests pass on CI and also pass when manually running gradlew testIntegration.

## Summary
The Asset Publisher Configuration has options to select different Asset Entry types, such as a Web Content Article, Web Content Structure, Document and Document Type. 

**Current Behavior**
When exporting an Asset Publisher portlet, all available Asset Entry types are being included.
- This means that all Asset Entry types are being included, even if they are not selected. 
- This causes missing-references exception when attempting to import the exported lar into a new Liferay Instance.

**Expected Behavior**
When exporting an Asset Publisher portlet, only selected Asset Entry types in the portlet's configuration should be be required. 
- This means that we should only include Asset Entry types that are related to the selected options.

## Notes
Eduardo Garcia helped take a look at my earlier attempts to resolve this issue.
He noted that he can take a look at the PR when it's ready:
> Hey Eric,
Thanks for your comments. Send me the PR when it's ready and I'll try to solve any remaining questions about Asset Publisher preferences with Julio and Eudaldo during the review.

---
Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ericyanLr Is that source formatting for your code or something else? If it's not yours, feel free to reopen.

**Comment by ericyanLr** [comment]
@jonathanmccann The source formatting error refers to the key "draft-saved-at-x," which is not related to my code changes. I'll reopen the pr, thanks!

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@ericyanLr Can you please incorporate Bryan's changes from https://github.com/jonathanmccann/liferay-portal/pull/1102 and push up the branch again? Thanks.

**Comment by ericyanLr** [comment]
Hey @jonathanmccann, I just incorporated Bryan's changes from #1102.
Thanks!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eduardo for further review: https://github.com/epgarcia/liferay-portal/pull/564

**Pull request closed without merging**
