### PR TITLE
LPS-60091 Verify and Test

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@Preston-Crary Shouldn't this be in an upgrade process since after the fix is in place, it should never happen again?

**Comment by Preston-Crary** [comment]
I thought upgrades are for when we change the database and verify processes are for when we have data integrity issues. I would hope with any verify we write the issue would never happen again. Maybe we should only have verify processes when we backport and should always have them as an upgrade for the next version, but that's not how we have done it in the past.

**Comment by jonathanmccann** [comment]
I'm trying to figure out myself as well. The rule I've always gone by is that verify processes are for things that run multiple times and upgrade processes should only be run once, that's why I thought this would be suitable for an upgrade process. In these cases, I agree, adding an upgrade process to Master and then backporting a verify process makes the most sense. I'm not sure who we can talk to about which to use in what situation but it would be good to figure out a rule to follow for all future fixes.

**Comment by Preston-Crary** [comment]
Are there any verify processes that should need to be run more than once?

**Comment by jonathanmccann** [comment]
Closing this pull for now. Once we figure out what should be a verify and what should be an upgrade process, feel free to resend this fix.

**Pull request closed without merging**
