### PR TITLE
LPS-80343 Unescape File Names for Database Queries

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-80343

Hello @jonathanmccann ,

The issue here is that the files with names that have ampersand (ex. %%file.txt) attached on a messageboards thread cannot be moved to the recycle bin and/or deleted using the available options.

It is the same scenario as https://github.com/jonathanmccann/liferay-portal/pull/1617, but for MessageBoards.

However, the solution is implemented differently because an attachmentshelper class does not exist for messageboards.

For messageboards, the unescape needs to happen in EditMessageAttachmentsMVCActionCommand.java as that is where the fileNames are being fetched from the requests before being passed off to  MBMessageServiceImpl and MBMessageLocalServiceImpl for permission checks and queries.

If you have any questions, please let me know. Thanks.

Sincerely,
Brian KIm

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by jonathanmccann** [comment]
I don't believe we need to change the implementation for `deleteTempAttachment`. Could you please double check that one?

**Comment by brianikim** [comment]
Of course, @jonathanmccann.

**Comment by brianikim** [comment]
Hello @jonathanmccann ,

I have removed the change for deleteTempAttachment. Thank you for catching that!

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/4354

**Pull request closed without merging**
