### PR TITLE
LPS-69171

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-69171

This is a pretty big commit, so let me know if you have any questions

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@ChrisKian Please take a look at these test failures as they're not happening on other pulls.

**Comment by ChrisKian** [comment]
Hey @jonathanmccann,

Here's what I did with the test failures:
1. Couldn't really figure it out, this one might always be failing?
2i. I didn't cause this issue, although it is in a file I touched.
2ii. fixed
2iii. fixed
3. Not sure about this one either, doesn't seem like it's on me.
 4, 5. These two are same issue.  Fixed
6... I assume it's 4 and 5 continued, but with different database types.

I'll look through the failures again after retesting.  Sorry for ramming your repo!

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
The source formatting error is probably due to the line length excludes in ```source-formatter.properties```. I'm not sure about the other ones though, since they're not happening elsewhere still.

**Comment by ChrisKian** [comment]
The source formatter is failing here due to the line being too long: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L544

The other errors are on me.  It's hard for me to get them without seeing the fail logs because I don't have my intelliJ set up properly for test files.  I've fixed all the ones I could find though.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
The only issue which is on me is #3.  I added a throws clause to Group.getLogoURL(); do I need to override the method instead or is it something else?  Can we ignore this test?

**Comment by jonathanmccann** [comment]
Again, I still think the source formatting issue is something you need to fix. My previous comment:

```The source formatting error is probably due to the line length excludes in source-formatter.properties.```

For the third test, did you directly modify Group.java or did you make the changes in GroupImpl.java and then rebuild the services?

**Comment by ChrisKian** [comment]
I tried to resolve the SF issue as best as I could without renaming the class altogether.  I have pretty much no idea what the class does, so I didn't want to mess with it too much.

As for number 3, I've both manually made and generated the changes, and the only difference is a line break; no incrementation of packageinfo or bnd files.  Maybe with the linebreak it won't break the test?

Once all the tests pass, I'll rebase and create a new PR so everything is cleaned up; sorry about all the trouble!

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
I don't think those tests are one me.  Would you like me to rebase and send another PR?

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
https://github.com/robertoDiaz/liferay-portal/pull/497

**Pull request closed without merging**
