### PR TITLE
[TECHNICAL-SUPPORT] LPS-71521

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
This doesn't seem to be working correctly when making the parent text box that contains the boolean field repeatable.

If the text box is repeatable but the boolean field is not (which is what the client reported but not the steps you laid out on the LPS), then an error is thrown stating that the size of the values for the boolean field is incorrect. If both the text box and the boolean field are repeatable, the two booleans are applied to the first text box and the second text box has no boolean.

Please take another look at this fix and try it with many different combinations of fields, nested fields, and repeatable fields to make sure that everything is working properly.

**Comment by mbowerman** [comment]
@jonathanmccann,

I was unable to reproduce either of the issues that you mentioned.

> If the text box is repeatable but the boolean field is not (which is what the client reported but not the steps you laid out on the LPS), then an error is thrown stating that the size of the values for the boolean field is incorrect. 

Did you add a second text value to the text field? If not, then throwing an error here would be the expected behavior, because you cannot possibly have more instances of a non-repeatable child field than its parent field. When I tested with two values for the text field and two values of the boolean field, it worked just fine.

> If both the text box and the boolean field are repeatable, the two booleans are applied to the first text box and the second text box has no boolean.

That sounds to me like you forgot to update the _fieldsDisplay field. Can you double-check to make sure that your _fieldsDisplay has all the fields listed in the right order? For instance, when I tested it, I had my code to add the _fieldsDisplay value as follows:

```
StringBundler sb = new StringBundler(15);

sb.append(textFieldName);
sb.append("_INSTANCE_");
sb.append(StringUtil.randomString());
sb.append(StringPool.COMMA);

sb.append(booleanFieldName);
sb.append("_INSTANCE_");
sb.append(StringUtil.randomString());
sb.append(StringPool.COMMA);

sb.append(textFieldName);
sb.append("_INSTANCE_");
sb.append(StringUtil.randomString());
sb.append(StringPool.COMMA);

sb.append(booleanFieldName);
sb.append("_INSTANCE_");
sb.append(StringUtil.randomString());

fieldsMap.put("_fieldsDisplay", sb.toString());
```

**Comment by jonathanmccann** [comment]
I think what was throwing me off was that the text values were just a string, not an array:

```fieldsMap.put(textFieldName, "X1, X2");```

I'll go ahead and reopen this, but I have one more question. Are the types you enumerated exhaustive or do we need to handle others (BigDecimal, Date, etc.)?

**Comment by mbowerman** [comment]
Yeah, sorry about that. I copied some of it from the client's confusing steps, but I probably should have modified that String to make it more clear.

The types that I enumerated include `Serializable` and every primitive. Because the values are required to be serializable, I believe that this should be sufficient to cover every case.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/1849

**Pull request closed without merging**
