### PR TITLE
LPS-74784

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Shouldn't we get rid of the unused class as well? Feel free to force-push if that's the case.

**Comment by mbowerman** [comment]
If we remove it, don't we risk causing semantic versioning problems? Should we just deprecate it instead?

**Comment by jonathanmccann** [comment]
Either way, we should do something. Not sure if it would trigger a version increase or not.

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
OK, I've deleted the unused class and we can see whether or not it passes the CI.

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Ugh, that's confusing. Can't it respond more gracefully when you call "ci:stop"?

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/4007

**Pull request closed without merging**
