### PR TITLE
LPS 75045 - Reindex affected users when changing parent organization.

### PR DESCRIPTION
**Pull request by ericyanLr**
@wanderlast

Notes from Lianne:

> ### Links:
> LPS: https://issues.liferay.com/browse/LPS-75045
> Related LPP: https://issues.liferay.com/browse/LPP-27284
> 
> Hi @ericyanLr 
> 
> ## _Synopsis_
> The issue is that when a parent organization is added or removed from an organization the permissions of the organization members are not updated. The problem can be 'fixed' currently by restarting the server, or in Liferay's control panel under Server Administration -> "Clear content cached across the cluster".
> 
> The root cause of the bug is that users are not reindexed when organizations are updated, meaning that adding or removing a parent organization does not update the user's organizational permissions as it should.
> 
> ## _Related History_
> This problem has cropped up multiple times with other, similar areas of the code. Specifically [LPS-68988](https://issues.liferay.com/browse/LPS-68988) fixed it with regards to UserLocalServiceImpl functions. This fix is near identical to the fix I applied--calling a reindex whenever a change is made.
> 
> Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
Updated with SF commit, will be restarting CI test.

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:retest

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
A couple of things:

1. Combine your source formatting commits with the commits that introduced them. In this case, it would be squashing your two commits together. It helps keep the history clean and makes it easier to review.

2. This fix does not appear like it would perform well. We're reindexing users one by one and a client might have upwards of hundreds of thousands of users. When the user changes the parent organization, the page will hang for several minutes waiting for all of the users to be reindexed. This should either be done in parallel by an actionable dynamic query or even in a callback.

If you have questions about how to increase this performance, please ask Michael Bowerman about it as he will probably have some good ideas.

**Pull request closed without merging**
