### PR TITLE
LPS-76766

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-76766

The first 5 commits make a moderate performance boost by not fetching each group one at a time, and not calling getPortletURL() over and over.

The final commit resolves an issue where the managementBarFilterItems list has too many large values, resulting in memory issues.  This issue utilizes changes from LPS-74910 in order to calculate the selectedGroupIds list after the request, so we don't have to load it up with 40,000+ characters for 5000 entries.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/1332

**Pull request closed without merging**
