### PR TITLE
LPS-77038

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-77038

Fixes issue from LPS-74910 where we add out-of-scope groups to asset list.  Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:test

**Comment by ChrisKian** [comment]
I fixed the SF error and forced a push

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
The latest failing tests are all passing for me locally.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/1350

**Pull request closed without merging**
