### PR TITLE
LPS-64627

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-64627

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Instead of creating a new variable "var elapsed = instance._elapsed;" can we just reuse "instance._elapsed"?

**Comment by dustinryerson** [comment]
Hey @jonathanmccann, I considered that when working on the fix but chose to continue using the elapsed variable because the value is being reused a few times within the _startTimer method. The _getBanner method is also similar. That being said I think it would be reasonable to simply use "instance._elapsed" rather than assigning it to a variable if that simplifies the code or makes it easier to read. Please feel free to make the change if you think it would be best.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/jonmak08/liferay-portal/pull/1526

**Pull request closed without merging**
