### PR TITLE
LPS-79302 Fix Inconsistencies in Entry Deletion Between Activities an…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…d Microblogs Portlet

https://issues.liferay.com/browse/LPS-79302

CI Tester failed on the original PR.

Resent from https://github.com/gregory-bretall/liferay-portal/pull/55

@brianikim

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by brianikim** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@brianikim @gregory-bretall There is an issue when using the type field to fetch back the appropriate entries. If you create a secondary user with administrator privileges and repost the Microblogs entry it has a type of 2. This will encounter the same issue as before since you're limiting it to entries of type 0. It would be better to utilize the `parentMicroblogsEntryId` to fetch back the replies and then delete those.

Also, for future fixes, be sure to use or create a constant instead of using magic numbers. Instead of comparing the type to 0 or adding 1 to the type, it would be clearer to use the constants in https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/microblogs/microblogs-api/src/main/java/com/liferay/microblogs/model/MicroblogsEntryConstants.java#L22-L24

Please let me know if you have any questions.

**Comment by jonathanmccann** [comment]
This should also fix another bug I found where if you repost an entry and then delete the original entry, the reposted entry doesn't display any information and an exception is logged.

**Comment by brianikim** [comment]
hello @jonathanmccann ,

Thank you for that catch on the secondary user with administrator privileges. That is something I should have definitely checked. I will update the PR with your suggested changes. Thanks.

**Pull request closed without merging**
