### PR TITLE
LPS-70361

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @jonathanmccann,

This is a very high priority issue for a client, so Chris asked me to send the pull request directly to you. Also, we were wondering if we could do an SDH for this.

You may be concerned that we pass companyId in when we call GroupLocalServiceUtil.fetchFriendlyURLGroup. However, we can safely assume that the group (if it exists) will be in the same company because of the way replaceExportHostname works. replaceExportHostname will prevent the URL from being validated if it doesn't begin with the current company's virtualHost.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mbowerman I don't feel comfortable approving an SDH as I don't know enough about this area. If you'd like you can get @holatuwol opinion on it and if he approves it.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/598

**Pull request closed without merging**
