### PR TITLE
LPS-68449

### PR DESCRIPTION
**Pull request by ChrisKian**
I made changes based off Miguel's comments here: https://github.com/migue/liferay-portal/pull/869#issuecomment-251395345

For his second comment, I found we do not retrieve the name column for either the DDMStucture nor DDMStructureVersion tables, so we should be safe to switch it to a CLOB type.

Let me know if I missed anything.

https://issues.liferay.com/browse/LPS-68449

### CODE REVIEW

**Comment by ChrisKian** [comment]
My changes had nothing to do with BlogsStatsUserLocalServiceWrapper.java.

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Hey Chris,

Please take a look at the following:

1. Run the source formatter
2. Add your name as the author of "UpgradeDDMStructureName" and put in our copyright and license at the beginning of the file
3. Separate out the manual changes from the generated ones in https://github.com/jonathanmccann/liferay-portal/pull/1080/commits/39e96d3ea26451d3aa1eb676e4a1e9c35d9c6137

Thanks.

**Comment by ChrisKian** [comment]
Fixed the mistakes, here's the new pull:https://github.com/jonathanmccann/liferay-portal/pull/1081

**Pull request closed without merging**
