### PR TITLE
LPS-60047

### PR DESCRIPTION
**Pull request by ChrisKian**
This issue is currently blocked by LPS-60138.  To work around it, avoid the "isPortletEmbedded" method here: 2b6440e6e09d87bf1491c71be8391868fc7a060a

Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
Looks like source formatter didn't catch some tabbing syntax.  I'll fix it and re-push the branch.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Hey @ChrisKian,

For checking whether the user has permission, would it work to just use the permission checker instead of getting all of the roles?

```
protected boolean hasRoleViewPermission(
		String sourcePortletId, PermissionChecker permissionChecker)
	throws PortalException {

	String sourcePortletPrimaryKey = PortletPermissionUtil.getPrimaryKey(
		getLayout().getPlid(), sourcePortletId);

	return permissionChecker.hasPermission(
		getLayout().getGroupId(), sourcePortletId, sourcePortletPrimaryKey,
		ActionKeys.VIEW);
}
```

Also, I'm not sure what "resourcePermission.setMvccVersion(0);" is doing, but it seems strange to set all of the resource permissions' mvcc version to zero.

Finally, there are some source formatting / performance issues using "getLayout().getPlid()". We shouldn't chain together method calls and also this should be set to a variable to avoid calling getLayout() within a loop.

Let me know if you have any questions or concerns. Thanks!

**Comment by ChrisKian** [comment]
Hey Jonathan,

I'm pretty sure I originally used the hasPermission method.  This led me to an infinite loop, similar to the issue currently blocking this ticket.  I'll double check though.

I believe the MVCC version has to do with whether or not the portlet is default or custom.  In my testing, the only portlets with MVCC set to '1' were portlets on the default site; custom portlets were '0'.

I'll create a variable for getLayout().

**Comment by ChrisKian** [comment]
I testing the permissionChecker.hasPermission() method and found no loop; I must have been using the contains() method or something similar.  Anyways, I added that change as well as the layout change.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3783

**Pull request closed without merging**
