### PR TITLE
LPS-86907 Reset default value when toggled

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-86907

The issue is that when the toggle is off the options are not shown -- however they are still used on submission.  
The change is to reset the value to the default value on toggle.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adolfo for further review: https://github.com/adolfopa/liferay-portal/pull/738

**Pull request closed without merging**
