### PR TITLE
LPS-59894 Fix performance issues with page versioning and admin user's preferences

### PR DESCRIPTION
**Pull request by Preston-Crary**
We were storing tables in the user's preferences.  This resolves the performance issues by reducing the size of the tables and the cost of reading and writing to them.  Then we move the tables out of the user's preferences.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest Forgot to delete when the user is removed. I've updated the pull.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Reviewed and sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1231

**Pull request closed without merging**
